### ISSUE TITLE
Viewgrid and option dataheight

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#208] opened 2016-02-05 20:23 UTC
Viewgrid in combination  with option -> dataheight:500 is show wrong.

**Comment by OlegKi** [comment] 2016-02-05 22:07
Thank you for the bug report. I committed the corresponding [bug fix](https://github.com/free-jqgrid/jqGrid/commit/ae69b2e9d7986fab21b2b3b54d40ec4887799f5e) to GitHub. Please refresh your sources and verify that the problem is solved now.

**Comment by davgino** [comment] 2016-02-06 13:11
Viewgrid in combination with option -> top : 50 and UI tab is show wrong.
Any distance would pass, it has no effect.

**Comment by OlegKi** [comment] 2016-02-06 13:25
Could you prepare the demo which demonstrates the problem? What "is show wrong". It's difficult understand what you mean if you post no pictures, no code and no demo.

**Comment by davgino** [comment] 2016-02-06 17:08
See http://s12.postimg.org/vmeladq2l/viewgrid.png

**Comment by OlegKi** [comment] 2016-02-06 18:14
Which version of free jqGrid you use (the current source from GitHub, 4.12.1, some more early version)? Could you provide the demo which reproduces the problem? Sorry, but I can't fix the problem, which I can't reproduce.

**Comment by OlegKi** [comment] 2016-02-08 01:04
I made some additional changes which can fix the problem which you reported. Please verify whether the problem exist if you use the latest sources from GitHub.

**Comment by davgino** [comment] 2016-02-08 14:43
From a certain point of view it is ok.
I need to use the option   **top : -200**  and is ok.

**Closed** 2016-02-08 14:44 UTC
Labels: bug
