### ISSUE TITLE
noFilterText property and new filterToolbar

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#216] opened 2016-03-08 15:53 UTC
1. If i used noFilterText property for filterToolbar is ok, but for search : true of navigator is bad.
Pls. see http://i.imgur.com/XbEVI7E.png

2. For  new idMode of filterToolbar i receive next error:
TypeError: currentFilters is undefined - line 9237
if (p.search && currentFilters[this.name] != null) {

**Comment by OlegKi** [comment] 2016-03-08 16:48
Thank you very much for the bug report. I committed [the corresponding fix](https://github.com/free-jqgrid/jqGrid/commit/3fda96f2d36a844486a38f3804ddc6b25a120cb4) just now. Please verify that the problem is solved now.

**Comment by davgino** [comment] 2016-03-08 19:39
Partial is ok. Missing from list - noFilterText: 'All'

**Comment by OlegKi** [comment] 2016-03-08 19:57
Sorry, but I don't understand what you mean. Where you are missing? What you are mission and so on.

**Comment by davgino** [comment] 2016-03-08 20:17
The first option should be  : All

**Comment by OlegKi** [comment] 2016-03-08 20:30
**Where it should be?**

In my tests the option `"All"` is the first in the searching toolbar (in case of usage `noFilterText: 'All'` property). The Search Dialog should **not** contain the option `'All'` because all means **no searching rule** (no filter) in the searching toolbar. If one would be do search for `'All'` then one will search for *empty items* and to get no values. Because of that the Searching Dialog the option `'All'` should exist **only in the searching toolber**.

**Comment by davgino** [comment] 2016-03-08 20:42
Ok, I understand.
Another bug. If i used in colmodel option : **searchoptions:{searchhidden: true}**,  a error is at line **9310 **
oSv = (searchoptions.value === undefined ? "" : searchoptions.value) || editoptions.value;

**Comment by OlegKi** [comment] 2016-03-08 21:14
Please, include more details (like the definition of the column in `colModel`), which you use. I analysed the code and made it (see [the changes](https://github.com/free-jqgrid/jqGrid/commit/3cb6433bd2c029e38765f65319d48fe09fdbcff2)) safer in the part, which you pointed. Please retry, whether your current combination of options works now.

**Comment by davgino** [comment] 2016-03-08 21:34
Now, load page not is complete and error is **newFilters is undefined** at line **9521**

**Comment by OlegKi** [comment] 2016-03-08 21:56
Thanks! Could you try once more. The values in the filter toolbar will be refreshed now after setting the filter (setting parameters `postData.filters` and `searching: true`). For example, if one uses *both* the filter toolbar and the searching dialog then the filter will be updated after setting simple searching rule in the searching dialog. The complex searching filters will be ignored.

**Comment by davgino** [comment] 2016-03-09 07:07
Now in searching dialog when i have only **stype:"select",searchoptions:{value:":;T:Platitor;F:Neplatitor"}** without **searchoptions:{searchhidden: true}** error is 
**cm is undefined** at line 8368

Second problem in searching dialog is next: 
Page is loaded corect. I search in searching dialog, then click on Reset button and error is in jquery.min.js - **JSON.parse: unexpected end of data at line 1 column 1 of the JSON data**.

I mention that this error is only click on Reset button in searching dialog.

**Comment by OlegKi** [comment] 2016-03-09 07:47
Sorry, but I can't reproduce the problems. **Could you prepare the demo?**

The error `cm` is undefined at line 8368 could exist only if `options.name` of `createEl` is wrong and the `name` value is not from `colModel`. It's difficult for me to imagine the test case, which reproduce the problem. The error `JSON.parse` is an internal error from probably `$.parseJSON`, but it's difficult for me to find the origin of the problem wittout the demo.

**Comment by OlegKi** [comment] 2016-03-09 08:26
I do could reproduce and fix the problem with Rest button and the internal error in `$.parseJSON`. The error "`cm` is undefined at line 8368" is still unclear for me. The demo or at least more details would be very helpful.

**Comment by davgino** [comment] 2016-03-09 08:40
I use both the filter toolbar and the searching dialog in same grid.

`var grid=$grid.jqGrid({
 	url:'<?php echo JS_MODUL_PATH?>s_diverse.php?q=lista',
  datatype: "json",
 	colNames:['Id','Denumire','ID Extern','J/F','TVA','Analitic','R','CIF sau CNP','Reg.com','Reg.TVA','Adresa','Localitate','Judet','Cod postal','Scadenta','Telefon','Email','Sitweb','Banca','Cont','Categorie','Tara','Blocat','Info'],
 	colModel:[
   		{name:'id',index:'furnizori.id', width:60,align:'center',hidden:false,search:true,frozen:true},
      {name:'denumire',index:'furnizori.denumire', width:200,frozen:true},
      {name:'idextern',index:'furnizori.idextern', width:80,align:'center',hidden:false,search:true},
     	{name:'jsauf',index:'furnizori.jsauf', width:60,align:'center',stype:"select",searchoptions:{value:":;J:Juridica;F:Fizica"}},
     	{name:'tvadn',index:'furnizori.tvadn', width:60,align:'center',stype:"select",searchoptions:{value:":;T:Platitor;F:Neplatitor"}},
   		{name:'analitic',index:'furnizori.analitic', width:60,align:'center'},
  		{name:'r',index:'furnizori.r', width:50,align:'center'},
 			{name:'cfcnp',index:'furnizori.cfcnp', width:90},
 			{name:'regcom',index:'furnizori.regcom', width:100},
 			{name:'regtva',index:'furnizori.regtva', width:70,align:'center',formatter:'checkbox',stype:"select",searchoptions:{value:":;T:Da;F:Nu"}},
	    {name:'adresa',index:'furnizori.adresa', width:160},
    	{name:'loc',index:'furnizori.loc', width:120},
   		{name:'judet',index:'furnizori.judet', width:90},
   		{name:'codpostal',index:'furnizori.codpostal', width:80,align:'center'},
   		{name:'zilescd',index:'furnizori.zilescd', width:70,search:false,align:'center'},
   		{name:'tel',index:'furnizori.tel', width:100},
   		{name:'email',index:'furnizori.email', width:100,formatter:'email'},
   		{name:'sit',index:'furnizori.sit', width:120,hidden:false,align:'center',formatter:'showlink',formatoptions: {
          baseLinkUrl: function (options) {
              
          },
          cellValue: function (options) { return "<a href=http://"+ options.cellValue + " target='_blank'>" + options.cellValue + "</a>";}}
      },
   		{name:'banca',index:'furnizori.banca', width:160},
   		{name:'contbanca',index:'furnizori.contbanca', width:160},
   		{name:'dencategorie',index:'furnizori.dencategorie', width:100},
   		{name:'tara',index:'furnizori.tara', width:120},
   		{name:'blocat',index:'furnizori.blocat', width:60,align:'center',formatter:'checkbox',stype:"select",searchoptions:{value:":;T:Da;F:Nu"}},
   		{name:'obs',index:'furnizori.obs', width:120}
    	],
 	<?php config_rowlist("1","1000");?>
 	autowidth: true,
 	sortable:true,
 	height:300,
  shrinkToFit:false,
  navOptions: {view:true,edit:false,add:false,del:false,search:true,refresh:true },
 	sortname: 'id',
  viewrecords: true,
  sortorder: "desc",
  toolbar:[true,'top'],
  gridview:true,
  caption:"Diverse"
 
});

$grid.jqGrid('navGrid','#pagerfurnizor').jqGrid('filterToolbar');
jQuery(".ui-search-toolbar").hide();`

Server response is:

`{"page":"1","total":1,"records":"1","rows":[{"id":"448","cell":["448","Hard S.r.l.","0","J","D","401"
,"RO","14211881","J33\/472\/2001",false,"Piata  Unirii Nr.67","Buc","SUC","RO-725400","0",""
,"","","","","Toti","Bulga",false,""]}]}`

**Comment by OlegKi** [comment] 2016-03-09 09:53
Sorry, but I still can't reproduce the problem. First of all your code contains syntax error near `baseLinkUrl: function (options) {`. I used `baseLinkUrl: function (options) { return "";}}` instead. I can't debut the code directly. Seconds **it's unclear for me, which exactly error exist currently, and how you reproduce it**. Do you filter the grid by some field? Is the error exist in Searching Dialog? What exactly you do and which error in which line of code you get now? If you can debug the code in your environment, please describe the error more exactly. Alternative you can post me URL to the demo and short test case (what should I do, step by step, to reproduce the problem), which can I use to debug the problem. You can send me any data via email oleg.kiriljuk@ok-soft-gmbh.com if the information is confidential.

I just included some additional tests for input parameters of some functions, to prevent using of undefined `cm`, but I'm not sure what problem exist. I just guess and try to fix some possible problems and to make the code be more safe in some exotic cases.

**Comment by davgino** [comment] 2016-03-09 10:09
I reduced the Code

`<script type="text/javascript">

$(document).ready(function() {

 var $grid=jQuery("#diverse")
 hscreen=$(window).height()-220;

var griddiverse=$grid.jqGrid({
 	url:'<?php echo JS_MODUL_PATH?>s_diverse.php?q=lista',
  datatype: "json",
 	colNames:['Id','Denumire','ID Extern','J/F','TVA'],
 	colModel:[
   		{name:'id',index:'diverse.id', width:60,align:'center'},
      {name:'denumire',index:'diverse.denumire', width:200},
      {name:'idextern',index:'diverse.idextern', width:80,align:'center'},
     	{name:'jsauf',index:'diverse.jsauf', width:60,align:'center',stype:"select",searchoptions:{value:":;J:Juridica;F:Fizica"}},
     	{name:'tvadn',index:'diverse.tvadn', width:60,align:'center',stype:"select",searchoptions:{value:":;T:Platitor;F:Neplatitor"}}
 	],
  rowNum: 30,
  rowList:[10,20,30,50],
 	height:200,
 	pager: '#pagerdiverse',
  navOptions: {view:true,edit:false,add:false,del:false,search:true,refresh:true },
  sortorder: "desc",
  toolbar:[true,'top'],
  gridview:true,
  caption:"Furnizori",
});


$grid.jqGrid('navGrid','#pagerdiverse');

}); // ultim ready


</script>`
 <table id="diverse"></table>
<div id="pagerdiverse"></div>

Server response:
`{"page":"1","total":1,"records":"1","rows":[{"id":"448","cell":["448","Hard S.r.l.","0","J","D"]}]}`

Pls see : http://i.imgur.com/gaaiRrP.png

**Comment by davgino** [comment] 2016-03-09 10:19
At last change of code select field of data not is:
Pls. see http://i.imgur.com/poLKanV.png

**Comment by OlegKi** [comment] 2016-03-09 10:41
Thank you! I hope that I found the reason of the problem now. There are some problems processing of searching request in case when `name` and `index` of `colModel` have different values and one forward only the `index` in internal methods. I will extend the option of internal method `$.jgrid.createEl` and will inform you soon, after I'll create the fixed code.

**Comment by OlegKi** [comment] 2016-03-09 12:35
@davgino : I made more fixes. Please verify that the problem is fixed now. Thank you in advance.

**Comment by davgino** [comment] 2016-03-09 12:47
Now is ok.

**Comment by davgino** [comment] 2016-03-19 19:59
Pls see http://jsfiddle.net/OlegKi/13582dh7/4/
When i search in column Owner an type tyanay, then type a space, cursor is back automat.
I use **filtertoolbar** with **searchOnEnter: false** option.
I do not think that the behavior is correct.

**Comment by OlegKi** [comment] 2016-03-20 12:28
@davgino : Thanks for the bug report! The problem should be fixed now (see [the commit](https://github.com/free-jqgrid/jqGrid/commit/c1320de0ff487f528fc60bc5caddcfef9cb7ac26)).

Please post new issues in the future as separate issues instead of reopening the old one.

**Closed** 2016-03-20 20:01 UTC
Labels: bug
