### ISSUE TITLE
Autoresize on load and grouping headers dont size columns correctly

### ISSUE THREAD

**Issue by salimnanji** [free-jqgrid/jqGrid#163] opened 2015-10-24 17:16 UTC
When using autoresizeOnLoad, and hideFirstGroupCol: true with groupings, one would expect column 'aa' to resize to fit both grouping headers 'aa' and 'bb' (as column data 'aa' is hidden).
See Fiddle: http://jsfiddle.net/gwj8s41p/3/

Similarly, When using just autoresizeOnLoad and grouping, one would expect column 'aa' to resize to fit the grouping headers aa.
See fiddle: http://jsfiddle.net/gwj8s41p/4/

Thank you for the excellent work so far. Much appreciated.

**Comment by OlegKi** [comment] 2015-10-24 22:46
I think a part of problems will be ways if you would remove `width: 500` parameter which set the width value explicitly.

Another problem: the current implementation of `getAutoResizableWidth`, `autoResizeColumn` and `autoResizeAllColumns` columns take in consideration only *visible data rows* and the grouping header row (which has class `jqgroup`) only in case of usage `groupSummaryPos` which contains `"header"`. Such setting makes the grouping header row be without `colSpan` (with `colSpan="1"`). I know that one can improve the algorithm. I will consider to do this in the future, but now I want just test the current version and to publish new version under the number 4.9.3 or 4.10.0. If you would find some errors, which come after the last changes, it would be very helpful.

After publishing the new version I want to spend some time in preparing parts of documentation and many demo examples which I plan to expend permanently. The goal have now for me the highest priority, higher as implementing new features. The problem is that there are already a loot of features which can be used, but the most people didn't know there.

**Comment by salimnanji** [comment] 2015-10-24 23:42
Okay, I'll test it early this week with my project. Thanks.

**Comment by OlegKi** [comment] 2015-11-11 11:46
@salimnanji : Do you have some progress in tests for the issue and [another issue](https://github.com/free-jqgrid/jqGrid/issues/171), which you posted later? Please inform me about the results and close the issues after the corresponding problems will be solved.

**Comment by salimnanji** [comment] 2015-11-11 14:26
I ended up removing auto resizing columns from this specific grid and keeping them as fixed widths as a work around. The other issue I haven't had time to implement yet.

**Closed** 2015-11-11 22:17 UTC
