### ISSUE TITLE
pivot-hide column

### ISSUE THREAD

**Issue by andycow** [free-jqgrid/jqGrid#117] opened 2015-07-14 09:46 UTC
![2015-07-15_115503](https://cloud.githubusercontent.com/assets/13325992/8690533/6b7479ca-2ae8-11e5-9531-b089619fa247.png)
![2015-07-15_115532](https://cloud.githubusercontent.com/assets/13325992/8690534/6b7ddac4-2ae8-11e5-8a92-d54c29f8de59.png)

Hi Oleg:
When i hide one column in pivot(a$),
the row 2011 was missing(like the picture),
is it possible to fix it?
link:http://codepen.io/anon/pen/doKeLP
thanks!

**Comment by OlegKi** [comment] 2015-07-15 09:43
Hi! I am in vocation now. I will try to help you next week.

**Comment by andycow** [comment] 2015-07-16 03:22
OK! thank you a lot!

**Comment by OlegKi** [comment] 2015-07-19 22:17
@andycow: Thanks for reporting the problem. I'm back from vacation and posted [the commit](https://github.com/free-jqgrid/jqGrid/commit/6fd890f40dc1908effced52a986d44675dcf1c7d) which should fix it.

**Comment by andycow** [comment] 2015-07-20 07:10
@OlegKi :
thank about that!!!,
but now i have a new problem,
when i has a huge data in pivot(example: two yDimension,two xDimension) and hidden the column,it's need a lot of time to excute the hidden event(about 10S-15S),
is it other way to hidden column??
or how can i improve efficacy

**Comment by OlegKi** [comment] 2015-07-20 11:37
You are welcome! Sorry, but it seems to be a new question. It's important that other people could search and find the post. Thus it's important to separate different questions in separate issues.

About your last question. To analyse any question about performance it's really important to have the demo and the test case, which can be used to reproduce the problem. It's unclear for me which jqGrid options you use currently. Do you use local paging of data or not? Which web browser and in which version you made the performance tests? What exactly is slowly: creating of pivot grid or hiding some column? You wrote "it's need a lot of time to execute the hidden event". Do you mean that `hideCol` method is slow or which **event** you mean? How many rows and columns have the pivot grid which will be created from "3000 sets of data" (input pivot data? the output pivot data which will be used as input for jqGrid?)

**Comment by OlegKi** [comment] 2015-07-28 15:19
I didn't get any response from you on my last comment. In any way the problem which you reported is fixed now and you confirm it. So I'm closing the issue.

**Closed by OlegKi** 2015-07-28 15:19 UTC
Labels: bug, pivot
