### ISSUE TITLE
using jqgrid

### ISSUE THREAD

**Issue by kj1981** [free-jqgrid/jqGrid#407] opened 2017-12-15 15:04 UTC
Sorry to be asking some of the basic question here.

- I believe this version of jqgrid is free vs the gurrido grid. Could you let me know whihc version shall I download which is free
- I want to have functionality like having a custom template at the footer which has add rows, edit rows, delete rows. Like at http://www.guriddo.net/demo/bootstrap/
 Does the free grid provides all these?
 
 Sorry there are too many posts everywhere and are not clear.

**Comment by OlegKi** [comment] 2017-12-15 17:19
"Free jqGrid" is completely free of charge and it can be used under MIT or GPL licenses (like old version of jqGrid <=4.7). I recommend you [the page](https://free-jqgrid.github.io/getting-started/index.html) as the starting point. If you want to use Bootstrap CSS instead of jQuery UI CSS then you should follow [the section](https://free-jqgrid.github.io/getting-started/index.html#bootstrap). If you want to use Bootstrap 4 instead of Bootstrap 3, then you will need just replace `guiStyle: "bootstrap"` option to `guiStyle: "bootstrap4"`.

The recommended way of using free jqGrid is referencing the files `ui.jqgrid.min.css` and `jquery.jqgrid.min.js` directly from CDN. See [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs) for more details. If you do prefer to download the files, you can get it from [GitHub](https://github.com/free-jqgrid/jqGrid/releases) or to use [npm](https://www.npmjs.com/package/free-jqgrid), [NuGet](https://www.nuget.org/packages/free-jqGrid), [bower](https://bower.io/search/?q=free-jqgrid) or to get the package from [Maven Central](https://search.maven.org/#search%7Cga%7C1%7Cfree-jqgrid).

If I correctly understand your last question, you need use `navGrid` or/and `inlineNav` to create the navigator bar and to include add, edit, delete and other buttons to the navigator bar. The demo https://jsfiddle.net/OlegKi/hvwn1tf7/ (included in one from the old readmes) provides the functionality and many other advanced functionality, which could be helpful for you.

**Comment by kj1981** [comment] 2017-12-15 17:41
Great. Thanks for quick response. I will look into these.

**Comment by OlegKi** [comment] 2017-12-15 17:50
You are welcome! Please don't forget to close the issue after the problem is cleared/solved.

**Comment by kj1981** [comment] 2017-12-15 17:51
Used to info shared by Oleg to get started.

**Closed** 2017-12-15 17:51 UTC
