### ISSUE TITLE
virtual scrolling through large recordset causes grid override any width specified previously

### ISSUE THREAD

**Issue by bkwdesign** [free-jqgrid/jqGrid#246] opened 2016-06-27 17:16 UTC
See [this stackoverflow](http://stackoverflow.com/questions/38021570/jqgrids-sizing-behavior-changes-when-scrolling-through-a-large-set-of-records?noredirect=1#comment63486497_38021570) for a lengthy explanation

See [this jsFiddle](https://jsfiddle.net/bkwdesign/a6jpwecm/) for an immediate demonstration

**Comment by bkwdesign** [comment] 2016-06-27 17:27
FWIW - I've toyed a bit further with the jsFiddle. If I turn off the virtual scroll and allowing it to paginate the results.. when it renders the next page of results, a similar behavior can be witnessed. The grid resizes itself (wider) upon rendering the next page of results.

**Comment by OlegKi** [comment] 2016-07-15 10:38
You accepted [my answer](http://stackoverflow.com/a/38071941/315935) of your question on the stackoverflow. Is the problem solved now and one can close the issue?

**Comment by OlegKi** [comment] 2016-07-21 11:00
I didn't get any answer from you. I suppose that the problem is solved and I'm closing the issue. You can reopen it later or to post new issue.

**Closed by OlegKi** 2016-07-21 11:00 UTC
