### ISSUE TITLE
jQuery.ajax data converters not firing for subgrid

### ISSUE THREAD

**Issue by kaixiong** [free-jqgrid/jqGrid#218] opened 2016-03-30 06:24 UTC
Hi,

`jQuery.ajax` supports per-datatype converter functions (via the `converters` property) that process successfully received data before passing it on to the `success` callback. Among other things, I use this feature extensively to unwrap JSON data returned by ASP.NET webmethods.

However, as subgrid data is received and processed via the `complete` callback, the converters I install in my jQuery.ajax requests end up not firing.

From current master `HEAD`, `jqGrid/js/grid.subgrid.js` line 206-219:
```javascript
$.ajax($.extend({
  type: p.mtype,
  url: $.isFunction(p.subGridUrl) ? p.subGridUrl.call(ts, dp) : p.subGridUrl,
  dataType: p.subgridtype,
  //data: $.isFunction(p.serializeSubGridData)? p.serializeSubGridData.call(ts, dp) : dp,
  data: jgrid.serializeFeedback.call(ts, p.serializeSubGridData, "jqGridSerializeSubGridData", dp),
  complete: function (jqXHR) {
    if (p.subgridtype === "xml") {
      subGridXml(jqXHR.responseXML, sid);
    } else {
      subGridJson($.parseJSON(jqXHR.responseText), sid);
    }
  }
}, jgrid.ajaxOptions, p.ajaxSubgridOptions || {}));
```
The suggested fix is to hook onto the `success` event instead:
```javascript
  success: function (data) {
    if (p.subgridtype === "xml") {
      subGridXml(data, sid);
    } else {
      subGridJson(data, sid);
    }
  }
```
(`subGridXml` may need to be modified for this to work with XML data.)

**Comment by OlegKi** [comment] 2016-03-30 11:18
Could you post the demo (or URL to the demo), which reproduces the problem? You posted **no your code** (only the fragments of jqGrid code). I can suppose that you have problem in ASP.NET WebMethods and you fix the error in the WebMethod by usage converters property. How looks the prototype of the WebMethod for filling the grid and subgrid? Typical error: one use `string` as the type of return value instead of `object`. As the result the returned data will be converted to JSON **twice**. 

In any way I guess only about what you do on the server and on the client site and what problem exactly you have. You should post **more details** about what you do, in what format WebMethod  return the data and how WebMethods are declared.

**Comment by kaixiong** [comment] 2016-03-30 13:18
There is a complete description of the problem [here](https://encosia.com/a-breaking-change-between-versions-of-aspnet-ajax/).

ASP.NET Webmethods automatically serialises return .NET objects into JSON with no special configuration:

The webmethod
```C#
[WebMethod]
public static Object GetData()
{
    ...
    return new {
      prop1 = value1,
      prop2 = value2,
      ...
    };
}
```
When queried using `jQuery.ajax`, the method above produces the JSON string:
```javascript
{
  d: {
    prop1: value1,
    prop2: value2,
    ...
  }
}
```

Notice how the JSON-serialised .NET object has been encapsulated in the 'd' property.

I could not find a way to configure jqGrid's JSON readers to reach into the data encapsulated in `d`, so I applied a custom data converter to pull it out. It is simple, transparent and works with anything that processes returned data using the `success` callback. [This comment](https://encosia.com/never-worry-about-asp-net-ajaxs-d-again/#comment-43177) shows how it's done.

To your suggestion of a possible double parse, results of content type `application/json` and `text/javascript` are parsed once by jQuery itself using `jQuery.parseJSON` before they are passed on to the `success` callback. This is done via its default settings utilising the same converter mechanism. A custom converter applied to the same content types will override this completely. And since my suggested fix passes the parsed and extracted object into `subGridJson` in the `success` callback, no double parsing occurs.

(For results of type `application/xml` and `text/xml`, jQuery will invoke `jQuery.parseXML` by default.)

Do note that my use of a custom data converter /already works with the main grid data/. The technique also worked for subgrid data with Trirand's jqGrid before I switched over to free-jqGrid.

In any case, there does not seem to be a good reason to parse the raw string directly using a `complete` callback when jQuery already gives you the fully parsed object in the `success callback`. 

What's more, `complete` is called regardless of success or error. The current code does not appear to properly handle requests that end in errors.

**Comment by OlegKi** [comment] 2016-03-30 13:46
To get the data wrapped from `d` property one can use either dot-separated values in `jsonReader` or functions. Typical options in case of usage WebMethods are
```JavaScript
ajaxGridOptions: { contentType: "application/json"},
serializeGridData: function (postData) {
    return JSON.stringify(postData);
},
jsonReader: {
    root: "d.rows",
    page: "d.page",
    total: "d.total",
    records: "d.records"
}
```
I should mention that all problems which could be in case of usage WebMethod and jqGrid are old and well-known. The only problem: you didn't posted any JavaScript code, which you use and no *real* example of JSON data, which returns the server. I have no idea whether you use server side paging, sorting and filtering or you use `loadonce: true` option. I have no idea how many total rows in the dataset which you want to display in the grid. I have no idea whether you use TreeGrid, PivotTable, Data grouping and so on. You wrote only about Subgrids before, but it's not clear whether you load the subgrid data **together with the main data** or every expending of subgrid send separate Ajax request to the server. I have no idea whether you use legacy/simplified Subgrids or you use Grid as Subgrid. I can continue...

jqGrid have too many option and many ways of the usage. Before you posted any code I have to guess and think about a lot of possibilities which are possible to interpret your problem. Thus **please send always the JavaScript code which you use and an example of JSON response returned from the server (2-3 rows are enough typically)**.

**Comment by kaixiong** [comment] 2016-03-30 15:57
I'm off work at the moment but I will quickly answer your questions here:

1. Grid + subgrid with data sourced via a jsonReader that queries a ASP.NET webmethod.
2. No treegrid, data grouping or pivoting.
2. Server-side paging is used, so loadonce = false.
3. Subgrid data is loaded on-demand, when grid row is expanded by user.

Your suggestion of prefixing the property names with `d` did not work for me the first time I tried it. I will try again later to see if it works now.

I appreciate that you need some concrete code for clarification. But whatever the settings are, it boils down to line 206-219 of `jqGrid/js/grid.subgrid.js and the use of `complete` instead of `success`. The question is this: why does the code need to hook onto `complete` to parse the raw data itself instead of letting jQuery do the work?

A `success` callback works just as well without preventing custom converters from working. I may be among the few that use converters to pull out the `d` object, but there could just as well be other reasonable use cases you and I have never considered. 

What's more, as I mentioned earlier, the current `complete` callback code not check response statuses where jqGrid can end up trying to parse error responses and trying to load them as grid data.

**Comment by OlegKi** [comment] 2016-03-30 16:26
Sorry, but if `jsonReader: { root: "d.rows", page: "d.page", total: "d.total", records: "d.records" }` not helps you then your program probably do not what you describe.

The lines of `subgrid.js` which you referenced many times helps absolutely not if you don't post any JavaScript code and you don't post any test JSON data returned from the server. The JavaScript code have to correspond the data. The data returned from the server will be forwarded in the line 219 is **string**, which will be converted to **object** by call of `$.parseJSON`. It's correct behavior. I can understand your problem only with test data returned from the server and JavaScript code which you use.

To get JSON data returned from the server you can use [Fiddler](http://www.telerik.com/fiddler) or Developer Tools of IE/Chrome/Firefox (press F12 to start and choose Network tab). You should examine the body of the real server response for the data.

Thus 3 things are required to help you:
- JavaScript code which you use
- Test data returned from the server (for main grid and for the subgrid). You can replace the real data to dummy values to hold the confidentially. 2-3 rows of the data would be enough. Please send only real formatted data which you find in HTTP traces (using Fiddler or Developer Tools)
- You should write me approximately number of rows in the main grid and in the subgrid (100, 1000, 10000, 1000000 or some other)

If you have some demo accessible over internet then you can send me the corresponding URL. Please use non-minimized free jqGrid in the case (`jquery.jqgrid.src.js` instead of `jquery.jqgrid.min.js`).

**Comment by kaixiong** [comment] 2016-03-31 10:53
Hi Oleg,

Thank you for your patience. I will post it up next week when I have the free time to create a minimal example. The deployed code is complex, with multiple tabs and grids.

> The data returned from the server will be forwarded in the line 219 is string, which will be converted to object by call of $.parseJSON. It's correct behavior.

I am afraid you have completely missed the point I've been trying to make :(

I am _not_ saying the code is wrong. jQuery.ajax does indeed call `complete` with the XmlHttpRequest object. If you handle the `complete` event, `$.parseJSON(responseText)` is absolutely required.

What I am saying is this: there is a _better_ approach.  `jqGrid/js/grid.subgrid.js` can be updated to hook onto `success` **instead** of `complete`. The `success` callback will receive the JSON (or XML) object parsed by jQuery.

The key advantages of this are that it saves code for everyone:

- jQuery.ajax data converters work, so developers are free to add a callback to preprocess the 
returned data before it is passed on to jqGrid.
- jQuery parses the JSON/XML strings automatically.
- `success` will only fire if the data request was successful - no additional code is needed to check HTTP response statuses (think 40x errors). Contrast this with the `complete` event, which fires in regardless of what happens.

**Comment by OlegKi** [comment] 2016-03-31 12:13
Thank you! I think that I understand now better, what you mean.

The most problem with your suggestions is the compatibility with the previous versions. The feature, which you use currently is *legacy/simplified subgrid*, which require the usage of `subGridModel` and `subGridUrl` options **without** `subGridRowExpanded` callback. The legacy/simplified subgrid gives you very little possibilities to parse and to format the subgrid. Grid as Subgrid (`subGridRowExpanded` callback) gives much more flexibility. I thought before to remove the feature at all, but after some feedbacks from the other developers I decided to hold the feature. In case of usage Grid as Subgrid you would create **the standard grid** inside of the subgrid row. The standard grid uses `success` callback with additional callbacks like `beforeRequest`, `loadBeforeSend`, `loadError`, `beforeProcessing`, `loadComplete` and other callbacks which can be used for customization. The Ajax of the standard grid of free jqGrid have default implementation of `loadError` (see [the lines](https://github.com/free-jqgrid/jqGrid/blob/v4.13.1/js/grid.base.js#L2374-L2440) and [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.13.1/js/grid.base.js#L2530)). As the result, the user will see error messages in case of errors in Ajax.

In case of usage legacy/simplified subgrid one can use `ajaxSubgridOptions` for additional customization of `$.ajax` request. You can in general use any possibilities of jQuery.ajax and for example includes your own `success` and `error` callback or replace the standard `complete` implementation.

Now back to your suggestion. In general you are right and the usage of `success` and `error` is better as the usage of `complete`, but ... the compatibility. One have to be very careful in changing the legacy code. **Thus I'd prefer to have clear demo before making the modifications.** Just one example: the current code of legacy subgrid executes `subGridXml` and `subGridJson` inside of `complete` and thus *it will be executed in case of errors too*. **The user will see empty subgrid in case of error on `$.ajax` used to lead the subgrid**. You suggest to replace `complete` to `success`, which is good in general, but one will have **no empty subgrid** in case of error in `$.ajax` request. Thus your suggestion have side effects. One could easy fix the problem by adding `error` callback where one calls  `subGridXml` or `subGridJson` with `null` as the first parameter. I included the example only because I want to stress, that it's better to be very carefully in fixes trying to hold the compatibility to the previous versions.

I see much more other problems in legacy/simplified subgrid. For example, it would be required to add `context` parameter to the Ajax request with `sid` used in `complete` callback. The current code works incorrectly in case of slow responses from the server. If the user click on the second subgrid icons (from another row) before we get the response from the first request, then the value of `sid` variable will be changed and the `complete` callback. The `complete` callback will process the first response using the wrong (new) `sid` and to insert the subgrid data to the wrong row. I will post the fix today after some testing.

I will try to make the modifications based on you suggestions and will post you new message later...

In any way thank you for your suggestions and for the discussion!

**Comment by OlegKi** [comment] 2016-03-31 20:42
I committed [the changes](https://github.com/free-jqgrid/jqGrid/commit/6911798009025ef194d815705084d185106d7b9e) to GitHub. Please try the new code. I hope that the problem, which you reported is solved now.

Thank you once more for reporting the problem.

**Comment by kaixiong** [comment] 2016-04-02 01:57
Thanks! I will try your fix as soon as I can.

Sorry that I hadn't been as clear on the get-go. My suggestion for the fix was superficial I admit, but it was only intended point to a possible improvement.

It's really interesting to hear your thoughts on the current implementation. In general, I feel that the jqGrid API may be more complicated than it needs to be - there often appears to be multiple ways of doing similar things, and the differences are not immediately clear to me. Until today, I didn't even know that I've been using the subgrid feature I am using is considered legacy/simplified. But that's another issue altogether :)

**Comment by OlegKi** [comment] 2016-04-02 08:55
You are welcome! Please verify that the original problem, with non-applying of converters,  is solved in the latest code of free jqGrid and close the issue.

**Comment by OlegKi** [comment] 2016-04-05 16:06
I get no feedback from you since some days. Thus I closing the issue. You can reopen it at any time if it would be required. Please confirm that the reported problem is solved (my tests stows it).

**Closed by OlegKi** 2016-04-05 16:06 UTC

**Comment by kaixiong** [comment] 2016-04-06 04:40
I have only just managed to test it today and I am happy to confirm that it works :)
