### ISSUE TITLE
Inline edit, default value

### ISSUE THREAD

**Issue by aboldel** [free-jqgrid/jqGrid#394] opened 2017-11-08 17:53 UTC
Hi Oleg,

I'm trying to customize the inline editing,
My issue is that on one of my columns in edit mode is a dropdownlist with a string using the  format xxxx:xxxx for its options, but from the server when I first load the grid I only receive a string xxxx, and when the cell in edit is a dropdown list there is a mismatch between the value I have and the list of options.

What I'd like to do is to work on the editoptions and use something like the defaultValue to edit the value in the cell to the format I require so that when the dropdown list is initialized I have a match.

Is there an option or an event that I can use to edit the value of the cell before the inline edit starts populating the dropdownlist?

Thank you.

**Comment by OlegKi** [comment] 2017-11-08 18:43
It would be good if you post more details about your implementation. Which `datatype` has the grid? How you fill the data in jqGrid? How you define the column which use the dropdownlist? If you use remote `datatype` ("json", "xml", ...) then you can use `beforeProcessing` callback to **normalize** the data returned from the server. It could be the simplest solution of your problem. I can continue to guess what you do and to describe a possible solution of the problem, but it would be more productive if you send more details of your implementation. The best way to solve the most problems is preparing small demo (in jsfiddle for example), which reproduces the problem.

**Comment by OlegKi** [comment] 2017-11-08 18:43
It would be good if you post more details about your implementation. Which `datatype` has the grid? How you fill the data in jqGrid? How you define the column which use the dropdownlist? If you use remote `datatype` ("json", "xml", ...) then you can use `beforeProcessing` callback to **normalize** the data returned from the server. It could be the simplest solution of your problem. I can continue to guess what you do and to describe a possible solution of the problem, but it would be more productive if you send more details of your implementation. The best way to solve the most problems is preparing small demo (in jsfiddle for example), which reproduces the problem.

**Comment by OlegKi** [comment] 2017-11-08 18:44
It would be good if you post more details about your implementation. Which `datatype` has the grid? How you fill the data in jqGrid? How you define the column which use the dropdownlist? If you use remote `datatype` ("json", "xml", ...) then you can use `beforeProcessing` callback to **normalize** the data returned from the server. It could be the simplest solution of your problem. I can continue to guess what you do and to describe a possible solution of the problem, but it would be more productive if you send more details of your implementation. The best way to solve the most problems is preparing small demo (in jsfiddle for example), which reproduces the problem.

**Comment by aboldel** [comment] 2017-11-09 12:32
Thanks for the help,
I'm using datatype json and this is my column colmodel
```
edittype: "select",
                                editoptions: {
                                    value: project_codeList,
                                    dataInit: function (element) {
                                        $(element).width(200).select2({form
                                            dropdownCssClass: "ui-widget ui-jqdialog"
                                        });
                                    }
                                },
```

project_codeList is in the xxxx:xxxx format, but the value I receive from the json is just a xxxx,
the same as it gets set when I click on the dropdown.
I thought the select2 would read from its options and find the value but it's not working.
Right now I'm trying to set the value of the select2 on the onedit event, as I think the beforeProcessing is too soon, since I get the data I need, but I just can't make them read from the dropdown.
I'll update as soon as I have some results.

Thank you again

**Comment by OlegKi** [comment] 2017-11-09 12:55
Could you prepare **the demo**, which demonstrates what you do? You can get https://jsfiddle.net/OlegKi/yvbt6w54/ from README of free jqGrid 4.14.1 and modify it.

You use in the second post the same `xxxx:xxxx` and `xxxx` format or `project_codeList`, which gives not enough information. `editoptions.value` can be used in *multiple* formats. Moreover, you can combine `edittype: "select"` with `formatter: "select"`. You should describe all more detailed or to provide the demo, which demonstrates what you currently do.

The statement "*I think the beforeProcessing is too soon*" from your last comment sounds very strange because you don't clear *how* you get information about the values/texts used in the dropdown (`editoptions.value`) and how you fill the grid with data. The statement "*project_codeList is in the xxxx:xxxx format, but the value I receive from the json is just a xxxx*" is unclear too because you don't describe what is `project_codeList`.

**Comment by OlegKi** [comment] 2017-11-20 15:19
Please provide the demo, which demonstrates the problem or close the issue.

**Closed** 2017-11-21 18:03 UTC
Labels: question
