### ISSUE TITLE
Unable to choose columns with column chooser

### ISSUE THREAD

**Issue by arrinmurr** [free-jqgrid/jqGrid#363] opened 2017-08-17 16:24 UTC
The column chooser functionality has stopped working starting with the version 4.13.5, at least in the way I have been using it. Trying to press "Ok" in the column chooser dialog results in a JavaScript error.  It could be that the way I have been using it is unsupported.

Examples:
* master: https://jsfiddle.net/64ajs7jk/   (Currently does not work)
* 4.13.5: https://jsfiddle.net/64ajs7jk/1/ (First nonworking version)
* 4.13.4  https://jsfiddle.net/64ajs7jk/2/ (Last working version)

Steps to reproduce:
1. Click on the "Choose columns" button.
1. Press the "Ok" button in the dialog.

When pressing the "Ok" button, the column chooser dialog stays in place and an error message along these lines can be seen in the browser console:
* "TypeError: n is undefined" (Firefox)
* "Cannot read property 'newColOrder' of undefined" (Chrome)

**Comment by OlegKi** [comment] 2017-08-18 23:05
Thank you for the issue with the demos. The demos don't includes `ui.multiselect.js` and `ui.multiselect.css`, which **required** for `columnChooser` and which can be found in `plugins` folder of every release. https://jsfiddle.net/OlegKi/64ajs7jk/3/ provides the fixed version. It used `https://cdnjs.cloudflare.com/ajax/libs/free-jqgrid/4.14.1/plugins/css/ui.multiselect.css` and `https://cdnjs.cloudflare.com/ajax/libs/free-jqgrid/4.14.1/plugins/min/ui.multiselect.js` only and the same code like in your original demos. You can see that the dialog of `columnChooser` looks now like it should be (see pictures in the [old documentation](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:jquery_ui_methods#column_chooser)). The main functionality works now too.

**Comment by arrinmurr** [comment] 2017-08-19 06:31
I was under the impression that the multiselect plugin was optional, and it just made the column chooser prettier. I have been using the column chooser without the multiselect plugin at least since jqGrid 4.6.0, and it has worked without issues. You just had to ctrl-click to select the columns.

However, even the old documentation you linked to states that the multiselect plugin is required, so I'm not sure where I got the idea that the column chooser could be used without it. Maybe it has just been a coincidence that it has worked, and I have been using it wrong all this time.

**Comment by OlegKi** [comment] 2017-08-20 17:39
@arrinmurr I understand what you mean. Nevertheless, please close the issue is the problem is cleared now.

**Comment by arrinmurr** [comment] 2017-08-20 18:09
Fair enough. Thanks!

**Closed** 2017-08-20 18:25 UTC
