### ISSUE TITLE
PivotGrid - useColSpanStyle true

### ISSUE THREAD

**Issue by mrjumpy** [free-jqgrid/jqGrid#69] opened 2015-05-27 07:33 UTC
When I'm apply useColSpanStyle: true with more aggregates.
The result:
http://codepen.io/mrjumpy/pen/RPRXjM?editors=101

It's not a simple problem, maybe we can fix it after 4.9 beta1.

**Comment by OlegKi** [comment] 2015-05-27 08:05
After writing you the previous post I do started debugging `setGroupHeaders` and it seems I do found one simple fix which produce pretty good results for your demo and even for more complex case like [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/pivotGrouping_useColSpanStyle.htm). So I [committed the fix](https://github.com/free-jqgrid/jqGrid/commit/a94ae4b98df502e3b0196f4580896ae1af1ae6f8) to the code of 4.9 beta1. Please test it and report any bugs it you find there.

**Comment by mrjumpy** [comment] 2015-06-04 03:44
Hi Oleg.
There is a bugs.
Please drag & drop the column's line between categoryName  and Price.
Then, you'll find the bug.
http://codepen.io/mrjumpy/pen/rVyVQL?editors=001

When `useColSpanStyle : true`, it's not gonna happen.

**Comment by OlegKi** [comment] 2015-06-04 07:59
Thanks for the bug report! The reason was [the last changes](https://github.com/free-jqgrid/jqGrid/commit/9f2525d5b1e91ff661ac6f4ddd26a6c151c1804a) which I made yesterday. I didn't tested there good enough. The problem is fixed now (see [the next commit](https://github.com/free-jqgrid/jqGrid/commit/f1ddc9477068cf567912f8f1cea1ec23a83e75d5)).

**Closed** 2015-06-08 02:13 UTC
Labels: enhancement, UI
