### ISSUE TITLE
reloadGrid after sortableRows enabled break sort feature

### ISSUE THREAD

**Issue by michelepra** [free-jqgrid/jqGrid#237] opened 2016-05-26 12:35 UTC
1. jqgrid initialized with default value of parameter `quickEmpty` 
2. enable sorting feature
3. call reloadGrid
4. sorting feature is break

`var grid = $("#myprevinitalizedgrid");`
`var optionSort = {};//options of jquery ui sortable`
`grid.jqGrid('sortableRows', optionSort);`
`grid.trigger("reloadGrid")`

i proposed to fix it by adding condition where quickEmpty param was used

> 	[...]
        } else if (p.quickEmpty) {
               if (p.quickEmpty === "quickest" && !$(table.tBodies[0]).data("ui-sortable")) {
              [...]

**Comment by OlegKi** [comment] 2016-05-27 09:13
Thank you for the bug report, but I suppose that you used some old version of free jqGrid. It was the bug in versions between 4.10.0 and 4.13.2, but the bug i already fixed in the version 4.13.3. See [the issue](https://github.com/free-jqgrid/jqGrid#below-one-can-see-the-full-list-of-changes-in-the-version-4133-compared-with-4132) and [the commit](https://github.com/free-jqgrid/jqGrid/commit/5834625cf40198a979833552c96ad1dbd529bd95), which fixed the bug.

In any way I can't reproduce any error with `sortableRows` in the current free jqGrid 4.13.3. I'm closing the issue. Please confirm that the problem, which you reported, is already fixed in free jqGrid 4.13.3. You can reopen the issue at any time later if it would be required.

**Closed by OlegKi** 2016-05-27 09:13 UTC

**Comment by michelepra** [comment] 2016-05-27 10:12
i test 4.13.3 but the code [here](https://github.com/free-jqgrid/jqGrid/commit/5834625cf40198a979833552c96ad1dbd529bd95) break application logic that generate a porting issue.
If i need some method of jquery ui sortable plugin, before i must call .sortable on `<tbody>` element, now with the code of #223 i must call .sortable on `<table>` element
The code that i proposed resolve #223 and application code doesn't need to be ported

**Comment by OlegKi** [comment] 2016-05-27 10:58
Could you describe the problem, which you report more detailed. You wrote about that the the code of free jqGrid 4.13.3 "breaks application logic". Could you described **detailed** what you mean. Which "porting issue" you mean?

The **current code** of free jqGrid calls `.sortable` on `<table>`, because only the `<table>` element be hold unchanged over all changes which could be made in the live cycle of jqGrid. The method `sortableRows` uses now `items: ">tbody>.jqgrow"` option of `.sortable` instead of `items: ">.jqgrow"` used before. Where you see any problem in such way of the usage?

[The changes](https://github.com/free-jqgrid/jqGrid/pull/238/commits/bb739e1b0cfa292adbb0046775b796dc7e94a6c8), which you suggested in [the pull request](https://github.com/free-jqgrid/jqGrid/pull/238), can't be applied to **the  current code of free jqGrid**, because there will not work in free jqGrid 4.13.3.

If you don't like the default `quickEmpty: "quickest"` behavior, then you can use `quickEmpty: true` option or `quickEmpty: false`. Both from the settings will don't destroy `<tbody>` of the main `<table>` element of jqGrid.

If you want that I revert [the fix](https://github.com/free-jqgrid/jqGrid/commit/5834625cf40198a979833552c96ad1dbd529bd95) implemented in free jqGrid 4.13.3 and apply your changes instead then you should provide **really clear understandable arguments** why the existing code of free jqGrid is wrong. You should provide the demo which uses the latest code of free jqGrid from GitHub and to describe the test case, which can be used to reproduce some issue. It should be *not an issue in your code*, which uses jqGrid, but the common issue in the code of free jqGrid.
