### ISSUE TITLE
jqGrid inline edit mode selecting 'select' element's last element always by text value

### ISSUE THREAD

**Issue by aulea** [free-jqgrid/jqGrid#241] opened 2016-06-07 12:38 UTC
When using inline editing, where column is defined as 'select' in edit mode and values are given by string/object, then wrong element is selected (always last one).
```javascript
colModel: [
     {name: 'code', jsonmap: 'name', editable: true, edittype: 'select',
      editoptionas: {value: "FE:FedEx; IN:InTime; TN:TNT"}
     }
]
```
Now, when my column viewable value is "InTime", then its not selected when going to edit mode.

https://github.com/free-jqgrid/jqGrid/blob/master/js/grid.common.js#L547
On line 547 and previous for cycle. All option elements are created in previous cycle and under variable 'ov' is last one, which is then selected, when there is match by text.

**Comment by OlegKi** [comment] 2016-06-08 09:14
Thank you for the post. I understand your problem, but the origin of the problem: wrong usage of `editoptionas.value`.

The problem is the following. It seems that you fill the grid with **texts** as the data (`"FedEx"`, `"InTime"`, `"TNT"`). The `editoptionas.value` are common for all editing mode and for local or remote editing. The value `editoptionas: {value: "FE:FedEx; IN:InTime; TN:TNT"}` means that the values `"FE"`, `"IN"` or `"TN"` have to be saved in the column (not a value `"FedEx"`, `"InTime"` or `"TNT"`). Thus you *have to* fill the data with the values `"FE"`, `"IN"` or `"TN"` and to **you have to use `formatter: "select"`** (see [the old documentation](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:predefined_formatter#formatter_type_select)) to display the values `"FE"`, `"IN"` or `"TN"` as the strings `"FedEx"`, `"InTime"` or `"TNT"`. After making the changes everything will be correctly displayed and the selection during editing will work too.

Alternatively you can use `editoptionas: {value: "FedEx:FedEx;InTime:InTime;TNT:TNT"}` *without adding `formatter: "select"`*. As the result jqGrid will "knows" only the texts `"FedEx"`, `"InTime"` or `"TNT"` instead of ids `"FE"`, `"IN"` or `"TN"`, which you probably use in the database. The texts (`"FedEx"`, `"InTime"` or `"TNT"`) contains *unique* values. Thus one can find the corresponding id value (`"FE"`, `"IN"` or `"TN"`) on the backend side. Thus the approach with `editoptionas: {value: "FedEx:FedEx;InTime:InTime;TNT:TNT"}` will work.

The usage of `edittype: 'select', editoptionas: {value: "FE:FedEx; IN:InTime; TN:TNT"}` *without* `formatter: "select"` is inconsistent.

Nevertheless **the existing code of jqGrid contains already** the part, which allows to set editing value based on the text of the select option if the value is not found. The changes from [your pull request](https://github.com/aulea/jqGrid/commit/820911e263de2d9164f56accf9cac80a10d6fc97) do this *better* as the original code. I thank you for the suggestions and I will apply (merge) the pull request.

**Comment by OlegKi** [comment] 2016-06-08 09:36
I merged your pull request. Thus I'm closing the issue now. You can reopen the issue at the any time later.

Please confirm that the latest code from GitHub is working correctly now. Thanks you again your your suggestions.

**Closed by OlegKi** 2016-06-08 09:36 UTC
Labels: bug

**Comment by aulea** [comment] 2016-06-08 13:07
Latest code is working correctly and thank you to point out that there is already existing formatter: "select". Which is of course preferred solution to compare select values instead of texts. Will use it.
