### ISSUE TITLE
'currency' formatter strips text from beginning of filter criteria

### ISSUE THREAD

**Issue by bellclassic** [free-jqgrid/jqGrid#362] opened 2017-08-14 21:30 UTC
I have a column that uses the currency formatter and includes the '$' symbol as a prefix.  My users tend to search on this column without including the '$' symbol, however the jquery.jqgrid.*.js code trims the prefix length from the search criteria, resulting in an incorrect search (missing the first character).  Suggested change to jqGrid would be to include a v.startsWith()/v.endsWith() check to determine if the prefix/suffix has been included before trimming it off.

Suggested modification made on version 4.14.1 starting at line 9795:

```javascript
case "currency":
	var prefix = getFormaterOption("prefix"),
		suffix = getFormaterOption("suffix");
	if (prefix && prefix.length && v.startsWith(String(prefix))) {
		v = v.substr(prefix.length);
	}
    if (suffix && suffix.length && v.startsWith(String(suffix))) {
		v = v.substr(0, v.length - suffix.length);
	}
	v = cutThousandsSeparator(v)
			.replace(getFormaterOption("decimalSeparator"), ".");
	if (v !== "") {
		// normalize the strings like "010.00" to "10"
		// and "010.12" to "10.12"
		v = String(parseFloat(v));
	}
	break;
```

**Comment by OlegKi** [comment] 2017-08-20 17:14
Thank you very much for the post! I just changes a litte your code, because `startsWith` isn't supported in old web browsers. Additionally the expression with `v.startsWith(String(suffix)` seems to be `v.endWith(String(suffix)`. In any way your suggestion is correct and [the commit](https://github.com/free-jqgrid/jqGrid/commit/21a72371bded56cb42aca3f3f8fad068c0872780) should implement it.

Please test the latest code from GitHub and confirm that it solves the problem, which you reports. Don't forget to close the issue if the problem is fixed now.

**Comment by OlegKi** [comment] 2017-08-31 18:00
@bellclassic I didn't get any response from you since a long time. I'm closing the issue. You can reopen the issue or post new issue with an additional information about the same problem.

**Closed by OlegKi** 2017-08-31 18:00 UTC
