### ISSUE TITLE
Scrollbars shown only in Chrome

### ISSUE THREAD

**Issue by antony84** [free-jqgrid/jqGrid#384] opened 2017-10-03 09:11 UTC
Hi,
i have a simple jqgrid with height:'auto' and width:'770', loading remote data.

In Chrome i get scrollbars, while in Firefox and IE no one scrollbar is shown. Why? How i can avoid chrome shows scrollbars?

**Comment by OlegKi** [comment] 2017-10-03 19:12
Sorry, but you have to post the demo, which can be used to reproduce the problem, which you report. You can get some simple demo like https://jsfiddle.net/OlegKi/v8x94gbm/ and modify it so that one can see the problem. If the problem exists only in case of loading the data from the server then you can use Echo service of JSFiddle. See https://jsfiddle.net/OlegKi/v8x94gbm/1/

**Comment by OlegKi** [comment] 2017-10-14 12:55
@antony84 I asked you 11 days ago to provide more detailed information about the problem, which you report. Please post it or close the issue.

**Comment by OlegKi** [comment] 2017-10-22 14:46
I didn't get any response from use since a long time. I'm closing the issue now. You can post additional information about your problem and *reopen* the issue.

**Closed by OlegKi** 2017-10-22 14:46 UTC
