### ISSUE TITLE
Pivot table ajax options

### ISSUE THREAD

**Issue by eppsaksh** [free-jqgrid/jqGrid#134] opened 2015-08-26 13:35 UTC
Hi Team,

I am planning to use JQGrid pivot table in my project. Existing details/issues/enhancement posts are  very helpful. I wanted to know where we can we use ajaxoptions in pivot table & what are other options. (I know only reader : "cell").

Thanks in advance.

**Comment by OlegKi** [comment] 2015-08-26 14:12
Hi eppsaksh,

you can just examine the source code of [jqPivot](https://github.com/free-jqgrid/jqGrid/blob/v4.9.2/js/grid.pivot.js#L730) which have the following 4 parameters
```JavaScript
jqPivot: function (data, pivotOpt, gridOpt, ajaxOpt) {...}
```
The main code is very simple. You can see it [here](https://github.com/free-jqgrid/jqGrid/blob/v4.9.2/js/grid.pivot.js#L786-L796). You should just use the URL as the value of the first `data` parameter. The last parameter (`ajaxOpt`) allows you to specify any other options of `jQuery.ajax` request used for loading of data from the server. I recommend you to read [the answer](http://stackoverflow.com/a/30795988/315935) too. If you don't get the required information then you should formulate more detailed which interface you have with the server and what you need to implement.

Best regards
Oleg

**Comment by eppsaksh** [comment] 2015-08-27 10:18
Hi Oleg,

Thanks a lot for details.
I am working on pivot grid, I will try to integrate all mentioned point in my code.

Regards,
EppsAksh

**Comment by OlegKi** [comment] 2015-09-09 05:36
Is the problem is solved now? Please close the issue or describe the currently opened problems.

**Closed** 2015-09-09 06:16 UTC
Labels: question
