### ISSUE TITLE
Broken search buttons when colNames contains HTML

### ISSUE THREAD

**Issue by Wooya** [free-jqgrid/jqGrid#240] opened 2016-06-03 08:42 UTC
I have defined colNames with additional span elements to display extra information in tooltip:
```
colNames: [
			"<span title='" + getLocale('SG_WNIOSKODAWCA').title + "'>" + getLocale('SG_WNIOSKODAWCA').text + "</span>",
			"<span title='" + getLocale('SG_PRZEWOZNIK').title + "'>" + getLocale('SG_PRZEWOZNIK').text + "</span>",
			"<span title='" + getLocale('SG_NR_WNIOSKU').title + "'>" + getLocale('SG_NR_WNIOSKU').text + "</span>",
			"<span title='" + getLocale('SG_DATA_WNIOSKU').title + "'>" + getLocale('SG_DATA_WNIOSKU').text + "</span>",
			"<span title='" + getLocale('SG_WPROWADZIL').title + "'>" + getLocale('SG_WPROWADZIL').text + "</span>"
...
]
```

When search options buttons are enabled then they are broken:
![image](https://cloud.githubusercontent.com/assets/541588/15773421/0e7199c2-2977-11e6-8e6c-1ace09c8b70f.png)

I suggest to change line 9408 in jqGrid to:
```
var csv = (getRes("search.resetTitle") || "Clear Search Value") + " " + p.colNames[ci].replace(/(<([^>]+)>)/ig, '');
```

That modification will strip html tags from colNames.

**Comment by OlegKi** [comment] 2016-06-03 09:09
Thank you for the bug report!

The bug come from [the post 4.13.3 changes](https://github.com/free-jqgrid/jqGrid/commit/88d6fbaabb8d8231ebd7a05232950c697ffdfcf8). I tried to improve the visibility of the tooltips and WAI-ARIA textes, but I forgot about the case when `colNames` contains HTML fragments.

The current code uses `encodeAttr` function (see [here](https://github.com/free-jqgrid/jqGrid/blob/v4.13.3/js/grid.base.js#L3108-L3110) and [here](https://github.com/free-jqgrid/jqGrid/blob/v4.13.3/js/grid.base.js#L3150-L3152)) for encoding data placed as `title` or any other HTML attribute. In general one could use the same function to escape `csv` value. Could you verify that the usage of `encodeAttr` function fixes the corruption of the generated data?

On the other side it would be probably better to introduce one more callback function, which would be able to overwrite the value, which will be built. The default value could be `encodeAttr(csv)`, but if the callback is defined (for example `resetTitle` callback with `options` parameter contains `iCol`, `cm` and so on) then the callback will build the title. What you think about that?

**Comment by OlegKi** [comment] 2016-06-08 08:02
Sorry for delay: I was busy with other projects.

I posted [the changes](https://github.com/free-jqgrid/jqGrid/commit/fee31848adf61ba47d3d1ad17a8b739cd6021da8) to GitHub. I uses `$.jgrid.stripHtml` now and the new code allows to specify `resetTitle` callback for additional customization.

**Comment by Wooya** [comment] 2016-06-08 21:52
Thank you :+1:

**Comment by OlegKi** [comment] 2016-06-09 05:19
You are welcome! You can close the issue is the problem is solved now.

**Closed** 2016-06-13 10:08 UTC
Labels: bug
