### ISSUE TITLE
SetCell error and afterInsertRow

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#60] opened 2015-05-15 20:35 UTC
1. I have the following code
$(this).jqGrid('setCell',rowid,'sumadeductibil','',{'background-color':'#EFEDED'});
and receive the following error  "$td is undefined"

line 5904 = $td[typeof cssp === "string" ? "addClass" : "css"](cssp);

2.  afterInsertRow : function (rowid,rowdata) 
     Value of rowdata.colname is the same all the time, but incorrectly.

**Comment by OlegKi** [comment] 2015-05-15 21:40
Thank you for the bug report! I made many code optimizations which improves the performance, but I made some small errors. I fixed the code now (see [the commit](https://github.com/free-jqgrid/jqGrid/commit/94915f3cfd292be8fcbe67f75a96b61cb2856d81)). Please retry the code and confirm that the both bugs are fixed.

**Comment by davgino** [comment] 2015-05-16 06:28
Now is ok.

**Comment by OlegKi** [comment] 2015-05-16 07:53
Please close the issue if the problem is fixed. I can of cause to close it myself, but I prefer that the person who reported the problem decide himself whether the problem is solved now or not yet.

**Closed** 2015-05-16 10:21 UTC
Labels: bug
