### ISSUE TITLE
Is ondblClickRow to edit still supported?

### ISSUE THREAD

**Issue by chenster** [free-jqgrid/jqGrid#164] opened 2015-10-27 15:00 UTC
I used to be able to double click a row to edit. It seems that it's no longer in the free version. I used to be able to edit a row using the following:

```javascript
ondblClickRow: function(){
var row_id = $(this).getGridParam("selrow");
$(this).jqGrid("editGridRow", row_id, {           // --------- edit options ---------
afterShowForm:function(form_id){
}, // afterShowForm 
onInitializeForm:function(form_id){},
afterSubmit:function(d,a){return true;},
jqModal:true,
                         checkOnUpdate:false,
                         savekey: [true,13],
                         width:450,
                                    height:"100%",
                                    navkeys: [false,38,40],
                                    checkOnSubmit : false,
                                    reloadAfterSubmit:false,
                                    resize:true,
                                    closeOnEscape:true,
                                    closeAfterEdit:true,bottominfo:"* required",
                                    viewPagerButtons:true,
beforeShowForm: function(frm) { }
			}); // editGridRow
        }, // ondblClickRow
```

**Comment by OlegKi** [comment] 2015-10-27 17:20
One can of cause call `editGridRow` inside of `ondblClickRow`, but your code have some problems. The first parameter of `ondblClickRow` is the rowid of the clicked row, but you don't use the parameter and get the rowid of the last selected row. Free jqGrid allows to **deselect** previously selected row starting with the version 4.8. One can fix your code by usage the following code:
```JavaScript
ondblClickRow: function (rowid) {
    $(this).jqGrid("editGridRow", rowid, {
        closeOnEscape: true,
        closeAfterEdit: true,
        ... // other parameters and callbacks
        savekey: [true, 13]
    });
}
```
See [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/formEditOnDoubleClick0.htm).

One can go back to the old behavior, where one can only select new row, but can't deselect previously selected row. One need just add `singleSelectClickMode: "selectonly"` option to the grid.

One additional problem can one see in the demo above. If one uses the options of `editGridRow` in **one explicit call of `editGridRow` then the options will be used only in the case**. If could be a problem if the grid provides multiple ways to start editing like `formatter: "actions"` and `navGrid` in the demo. You can easy test that `closeAfterEdit: true` option works only if editing was started by double-click.

I recommend you to read [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/New-style-of-usage-options-of-internal-methods) which describes new way to specify options of form editing which will be applied as default for all direct and indirect calls of `editGridRow`. You need just place the options of `editGridRow` inside of parameter ``

See [the next demo](http://www.ok-soft-gmbh.com/jqGrid/OK/formEditOnDoubleClick.htm) which uses the option `formEditing`. I added `singleSelectClickMode: "selectonly"` option too, but it isn't really required.

Please test both demos and close the issue if your problem will be solved.

**Comment by chenster** [comment] 2015-10-28 12:41
Thank you, Oleg, I will check it out and let you know if I discover anything interesting.

**Comment by OlegKi** [comment] 2015-10-31 09:58
Small remark. Please don't write "Update" part to your old comments. Such posts don't produces any notifications and only new readers of the issue will see the modified text. I read the modifications today only accidentally, because I looked through your old posts before writing the answer on your another new issue.

About the current issue: is the problem is solved? Please close the issues which are solved or write new post with the description of still opened problems. You question was about the usage of `editGridRow` directly inside of `ondblClickRow`. Do you fixed your code now? Is it works `with free jqGrid?

**Closed** 2015-11-01 11:06 UTC
Labels: question
