### ISSUE TITLE
FormEdit in grid . 

### ISSUE THREAD

**Issue by asifali0869** [free-jqgrid/jqGrid#294] opened 2017-02-14 18:44 UTC
Hi,

After save call return for formedit , it prompts null refrence on line 
a(":input:visible", y)[0].focus()
file : **grid.formedit.js**
applying check if (a(":input:visible", y)[0]) , works for me . But please review .
Thanks
Asif

**Comment by OlegKi** [comment] 2017-02-14 22:26
Please describe the problem clear enough. What version of free jqGrid you use? You should never use minimized version of jgGrid (`jquery.jqgrid.min.js`) if you report a problem. You should repeat the same test with `jquery.jqgrid.src.js` and post only the code fragments from non-minimized free jqGrid.
It seems that you loads separate **module** `grid.formedit.js` instead of usage  `jquery.jqgrid.src.js`. Do you used RequireJs to load all the dependent modules or you includes manually some modules in some order?

In any way, you should prepare the issue so, that other, like me, be able **to reproduce** your problem. Thus the information should be really full. You can provide, for example, the demo, which uses non-minimized free jqGrid and to describe exact test case (step by step instructions to reproduce the problem). It's good to include the information, which web browser in which version you used in your tests.

**Comment by OlegKi** [comment] 2017-02-15 18:50
@asifali0869 I think that, I understand now, which problem you mean. It should be [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.13.6/js/grid.formedit.js#L981) and [another one](https://github.com/free-jqgrid/jqGrid/blob/v4.13.6/js/grid.formedit.js#L1230). The problem is "inherited" from old jqGrid 4.7: see [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.7.0/js/grid.formedit.js#L831) and [another one](https://github.com/free-jqgrid/jqGrid/blob/v4.7.0/js/grid.formedit.js#L1069) .

Thanks for reporting the problem. I'll fix the bugs.

**Comment by asifali0869** [comment] 2017-02-15 18:57
Exactly . 
You made a complete task for me in your first reply but now you made it easy.
Thanks.

**Comment by OlegKi** [comment] 2017-02-15 19:07
I committed the changes not to GitHub. Please update your copy of sources. If the problem is solved then I'm closing the issue. If you'll do find that the fix in not work you can reopen the issue at any time later or to post new issue of cause. Thanks again for reporting the bug.

**Closed by OlegKi** 2017-02-15 19:07 UTC
Labels: bug
