### ISSUE TITLE
jquery-3.2.1 error?  Cannot read property 'msie' of undefined

### ISSUE THREAD

**Issue by tcaduto** [free-jqgrid/jqGrid#405] opened 2017-12-12 19:10 UTC
I installed latest jquery and latest jqgrid free and get this error:
jquery-3.2.1.min.js:2 jQuery.Deferred exception: Cannot read property 'msie' of undefined TypeError: Cannot read property 'msie' of undefined

Does jqgrid free not support jquery 3.2.1?

**Comment by OlegKi** [comment] 2017-12-12 21:40
Free jqGrid supports of cause jQuery 3.2.1 (see https://jsfiddle.net/OlegKi/hvwn1tf7/ for example). If you have any problem with the usage of free jqGrid, you should provide **the demo**, which reproduces the problem.

**Comment by OlegKi** [comment] 2017-12-17 11:55
Please post **the demo**, which can be used to reproduce the problem, which you reported, or close the issue.

**Closed** 2018-01-03 23:31 UTC

**Comment by iamhammer** [comment] 2018-07-23 21:03
I'm working my way through this issue myself. I'm not yet where I can post my code, but for travelers from the future I can tell you that the 'msie' has to do with jqGrid trying to browser sniff (msie=Microsoft Internet Explorer) and I believe it is related to [this post](http://www.trirand.com/blog/?page_id=393/releases/jqgrid-4-4-3#p28128) on the old jqGrid forums regarding jQuery's use of the $.browser property.

**Comment by OlegKi** [comment] 2018-07-24 11:20
@iamhammer I reread you comment many time, but I can't understand it. What problem you have? What problem you want to report?

The original post was absolutely insufficient for any kind of analyse. Its absolutely unclear which version of "free jqGrid" (or any other fork of jqGrid) was used and it's unclear whether the problem has any relation to jqGrid at all. The name `msie` is very common. It could be a property of some jqGrid object (like `$.jgrid.msie` which is **always** initialized), it could be `$.browser.msie` (which is not used in jqGrid since a long time and which don't exist in any version of "free jqGrid"). It could be that one used some other old jQuery plugin (which has no relation to jqGrid), which uses `$.browser.msie`. The problem with the old plugin could be solved by usage [jQuery Migrate](https://github.com/jquery/jquery-migrate/#readme) plugin....

I can continue to guess. In any way, I'm almost 100% sure, that the problem, reported in the post has no relation to the current version of free jqGrid fork, which I develop. I see no sense in guessing. Because of that I asked the author of the post for providing the demo, which can be used to reproduce the problem. I get no response. Thus the problem is closed. If you have the same problem, please post detailed description of the problem inclusive the demo, which I can use to reproduce the problem.

**Comment by iamhammer** [comment] 2018-07-24 11:56
I apologize. It was premature of me to post. I was going down a rabbit hole
on a problem I don't yet fully realize the root or solution to yet, and
came across this issue. I appreciate your response.

**Comment by OlegKi** [comment] 2018-07-24 12:49
No problem! Then I hold the issue closed.
