### ISSUE TITLE
Problem on install package via composer

### ISSUE THREAD

**Issue by servocoder** [free-jqgrid/jqGrid#209] opened 2016-02-09 09:56 UTC
Hello,
I used to update free-jqgrid via composer, it worked fine all the time set up as `"free-jqgrid": "*"`, but today I found that it was updated to v.5.0.2 from the original `tonytomov` repo:
```
  - Removing bower-asset/free-jqgrid (v4.12.0)
  - Installing bower-asset/free-jqgrid (v5.0.2)
```
Have you made any changes on this?
Should I use some other version definition insted of `"free-jqgrid": "*"` now?

**Comment by OlegKi** [comment] 2016-02-09 11:26
Thank you very much for the bug report!

It's the problem with Git clients which I use for committing the local changes to the GitHub repository. Every new version or every new client which I test "optimize" the work. As the result one creates the tags v4.7.1, v4.8, v4.8.1, v4.8.2, v5.0.0, v5.0.1, v5.0.2 which belong to Guriddo jqGrid JS.

I deleted the tags now. I will verify the existence of the tags more carefully after committing the changes to GitHub.

Please verify that the problem is solved now and close the issue.

**Comment by servocoder** [comment] 2016-02-09 14:04
It's ok now.
Composer has installed 4.12.1 now, but I had to remove wrong package first. The `composer update` comand seems have no impact in this case.

Thanks for the quick response and announcement of the new features.

**Closed** 2016-02-09 14:04 UTC
Labels: bug
