### ISSUE TITLE
Scrolling a grid with frozen columns lags in IE

### ISSUE THREAD

**Issue by salimnanji** [free-jqgrid/jqGrid#158] opened 2015-10-22 14:33 UTC
In internet explorer (tested with IE 11), when you are using frozen columns and have many rows, the frozen columns  lag behind the unfrozen columns when you scroll with your mouse scroll wheel.

Issue does not exist in Chrome, or if you use the scroll bar.

See fiddle: http://jsfiddle.net/7kc6vppq/10/

**Comment by OlegKi** [comment] 2015-10-22 19:03
I hope that I understand you correctly. I made animated GIF with your demo (using [LICEcap](http://www.cockos.com/licecap/)). The results looks like

![delatedscrolling](https://cloud.githubusercontent.com/assets/249117/10675266/8b20cae8-78ff-11e5-9306-f0466ea72b63.gif)

One can see that the final results are **correct**, but IE first scroll one div and then another one. As the result one see even more as flicker, but the final results are correct. I see the problem as mostly IE problem. At least I don't know a good way how to make scrolling of two large divs be synchronous. Do you know a way how to implement this?

I want to stress that the problem is not pure problem of frozen column. I made in the above GIF horizontal scrolling additionally. You can comment the line with `.jqGrid("setFrozenColumns")` in your demo and try *horizontal scrolling*. You will see the same results:

![delatedscrollingnonfrozen](https://cloud.githubusercontent.com/assets/249117/10675410/4d42efc0-7900-11e5-83ad-44b4a4c6106d.gif)

**Comment by salimnanji** [comment] 2015-10-22 20:28
You understand correctly, that's exactly the issue. However, I could not think of a way to create a fix for this.

**Comment by OlegKi** [comment] 2015-10-25 16:27
I examined the problem once more and found out that the described problem exist only if **Use smooth scrolling** setting are enabled in Internet Explorer.

Click on **Internet Options** , choose **Advanced** tab and scroll down to: **Browsing** heading, clear the checkbox **Use smooth scrolling**. After that you can repeat the tests with your demo. You will see that the problem don't exist anymore.

Thus the reported problem I interpret as pure Internet Explorer problem, which can't be fixed by some changing in JavaScript code of free jqGrid.

**Comment by OlegKi** [comment] 2015-11-18 10:56
The issue is opened too. Please don't forget to close the issues or to write the comment which describes the current problems which you have.

**Closed** 2015-11-18 16:48 UTC
