### ISSUE TITLE
UTC datetime is not convetred to local time

### ISSUE THREAD

**Issue by petronellius** [free-jqgrid/jqGrid#310] opened 2017-04-03 11:38 UTC
Dates from server are in UTC Time zone and in ISO601Long format.
When local Time zone is e.g. UTC+1 time in browser is displayed with right offset.
On other hand when local Time zone is e.g. UTC-5 time in browser is not converted to local time and it is still in UTC.
Issue may happen in grid.base.js in parseDate function. Right offset is calculated when srcFomrat is ISO8601Long. (e.g. for UTC-5 ofsset = -240) Then bad condition is used (if offset > 0 ... never happens for negative offset).

**Comment by OlegKi** [comment] 2017-04-03 13:39
Please, post more detailed information about the problem. The test data and `colModel` are required of cause too. For example, the properties of the `formatoptions` (like `userLocalTime` property) are required. You should exactly describe the test case, which can I use to reproduce the problem, inclusive the expected text, which should be displayed in the column and the text, which one sees instead. You should understand that I can analyse and, if it will be required, fix the problem only if I'm able to reproduce the problem.

Please include in all issues the exact version of free jqGrrid, which you used. It's recommended to post the demo (in JSFiddle, for example), which reproduces the problem.

**Comment by petronellius** [comment] 2017-04-04 07:41
You can find sample for the issue [here](https://codepen.io/petronellius/pen/oZVjom).

When you set your local Time zone to some with positive offset from UTC conversion to local date works.
![timezonewithpositiveoffsetfromutc](https://cloud.githubusercontent.com/assets/12825401/24645842/c87c363c-18e7-11e7-912a-6025ad0a0032.PNG)

When you switch your local time zone to some with negative offset from UTC conversion to local date does  not work (negative offset is not added to UTC time).
![timezonewithnegativeoffsetfromutc](https://cloud.githubusercontent.com/assets/12825401/24645897/e79f2d76-18e7-11e7-8a2a-762f03c581e1.PNG)
I would expect the following times: 01/02/2017 03:22 am, 01/02/2017 03:23 am and 01/02/2017 03:25 am.

Solution may be removing checks for positive offset in parseDate method from grid.base.js file.

**Comment by OlegKi** [comment] 2017-04-04 09:31
Thank you for the demo and the description of the test case. Processing the date/time isn't easy because many people have a little different imagination how one should interpret the input data and how one need to display the parsed dates. I think that processing of the date/time is implemented currently in jqGrid not in the best way. On the other side I don't want to make too many changes, which could change the time displayed in the grid in *existing* projects.

In any way I posted some small changes, which fix one clear bug. After that one could use `userLocalTime: true` property of `formatoptions`. It's important that the property will work *only if the input data contains no `Z` at the end of the string (which isn't correct). The result can be seen on the demo https://codepen.io/OlegKi/pen/PpLaZe.

What I really suggest you is the usage of custom formatter to format the datetime. I created the demo  https://codepen.io/OlegKi/pen/XMGYQM, which demonstrates the approach. The demo is only the simplified prototype and you should for example process empty/undefined input data too and to implement `unformat` callback (see [here](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:custom_formatter#unformatting)). I used in the demo `toLocaleDateString` and `toLocaleTimeString`, which supported starting with IE11.

**Comment by GabrielMancik** [comment] 2017-04-04 10:36
Why is there still check for offset > 0 [here](https://github.com/free-jqgrid/jqGrid/blob/master/js/grid.base.js#L1244)?

**Comment by OlegKi** [comment] 2017-04-04 13:29
Thank you! I fixed the line too.

One have still problems in adjusting of the daylight saving time. My current location is Germany, where one use adjusting of the daylight saving time and the demo https://codepen.io/OlegKi/pen/PpLaZe displays
![date](https://cloud.githubusercontent.com/assets/249117/24658413/9f95d78e-1917-11e7-86be-4fa3daee8f20.png)
If I swich off the Window setting
![date1_adjust](https://cloud.githubusercontent.com/assets/249117/24658452/bfeab630-1917-11e7-85e1-e1e0df170316.png)
then I get
![date1](https://cloud.githubusercontent.com/assets/249117/24658388/8ed489cc-1917-11e7-8fb6-fc67092c7113.png)

One should  probably compare `getTimezoneOffset()` to detect whether one enabled daylight saving time or not. See [the answer](http://stackoverflow.com/a/11888430/315935) for more details. One should of cause not extend the `prototype` of `Date`, but just compare `getTimezoneOffset` for some summer day and some winter day, like in the referenced answer.

I'm a little busy now, but I will implement the fix later...

**Comment by petronellius** [comment] 2017-04-04 14:20
Thanks for your replay and fixes.
You are right, it is more complicated when DST is taken into account. My expected times were wrong, they should be shifted by an hour back ([UCT to EST](https://www.timeanddate.com/worldclock/converter.html?iso=20170102T072200&p1=1440&p2=tz_et)).
I will rather use custom date formatter together with toLocaleDateString / toLocaleTimeString or Moment.js.

**Comment by OlegKi** [comment] 2017-04-04 18:51
Exactly! I think that the usage of built-in functionality of the web browser, like `toLocaleDateString` / `toLocaleTimeString` or the usage of existing, good tested libraries like [moment.js](https://momentjs.com/), [globalize.js](https://github.com/globalizejs/globalize) (see `globalize/date.js` - [the date module](https://github.com/globalizejs/globalize#date-module)) are the mostly effective ways. The most problem is the compatibility. On the other side, one can easy add *more formatters*, which uses moment.js or globalize and you will fix all the problems.

By defining of
```JavaScript
$.fn.fmatter.mydate = function (cellValue, options) {
    // the code of custom formatter
};
$.fn.fmatter.mydate.unformat = function (cellValue, options, elem) {
    // the code of unformatter
});
```
one introduces the formatter, which you can be used as `formatter: "mydate"`. In the way, one can easy *extend* the standard set of [predefined formatters](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:predefined_formatter) in the way. It's what I would recommend you to use.

**Comment by OlegKi** [comment] 2017-05-01 11:01
The problem seems be solved after applying the above fixes. I tried to use `formatter: "date"` with `formatoptions: {..., userLocalTime: true}` and all my tests displays correct results. I'm closing the issue. If somebody will find some problem, that he/she can post the demo with the corresponding test data, which reproduces the problem. I remind that one can reopen the issue at any time, to post to closed issue or of cause to post new issue about close subject.

**Closed by OlegKi** 2017-05-01 11:01 UTC
