### ISSUE TITLE
Problem loading data from MySQL

### ISSUE THREAD

**Issue by alexandre1973** [free-jqgrid/jqGrid#355] opened 2017-07-17 06:33 UTC
Hello!  Trying to load data from a MySQL table but getting the error:

![error](https://user-images.githubusercontent.com/30169094/28257352-148e3dfc-6a98-11e7-86cb-531be896651b.png)

Here is the the JS code:
```JavaScript
$(function () {
    "use strict";
    jQuery("#list2").jqGrid({
        url:'users_grid_load_data.php?q=2', 
        datatype: "json",
        mtype: 'Get',		
        colNames:['Id','First Name', 'Last Name', 'Username','Level'], 
        colModel:[ 
            {name:'id_user',index:'id_user', width:55}, 
            {name:'firstname',index:'firstname', width:90}, 
            {name:'lastname',index:'lastname', width:90}, 
            {name:'username',index:'username', width:90},
            {name:'level',index:'level', width:80} 	 	 
        ], 
        rowNum:10,
        rowList:[10,20,30], 
        pager: '#pager2', 
        sortname: 'id_user', 
        viewrecords: true, 
        sortorder: "asc", 
        height:"auto",
        width:"auto",
        caption:"LIST OF USERS" 
    }); 
    jQuery("#list2").jqGrid('navGrid','#pager2',{edit:false,add:false,del:false});
});
```
and this is the PHP
```php
$page = $_GET['page']; 
$limit = $_GET['rows']; 
$sidx = $_GET['sidx']; 
$sord = $_GET['sord']; 

//if(!$sidx) $sidx =1; 

$result = $mysqli->query("SELECT COUNT(*) AS count FROM users"); 
$row = mysqli_fetch_array($result,MYSQLI_ASSOC); 

$count = $row['count']; 
if( $count > 0 && $limit > 0) { 
    $total_pages = ceil($count/$limit); 
} else { 
    $total_pages = 0; 
} 
if ($page > $total_pages) $page=$total_pages;
$start = $limit*$page - $limit;
if($start <0) $start = 0; 

$SQL = "SELECT * FROM users ORDER BY $sidx $sord LIMIT $start , $limit"; 
$result = $mysqli->query( $SQL ); 

$i=0;
$responce = new stdClass();
$responce->page = $page; 
$responce->total = $total_pages; 
$responce->records = $count;

while($row = mysqli_fetch_array($result,MYSQLI_ASSOC)) {
	$responce->rows[$i]['id']=$row['id_user'];
	$responce->rows[$i]['cell']=array($row['id_user'],$row['firstname'],$row['lastname'],$row['username'],$row['level']);
	$i++;
}
//error_reporting(0);
echo json_encode($responce);
```
Any help please??

Thanks

**Comment by OlegKi** [comment] 2017-07-17 11:01
I don't see clear error in the JSON data, which you posted. I recommend you to use Developer Tools of Chrome/IE or other free tool like [Fiddler](http://www.telerik.com/fiddler) to see the exact JSON response with all HTTP headers. You can use `jquery.jqgrid.src.js` instead of `jquery.jqgrid.min.js` and debug processing of the server response with respect of Developer Tools of Chrome or Internet Explorer. You can set breakpoint inside of `stdLoadError` function (see [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.14.1/js/grid.base.js#L2659)) and examine the reason of the problem in details.

**Comment by OlegKi** [comment] 2017-08-19 21:00
@alexandre1973 Please provide additional information or close the issue if the problem is solved already.

**Comment by OlegKi** [comment] 2017-08-31 17:59
@alexandre1973 : I didn't get any additional information from you during a long time. Thus, I close the issue. You can reopen it any time later.

**Closed by OlegKi** 2017-08-31 17:59 UTC

**Comment by alexandre1973** [comment] 2017-09-01 12:24
Sorry my delay! It worked since I stopped using it on a pc with Windows 10. The grid is working okay with windows 7 pro.
Thanks Oleg

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
