### ISSUE TITLE
Grouping in connection with loadonce is broken

### ISSUE THREAD

**Issue by dkrey** [free-jqgrid/jqGrid#172] opened 2015-11-10 09:39 UTC
Hi, 
it seems like grouping is broken if "loadonce" is being used.

If I delete a row from the grid via the internal edit actions, this group text is not being updated, although the record is gone.
`groupText : ['<b>{0} - {1} Server(s)</b>'] `

Also if I add a row from server side and reload it via 
`$("#instance_grid").trigger("reloadGrid", { fromServer: true, page: 1 });`
the grid is not being properly updated. The new rows aren't displayed and the groupText is also not updated.

This all works when loadonce or grouping are set to false.

Browsers: Firefox, Chrome
jqrids tested: 4.9.2 and 4.10.0
If needed I can also post the complete  grid code.

Thanks for looking into this :)

**Comment by OlegKi** [comment] 2015-11-10 10:22
**Could you prepare the demo, which reproduces the problem?** The current description allow too many interpretations. It's unclear, which editing mode you use, whether you use server side grouping or not. Do you return from the server correctly sorted data or not? Do you force reloading of the data (local/from server) after editing? I can continue. The demo could clear everithing. Please use non-minimized latest code of free jqGrid from GitHub (see [here](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs#access-githib-code-from-rawgit)) in the demo. I could understand, what you do exactly and I could *debug* the demo to see whether it's a bug in free jqGrid or in your program.

**Comment by dkrey** [comment] 2015-11-10 13:09
Of course, thanks a lot for looking into this:
http://www.sonores.de/jqgrid_group/index.php

The demo is a bit quick and dirty but the issue is still in there. The only things working are adding elements and deleting them.

**Comment by OlegKi** [comment] 2015-11-10 16:14
Thank you for the bug report and the demo, which reproduced the problem! Please refresh your sources of free jqGrid from GitHub. The bug should be fixed now.

I looked in the source of the demo which you send. I like to give you some tips.

First of all one can use `template: "integer"` and `template: "actions"`, which reduce the code and simplify `colModel`. You can find some standard templates [here](https://github.com/free-jqgrid/jqGrid/blob/v4.10.0/js/jquery.fmatter.js#L45-L122).

Seconds I would recommend you don't use the function like `getColumnIndexByName`. Free jqGrid have now `iColByName` parameter which contains the map of column index (`iCol`) by column name. You have column with `name: "action"`, Thus you can get the parameter by `var iColByName = $(this).jqGrid('getGridParam', 'iColByName');` and then use `iColByName.action` to get the index of `action` column. If you have the name of the column in variable `colName` then you can use `iColByName[colName]`.

The next tip. I recommend you to examin [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/CustomActionButton.htm) and [this one](http://www.ok-soft-gmbh.com/jqGrid/OK/CustomActionButton1.htm) and to read [the answer](http://stackoverflow.com/a/29735149) which demonstrates how to use new possibilities of free jqGrid to customize `formatter: "actions"`. It will simplify your code and speed up it. The whole code of `loadComplete` can be removed.

More tip. You can replace `pager: "#instance_pager"` parameter to `pager: true` and remove unneeded `<div id="instance_pager"></div>`. The parameter `"#instance_pager"` can be removed from `navGrid`. Free jqGrid will automatically generate the id of the pager and use it everywhere. I recommend you to use other options described in [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/New-style-of-usage-options-of-internal-methods). For example you can modify `navOptions: { reloadGridOptions: { fromServer: true } }` option of jqGrid to `navOptions: { view:true, add: false, edit: false, del: false, reloadGridOptions: { fromServer: true } }` add the option `searching: {multipleSearch : false}` and `formViewing: { closeOnEscape:true }`. After that you can use `navGrid` just without any parameters: `.navGrid()` (or `.jqGrid("navGrid")`). The part after `//options for add and edit row` (which not work because it set `$.extend(instance_grid.edit,{...})` instead of  `$.extend($.jgrid.edit,{...})`) can be replaced to the usage of `formEditing: {viewPagerButtons: false,...}` and `formDeleting: { afterSubmit : function(response, postdata){ ... } }`. In the way you will have clear code. Only if you want set **common defaulta over many HTML pages** then you should use `$.extend($.jgrid.edit,{...});`, `$.extend($.jgrid.del,{...});`, `$.extend($.jgrid.view,{...});`, `$.extend($.jgrid.nav,{...});`

Finally I want to repeat: thank you for reporting the bug! Please report all bugs which you find in the future too.

**Comment by dkrey** [comment] 2015-11-11 11:29
It's working perfectly fine now, thanks for this remarkably fast bugfix :)

I also highly appreciate your tuning tips for my grid code - it looks so much cleaner, now that loadcomplete is gone. :+1: 

**Problem is solved**

**Comment by OlegKi** [comment] 2015-11-11 11:42
You are welcome! I close the issue in the case. Please close the issues yourself in the future after the problem will be solved. I prefer that the person, who opens the issue, decide when it should be closed.

Please continue reporting of all bugs, which you could find in the future.

**Closed by OlegKi** 2015-11-11 11:42 UTC
Labels: bug
