### ISSUE TITLE
FilterToolbar with Text input 

### ISSUE THREAD

**Issue by gcet97it234** [free-jqgrid/jqGrid#244] opened 2016-06-15 22:02 UTC
I upgraded from 4.11 to 4.13.3 and my filter (text) type width became fixed width and it was not adjusted to 100%. I compared both version of codes and found that style 'style='width:100%;padding:0;' is not applied when input text text.

I put the code it and it is working fine.

**Comment by OlegKi** [comment] 2016-06-16 07:29
I'd recommend you to verify that you use the correct version of `ui.jqgrid.css`. Setting of inline CSS rules in the JavaScript code is not the best way. The old code of jqGrid contained many such places, which I eliminated sequentially and have moved in `ui.jqgrid.css`. Look at [here](https://github.com/free-jqgrid/jqGrid/blob/v4.13.3/css/ui.jqgrid.css#L1042-L1044). You will find the CSS rule
```css
.ui-search-input input {
	width: 100%;
}
```
which should applied for the text inputs from the filter toolbar. It could be that you have some coflict with other CSS included on the HTML page. You should provide the demo, which reproduces the problem.

**Comment by OlegKi** [comment] 2016-06-17 11:47
Do you have any progress in the issue?

**Comment by gcet97it234** [comment] 2016-06-17 15:21
Hi,
Thanks for your response. i was using wrong CSS.
i appreciate your work.
Thanks

Date: Fri, 17 Jun 2016 04:47:02 -0700

**Comment by OlegKi** [comment] 2016-06-17 16:26
You are welcome! It seems that the problem is solved and I am closing the issue.

**Closed by OlegKi** 2016-06-17 16:26 UTC
