### ISSUE TITLE
Overwrite feature in setGridParam method

### ISSUE THREAD

**Issue by inphekd** [free-jqgrid/jqGrid#409] opened 2017-12-25 09:58 UTC
SetGridParam by default extends the config object and in 99% of the situations thats what needed, but I stumbled upon a situation where I had to overwrite some parameters (in my case a simple array in postData) and trigger the grid reload. The overwrite feature in setGridParam overwrites the config, but I suspect it breaks the reference to the original object in memory, because of that the triggered reload uses the old config parameters. I have set up an [JSFiddle](https://jsfiddle.net/inphekd/wg3yshdc/) to illustrate the problem (NOTE: use the inspector to see what the request payload is during the initial Ajax request [1], when pressing the "Update postData in jqGrid" button [2] and "Overwrite postData in jqGrid" button [3]).

**Comment by OlegKi** [comment] 2017-12-25 13:40
I'm not sure that I understand your question or your suggestion. What exactly you suggest or ask?

I don't like to change the *existing* behavior of `setGridParam` to prevent *compatibility problems* with existing code. The method `setGridParam` (see [the existing code](https://github.com/free-jqgrid/jqGrid/blob/v4.15.2/js/grid.base.js#L6350-L6365)) supports optional *second* parameter, which could help to *overwrite* parameters.

I personally *almost never use* `setGridParam` method, because I find it unneeded. I use `getGridParam` instead. The method can be used **without parameters** (see [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.15.2/js/grid.base.js#L6347)) to get **the reference** to internal `p` property, which hold all parameters of jqGrid. To replace the `filters` property of `postData` to `newFiltersValue` one can use the following code:
```JavaScript
var p = $("#grid").jqGrid("getGridParam"); // get reference to all parameters
p.postData.filters = newFiltersValue;
```
Such code is very easy and it does exactly what one needs. You can easy change any other parameter of jqGrid in the way.

**Comment by inphekd** [comment] 2017-12-25 14:39
Tried your solution - it works [(Proof)](https://jsfiddle.net/inphekd/yuqorttf/). Awesome! The problem was that the "overwrite" feature in setGridParam does not work correctly. See the [(JSFiddle)](https://jsfiddle.net/inphekd/wg3yshdc/) and press the "Overwrite postData in jqGrid" button. Jqgrid makes the request, but not with the new/updated post data. At the moment I see three solutions:

1. Investigate further & fix the behaviour.
2. Deprecate the overwrite feature of the setGridParam method. A simple comment in source or console.log message would suffice.
3. Deprecate setGridParam method. A simple comment in source or console.log message would suffice.

**Comment by OlegKi** [comment] 2017-12-25 21:40
It seems that you misunderstand *what `setGridParam` do*. Additionally, your demo is strange because it contains no data (no `postData.json` like in https://jsfiddle.net/uvafmouo/ for example). In any way if you want to examine/validate what `setGridParam` do then you should use `getGridParam` to examine `postData.filters`. For example, the demo https://jsfiddle.net/wg3yshdc/4/ is the same like your previous demo, but where I added the line
```JavaScript
alert(JSON.stringify($("#grid").jqGrid("getGridParam", "postData").filters));
```
after the call of `setGridParam`. You can easy verify that "Overwrite postData in jqGrid" works like expected.

If you want to report **the bug** in `setGridParam` for example, then you should clear formulate what the method *should do* in your opinion and prepare the test case, which works not like you expect. The method `setGridParam` is nothing more as **wrapper on `jQuery.extend`** applied on the `p` (parameters) object of jqGrid. The standard mode uses deep mode of `jQuery.extend`:
```JavaScript
$.extend(true, this.p, newParams);
```
and the "overwrite mode" uses non-deep 
```JavaScript
this.p = $.extend({}, this.p, newParams);
```
It's known, that the deep mode *combines* elements of arrays in the same way like it combines properties of objects. I suppose that the behavior of `$.extend` makes misunderstanding for you. In any way it's documented behavior of `$.extend` and not a bug of `$.extend`. In the same way, all your examples works as expected and the only problem, which I see: you use `setGridParam` in the wrong situation or in the wrong way.

By the way, one important problem of `setGridParam` could be the performance. It applies `$.extend` to **the whole parameters object** even if you need to change only one small property (see "overwrite mode" especially). The code, which I suggested you in my previous comment
```JavaScript
var p = $("#grid").jqGrid("getGridParam"); // get reference to all parameters
p.postData.filters = newFiltersValue;
```
changes **only one property** without any misunderstandable side effects. It's the way, which I'd recommend you to use.

The last remark. The value of `postData.filters` should be **JSON string** and not an object, like you use in your demo. In the most cases jqGrid tolerate the object value and everything still work. On the other side you will not have the problem, which you tried to report, if you would follow the standard behavior and to use JSON string as the value of `postData.filters`. See https://jsfiddle.net/wg3yshdc/5/, which demonstrates that. The string value has no problems with *combines* elements of arrays from inside of JSON string and one will have no problems.

**Comment by inphekd** [comment] 2017-12-25 22:59
The response data is irrelevant, thats why I didn't bother adding the json. Anyway... using the latest fiddle revision where the filter value is converted to JSON string [(https://jsfiddle.net/wg3yshdc/5/)](https://jsfiddle.net/wg3yshdc/5/) you can clearly see after pressing the overwrite button the alert shows the updated filter data, but the request sent old filter data and not the new.

**Comment by OlegKi** [comment] 2017-12-26 18:55
I agree with your last post: `setGridParam` has a bug in case of usage `overwrite: true` parameter. Thank you! I posted [the changes](https://github.com/free-jqgrid/jqGrid/commit/c6367bb01c2bd374ae344aeeb7b65c008dc00c7a), which should fix the problem. See https://jsfiddle.net/wg3yshdc/6/, which is identical to https://jsfiddle.net/wg3yshdc/5/, but which uses the latest version of free jqGrid from GitHub.

**Comment by inphekd** [comment] 2017-12-26 19:47
Awesome! Thanks!

**Comment by OlegKi** [comment] 2018-01-03 23:28
The problem is solved and I'm closing the issue. @inphekd Please think about closing the issues in the future. I find better if the person, who reports the issue, close it.

**Closed by OlegKi** 2018-01-03 23:28 UTC
Labels: question
