### ISSUE TITLE
No chaining?

### ISSUE THREAD

**Issue by PeterSandberg** [free-jqgrid/jqGrid#170] opened 2015-11-07 16:09 UTC
This code only set the width of the first grid:

```javascript
$('#element').find('.class').jqGrid('setGridWidth', newWidth)
```

Have to do:
```javascript
$('#element').find('.class').each(function () {
    $(this).jqGrid('setGridWidth', newWidth);
}
```

Am I doing something wrong or is it by design?

**Comment by OlegKi** [comment] 2015-11-07 17:43
Sorry, but I don't full understand your question. What do you by usage `$('#element').find('.class')`? If you just have jQuery wrapper with more as one `<table>` elements, which are already converted to the grid (for example you use `$(".ui-jqgrid-btable")`), then you could use `setGridWidth` *on every* grid. In other words jQuery chaning should work. I'm not sure what is your question. Do you have problems with *selection* of the grids and creating the corresponding jQuery wrapper or you have problem with execution `setGridWidth`? You can have some problems with selection for example if you use frozen columns. You should remove from `$(".ui-jqgrid-btable")` all elements, which have `div.frozen-bdiv` as parent.

It would be better if I would not guess about the problem which you try to report. Instaad of that I'd ask you to describe the problem of the question which you have more detailed and to create small demo, which demonstrates the problem. Please use non-minimized version of free jqGrid for the demo.

**Comment by PeterSandberg** [comment] 2015-11-08 10:39
Example: https://jsfiddle.net/jgyw04oy/23/

I thought that the button should resize all grids!

**Comment by OlegKi** [comment] 2015-11-08 11:24
Thanks for the bug report and for the demo. Only debugging allows to localize the problem. The old code **has modified** the input parameter `newGridWidth` during processing of `setGridWidth` for the first grid. Thus the setting the width for the other grids was with wrong width value. I posted [the bug fix](https://github.com/free-jqgrid/jqGrid/commit/5453cb5472f7a5a65a33fc8f50a2004f843481b4) just now and your demo works already.

**Please test the new code from GitHub and close the issue, if you confirm that the bug is fixed now.**

Please include always the demo which reproduces the reported problem. You see that having the demo I can fix the problem very quickly.

Some common remarks to the demo. I suppose that you created the demo based on the real code which you use. Because of that I decide to write the comment. The demo which you posted have at least two important problems, which are independend from the reported bug.

The first problem: all demos uses the same data **with the same id values**. As the result the values will be used to assign the values of `id` attributes of the rows (`<tr>` elements) of the grids. Thus one will have **id dupplicates**. To fix the problem one can use `idPrefix` in every grid with *different unique value*. I used `idPrefix: "g1_"`, `idPrefix: "g2_"` and `idPrefix: "g3_"` in the modified demo https://jsfiddle.net/OlegKi/jgyw04oy/25/. As the result the rowid (`id` of `<tr>`) for the first row of the first grid was "g1_10" instead of `"10"`, for the second grid: "g2_10" instead of `"10"` and for the third grid: "g3_10" instead of `"10"`. No id duplicates exist on HTML page.

The second problem: you used `{ name: 'id', index: 'Id', width: 25, key: true }` and `sortname: 'Id'`. It's wrong. The grid with local data (`datatype: "local"`) should never use `index` property in `colModel` or to use **the same values** for `index` and `name`.

You should not mix string values with numeric content (like `'500'`) with numeric values. Many parts of the code use strict equality operations `===` and `!==` which don't make any type conversion. Thus the usage of the values with wrong type can produce wrong results. The current code uses `parseInt(newGridWidth, 10)`, but other place of the code cold don't do this. Thus please uses `Number` values for numeric parameters or options.

**Comment by PeterSandberg** [comment] 2015-11-08 11:25
thanks for your great work Oleg

**Comment by OlegKi** [comment] 2015-11-08 11:37
You are welcome! I remind you to test the results and to close the issue. I could do this myself of cause, but I prefer that the issue be closed by the person, who opened it. Thank you once more for reporting the bug.

**Closed** 2015-11-08 11:43 UTC
Labels: bug
