### ISSUE TITLE
Resize column - drag line wrong position

### ISSUE THREAD

**Issue by witek1902** [free-jqgrid/jqGrid#229] opened 2016-04-30 07:34 UTC
Hi,
I have problem with resize column in free-jqgrid.
Drap line is on wrong position: http://i.imgur.com/JBPPf2o.png

Is this my local problem or bug in free-jqgrid?

**Comment by OlegKi** [comment] 2016-04-30 09:28
Could you provide the demo, which reproduce the problem and which I can debut (it should use `jquery.jqgrid.src.js` instead of `jquery.jqgrid.min.js`)? I can't reproduce the problem (see https://jsfiddle.net/pqL7d004/4/ for example).

**Comment by OlegKi** [comment] 2016-05-03 14:06
Do you have any progress in the issue? Can you reproduce the problem in free jqGrid 4.13.2?

**Comment by witek1902** [comment] 2016-05-03 18:24
Hello Oleg, I'm sorry for late but until tomorrow I have access to enviroment where I can try reproduce this bug. Please wait :)

**Comment by witek1902** [comment] 2016-05-06 07:54
Hi Oleg, I found solution. I defined custom css for jqGrid that created this problem. Remove custom css  = fixed :)

**Comment by OlegKi** [comment] 2016-05-06 09:26
OK, I'm closing the issue. Please provide the demo, which can be used to reproduce the reported problem next time. The demo simplifies the analyse and the solution of the the problem.

Best wishes!

**Closed by OlegKi** 2016-05-06 09:26 UTC
