### ISSUE TITLE
Sorting a local data grid screws up the rows

### ISSUE THREAD

**Issue by bigman73** [free-jqgrid/jqGrid#204] opened 2016-02-03 19:23 UTC
I moved from jqGrid to free-jqGrid and immediately saw the problem.
Same source code and same data re-produces the problem on free-jqGrid.

Here's an example with jqGrid, working fine:
http://jsfiddle.net/yk0bvw45/

![2016-02-03 14_22_05-working jqgrid example - jsfiddle](https://cloud.githubusercontent.com/assets/5384551/12794129/944d1558-ca81-11e5-8aeb-8482c83b5d71.png)

And the same source code but this time with free-jqGrid:
http://jsfiddle.net/6pbob613/

The second example clearly shows that the last row is replicated on top of the other rows.

![2016-02-03 14_21_07-working jqgrid example - jsfiddle](https://cloud.githubusercontent.com/assets/5384551/12794092/7040ce52-ca81-11e5-8d08-21d8a7b4e1bd.png)

If sorting is not performed the rows show up fine with free-jqGrid, so it probably points to some issue within the sorting functionality

**Comment by OlegKi** [comment] 2016-02-04 14:49
First of all your demo have some small bugs like usage of `sorttype: "float"` for the column which have string data (`"OPEN"`, `"ENTERED"`). Seconds is the code, which you posed slow because of the usage `addRowData` and it's of cause not recommended way to fill the grid. The way is especially bad if you fill the grid with more data as the page size (`rowNum` value). The inserted data will be first included *unsorted* and **all the data will be placed on one page**. The filling of 10000 rows in the way will be very very slow in your way and will be less as a second (250ms on my computer for 40000 rows in [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/performane-13-40000-20-free-jqgrid.htm)). 

Correct way will be to use `data: data` parameter of jqGrid. It makes large difference in performance if you insert many rows of data. The resulting code http://jsfiddle.net/6pbob613/3/ works without any problem.

If you need to set the data of the grid *later* then you can use the following code
```
var p = $grid.jqGrid("getGridParam");
p.data = data;
$grid.trigger("reloadGrid");
```
which will be quickly too. See another demo http://jsfiddle.net/6pbob613/1/

Independent from the problem of performance the form in which you fill the grid is allowed form of usage, but free jqGrid provided the wrong results. **Thank you very much for reporting the problem!** I fixed the code of `addRowData` now (see [the commit](https://github.com/free-jqgrid/jqGrid/commit/eb1055702335b44f61670997d491f45f129782a1)) and your original code (after replacing the URLs to jqGrid from GitHub and removing wrong `sorttype: "float"` property) works now: http://jsfiddle.net/6pbob613/2/

**Comment by bigman73** [comment] 2016-02-04 16:09
Hi Oleg,
Thanks for pointing out all these very valuable points and also committing a fix.
I think what you guys are doing with free-jqGrid is amazing. Keep on the good work!

I actually took the example from a stackoverflow jsfiddle I stumbled upon, it is not my code. But I should have been more careful verifying that the 3rd party code is correct (in regards to sorting data types).  I agree about performance issues, but again, I didn't want to demonstrate that but focus on the sort issue, the jsfiddle I found just demonstrated very well how the bug reproduces.
Good thing you provided a better jsFiddle so others don't copy-paste "my" incorrect version.

Thanks,
Yuval

**Comment by OlegKi** [comment] 2016-02-04 16:43
You are welcome! It seems that the problem is solved and I close the issue. Please close the next issue yourself. I try to hold the rule that the person who opens the issue review all the changes and close the issue after confirmation that the problem is really solved. Best wishes!

**Closed by OlegKi** 2016-02-04 16:43 UTC
