### ISSUE TITLE
Right way to change refresh button functionality to preserve filters

### ISSUE THREAD

**Issue by argaliev** [free-jqgrid/jqGrid#137] opened 2015-09-01 09:59 UTC
From  documentation about refresh button: "When the button is clicked a trigger(“reloadGrid”) is executed and the search parameters are cleared". So I need only reloadGrid without clean search parameters. <br />
After looking at onRefresh  method realization in code,  I was found that if  option refreshstate is switched to "currentfilter", postData not cleaned, but search flag is set to false; In the end "reloadGrid" triggered: 
```javascript
       $self.trigger("reloadGrid", [$.extend({}, o.reloadGridOptions || {}, { current: true })]);
```
I add {search:true} to reloadGridOptions but no luck. 
After debug i found that "search:true" was passed to called method, but it seems to be that seach option is ignored, for example code:
```javascript
        $('#grid').trigger('reloadGrid', [{search:true, page:2}])
```
will set page to 2, but won't change seach to true if it was false;
Also setGridParam {seach:true} with reloadGrid works ok.
I use datatype: json.

Is it possible to preserve filters that way, or need simply remove standard button, and add my custom button?

**Comment by OlegKi** [comment] 2015-09-01 13:44
If I understand the problem correctly than you have the problem not with `reloadGrid`, but with Reload button added by `navGrid` method. The option `refreshstate: "currentfilter"` provides the most close to what you need, but it still reset `search` parameter to `false`. To tell the truth I don't full understand why you could need to reload the data with applied filter. I suppose that you need to reload the data from the server.

I see two main options to implement your requirements:
 1. Don't create any Reload button at all (use `refresh: false` option of `navGrid`) and to use `navButtonAdd` to add custom button which look exactly like Reload/Refresh button, but which just call `reloadGrid` without clearing `postData.filters` or `search`.
 2. You can use `beforeRefresh` to set some information, like `this.p.myReload = true;`, which allows to distinguish "your reload" from any other reloading. You can use `beforeRequest` callback of jqGrid to reset `postData._search` to `true` and set `search` parameter to `true` too if `myReload` parameter is true. You should of cause reset or remove the value of `myReload` parameter additionally.

Every from the ways seems to me acceptable and could solve your problem.

**Comment by argaliev** [comment] 2015-09-02 04:35
"I suppose that you need to reload the data from the server." - absolutely right.

Thanks for your answer!

**Comment by OlegKi** [comment] 2015-09-09 05:35
Is the problem is solved now? Please close the issue or describe the currently opened problems.

**Closed** 2015-09-09 05:43 UTC
Labels: question
