### ISSUE TITLE
Page state is not retained while sorting a column

### ISSUE THREAD

**Issue by Velu-Narasimman** [free-jqgrid/jqGrid#406] opened 2017-12-13 05:17 UTC
As discussed [here](https://stackoverflow.com/questions/47546498/how-to-retain-expand-collapse-state-in-jqgrid-grouping/47546617?noredirect=1#comment82482887_47546617), If there are 5 pages in my grid and I navigate to third page and sort a column, sorting goes well but the grid is reloaded and I am redirected to the first page of the grid instead of staying at the third page itself.

How to make the grid remain in the same page while doing sorting? Please help me on this.

**Comment by OlegKi** [comment] 2017-12-13 17:17
Thanks für reminding about the problem. I'll examine it after I'll come back from the business trip.

First of all an addition information for other readers of the issue. The problem is specific for **sorting of locally grouping data only** and it's not an general string issue. 

I think that I'll make some changes in the code of jqGrid to solve the problem, but I have to examine the problem more deep before.

**Comment by OlegKi** [comment] 2017-12-19 00:00
I could not find any good solution and then just added new option `resetPageAfterSort`, which could be used to prevent resetting of the page number to 1. The demo https://jsfiddle.net/92da8xhq/6/ uses the latest code from GitHub and the option `resetPageAfterSort: false`. I think the demo works like you expect.

**Comment by OlegKi** [comment] 2018-01-03 23:32
The problem is solved and I'm closing the issue.

@Velu-Narasimman  Please think about closing the issues in the future. I find better if the person, who reports the issue, close it.

**Closed by OlegKi** 2018-01-03 23:32 UTC
