### ISSUE TITLE
How to implement format and Unformatting for select type

### ISSUE THREAD

**Issue by rajeshks117** [free-jqgrid/jqGrid#133] opened 2015-08-26 02:23 UTC
I have a requirement where i have to show href link in read only mode but drop down in edit mode. "formatter" option works fine but when i click on the row to edit the selected value get lost. Can you please help and guide how to implement this where edit row will select the correct value automatically.

**Comment by OlegKi** [comment] 2015-08-26 05:14
Could you post more details what you do? Which options of jqGrid you use (`datatype`, `loadonce`, `colModel`, ...)? Which editing mode you use (form editing, inline editing, cell editing)? The definition of the column in `colModel` is really required. Moreover you wrote: "i have to show href link in read only mode". What you mean with "read only mode"? Typically in means `editing: false`, but you write about "drop down in edit mode". So it's unclear what you really need to implement. It would be good if you post the demo which represent the current state of the implementation and to clear more exactly what you need to implement.

**Comment by rajeshks117** [comment] 2015-08-26 13:56
Let me explain further.. Here is my ColModel. This is an infinite scroll grid. so loadonce is false.
{name: 'proposedPrvFlg', index: 'proposedPrvFlg', width: 67, editable: true, formatter: myDistributionFormatter, unformat:myDistributionUnFormatter, edittype: "select", stype: 'select',
            classes: 'recommended', editoptions: {value: privateFlags, dataEvents: cartModal.creditOpinionModalEvt()}, searchoptions: gridSearchOptions}

var myDistributionFormatter = function(cellValue, options, rowObject) {
    if (rowObject.reason !== null && reason !== '') {
        return "<a href='' onclick=\"cartCustomFormatter.openCreditOpinionDistributionDialogFromHyperLink(event,'" + rowObject.reasonId + "')\">" + $.jgrid.htmlEncode(cellValue) + "</a>";
    }
    else
        return $.trim(cellValue);
};


I am unable to come up with an elegent method to set the selected value when user tries to edit the row. Sorry for not loading the demo grid as it's too complicated.

**Comment by OlegKi** [comment] 2015-08-26 14:31
Sorry, but what you posted is small part of the code only. There are a lot of unknown functions and variables like `myDistributionUnFormatter`, `privateFlags` and so on. *The format of input data, which you use is absolutely unclear for me*. If you write about "an infinite scroll grid" you mean probably virtual scrolling, but it's unclear which value for `scroll` you use: `true` or `1`, it's unclear, which value of `datatype` you use (`"local"`, `"json"`, `"xml"`, ...). I asked you: which editing mode you use? You didn't answered too.

Sorry, but if you want that I help you then you should provide all required information. I still have no idea what you do, whether you edit local data or not, whether you save editing result on the server or edit the data locally. All editing options which you use are unknown too. I don't know which input data you have and how should looks like the results of editing. In other words I know almost nothing about what you do and what you need to implement.

**Comment by OlegKi** [comment] 2015-09-09 05:37
Is the problem is solved now? Please close the issue or describe the currently opened problems.

**Closed** 2015-09-10 00:30 UTC
Labels: question
