### ISSUE TITLE
Problem with grouping column

### ISSUE THREAD

**Issue by Rhend** [free-jqgrid/jqGrid#342] opened 2017-06-06 12:55 UTC
Hi,

First of all, thank you so much for this Free jqGrid, it's an awesome tool and i'm very grateful, Oleg ! 

I have a problem since i update the script from 4.13.5 to 4.14.1 with a grid who has some grouping column. Here's the problem : 
![image](https://cloud.githubusercontent.com/assets/2518681/26830148/23a583e4-4ac8-11e7-9cfa-649266e6aa02.png)

and here's my script 

![image](https://cloud.githubusercontent.com/assets/2518681/26830053/dc216484-4ac7-11e7-86ad-a6d456ee7ae1.png)

I try to search on the wiki some update about how grouping works now but didn't find anything.. If anyone can give me some advice on how i can resolve this bug ?

Thanks a lot

**Comment by OlegKi** [comment] 2017-06-06 16:00
Please provide **the demo**, which can be used to reproduce the problem, instead of pictures.

One can still see some problems in the code which you posted in the pictures:

1. you use `groupField : ['annee de paiement']`, but the value of `groupField` should be array of strings, which values have to be the values of `name` property of `colModel`. The problem is: the values of  `name` property of `colModel` must correspond the rules of `id` in HTML. **HTML5 don't allow to use spaces** (see [here](https://www.w3.org/TR/html5/dom.html#the-id-attribute) the text "The value must not contain any space characters"). You should fix  `name` properties of `colModel` to use unique values **without spaces**. If you don't control input data (`mydata`) and you have to parse properties, which contains spaces, then you should use `jsonmap`.
2. you use wrong value for `groupOrder`, `groupColumnShow` and `groupSummary` properties of `groupingView`. The values of the properties should be **arrays** (see [here](https://github.com/free-jqgrid/jqGrid/blob/v4.14.1/ts/free-jqgrid.d.ts#L1251-L1255)). It's easy understand if you think about grouping by *multiple fields/columns*.

In other woulds you should fix the value of `groupField` (or the value of `name` of `colModel`) to use the values **without space** and to fix the following properties of `groupingView`
```JavaScript
    groupOrder: 'desc',
    groupColumnShow: false,
    groupSummary: true
```
to
```JavaScript
    groupOrder: ['desc'],
    groupColumnShow: [false],
    groupSummary: [true]
```

**Comment by Rhend** [comment] 2017-06-08 08:26
Hi Oleg ! 

Thanks you ! The problem was on the value of `groupField` !

**Comment by OlegKi** [comment] 2017-06-08 09:09
You are welcome! Is the problem is solved now or something is still wrong? Please close the issue if the problem is solved.

**Closed** 2017-06-08 09:14 UTC
Labels: question
