### ISSUE TITLE
onSelectRow doesn't fire after migrated from jqgrid to free-jqgrid

### ISSUE THREAD

**Issue by ryanlin1986** [free-jqgrid/jqGrid#51] opened 2015-04-22 08:14 UTC
this.jqGrid = (<any>$(this.component.element).find('table')).jqGrid({
 onSelectRow(rowid, status, e) {
                            alert('never fired');
                        },
});
It worked in jqgird 4.7.

**Comment by OlegKi** [comment] 2015-04-22 11:30
Sorry, but you have to post the code or the URL of the demo (which uses non-minimized code of free jqGrud), which can be used **to reproduce** the problem.

You can try [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/dateInput_48_bootstrap-booleanCheckboxFa.htm) for example to see that the callback `onSelectRow` will be do called by free jqGrid. If it will be not called under some specific conditions then you should provide the corresponding demo and the test case.

**Comment by ryanlin1986** [comment] 2015-04-22 13:45
Hi OlegKi,
Thanks for your quick response, after some investigation I figured out that the problem occurs only when cellEdit set to true and multiselect to false.
I'm not sure if this is by design, as my opinion, even the cellEdit set to true, but the event still should be fired, at least when I click on non-editable cells.

**Comment by OlegKi** [comment] 2015-04-22 14:17
I'm not sure why one could need to select rows if one uses `cellEdit: true` option which use **cell selection** (for non-editable cells) and cell editing. I don't tested, but it seems to me that the same behavior was already before.

One can use `beforeSelectRow` or `onCellSelect` to in combination with `cellEdit: true`.

**Comment by OlegKi** [comment] 2015-05-24 15:13
Please close the issue if the problem is solved already or post some additional information which can be used to reproduce the problem.

**Closed** 2015-05-28 03:30 UTC
