### ISSUE TITLE
Building with grunt need --force, fails otherwise

### ISSUE THREAD

**Issue by dkrey** [free-jqgrid/jqGrid#199] opened 2016-01-20 15:29 UTC
Hi,
building jqgrid via grunt  exits with these "Illegal trailing whitespace" errors:

    Running "jscs:all" (jscs) task
    Illegal trailing whitespace at js/jquery.jqgrid.src.js :
      9718 |  *
      9719 |  * The filter uses JSON entities to hold filter rules and groups. Here is an example of a filter:
      9720 |
    ---------^
      9721 | { "groupOp": "AND",
      9722 |    "groups" : [
    Illegal trailing whitespace at js/jquery.jqgrid.src.js :
     10478 | /**
     10479 |  The below work is licensed under Creative Commons GNU LGPL License.
     10480 |
    ---------^
     10481 |  Original work:
     10482 |
    Illegal trailing whitespace at js/jquery.jqgrid.src.js :
     10480 |
     10481 |  Original work:
     10482 |
    ---------^
     10483 |  License:     http://creativecommons.org/licenses/LGPL/2.1/
     10484 |  Author:      Stefan Goessner/2006
    Illegal trailing whitespace at js/jquery.jqgrid.src.js :
     10484 |  Author:      Stefan Goessner/2006
     10485 |  Web:         http://goessner.net/
     10486 |
    ---------^
     10487 |  Modifications made:
     10488 |
    Illegal trailing whitespace at js/jquery.jqgrid.src.js :
     10486 |
     10487 |  Modifications made:
     10488 |
    ---------^
     10489 |  Version:     0.9-p5
     10490 |  Description: Restructured code, JSLint validated (no strict whitespaces),
    Illegal trailing whitespace at js/jquery.jqgrid.src.js :
     10492 |  Author:      Michael Schøler/2008-01-29
     10493 |  Web:         http://michael.hinnerup.net/blog/2008/01/26/converting-json-to-xml-and-xml-to-json/
     10494 |
    ---------^
     10495 |  Description: json2xml added support to convert functions as CDATA
     10496 |      so it will be easy to write characters that cause some problems when convert
    >> 6 code style errors found!
    Warning: Task "jscs:all" failed. Use --force to continue.
    
    Aborted due to warnings.

Building jqGrid-4.11.1 via grunt works fine, 4.12.0 also fails.
If you build it via --force, everything works as expected - so this might just be a cosmetic issue.

**Comment by OlegKi** [comment] 2016-01-20 17:12
It could be important to know which operation system you use during building. Moreover you should use the latest version 4.12.1 instead of 4.12.0.

I suppose that the reason of the problem in [the part](https://github.com/free-jqgrid/jqGrid/blob/master/gruntfile.js#L83-L119) of `gruntfile.js`. I included [the comment](https://github.com/free-jqgrid/jqGrid/blob/master/gruntfile.js#L86-L89), where I shortly describe the reason of a possible problem. The code fragment cuts the first common part from every file holding the licence agreement and holding the left margin, which, corresponds the left margin of the main code.

For example the modules `grid.base.js`, `grid.celledit.js`, `grid.common.js`, ..., `jquery.fmatter.js` will be concatenated to one file `jquery.jqgrid.src.js`. [The last line](https://github.com/free-jqgrid/jqGrid/blob/v4.12.1/js/grid.base.js#L6959) of `grid.base.js` will be removed, [the license comment](https://github.com/free-jqgrid/jqGrid/blob/v4.12.1/js/grid.celledit.js#L1-L8) at the beginning of `grid.celledit.js` will be moved right (one tab will be inserted at the beginning of all lines), and [some other first lines](https://github.com/free-jqgrid/jqGrid/blob/v4.12.1/js/grid.celledit.js#L9-L55) of `grid.celledit.js` will be full removed. [The local variables](https://github.com/free-jqgrid/jqGrid/blob/v4.12.1/js/grid.celledit.js#L56-L63) declared after [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.12.1/js/grid.celledit.js#L56) `// begin module grid.celledit` will be *local* variables in the same function as `grid.base.js`, which gives minimizer more possibilities for minimization and usage of shared variables.

I suppose that `gruntfile.js` should me adjusted in [the area](https://github.com/free-jqgrid/jqGrid/blob/v4.12.1/gruntfile.js#L97-L120), so that some `"\n"` will be replaced to [grunt.util.linefeed](http://gruntjs.com/api/grunt.util#grunt.util.linefeed), which corresponds to newline charackters, used on the current operation system. You can try to make the changes so that there will corresponds your operation system and I will combine all in one `gruntfile.js`.

**Comment by dkrey** [comment] 2016-01-21 08:22
oh sorry, I should have mentioned I've used Win7 and 4.12.1. What I meant to say is, that it stopped working flawlessly with 4.12.0
After downloading a fresh zip from here, all linebreaks are in \r\n. After running grunt, they get converted to \n and rebuilding jqgrid afterwards works without any warnings.
I hope this helps.

**Comment by OlegKi** [comment] 2016-01-21 08:47
OK, no problem. I'm sure that the origin of the problem was old sources of free jqGrid, which you used before. In any ways, it sound that the problem is solved now and I close the issue.

If you use `grunt` to build free jqGrid on Windows computer then you get `jquery.jqgrid.src.js` which uses `\r\n` and `jquery.jqgrid.min.js` which uses `\n`. No warnings should be displayed by `jscs`.

**Closed by OlegKi** 2016-01-21 08:47 UTC
