### ISSUE TITLE
import export function is broken

### ISSUE THREAD

**Issue by ibschreiber** [free-jqgrid/jqGrid#273] opened 2016-10-12 11:21 UTC
the function to import and export grid settings is broken. 
the reason is due to the way the config is saved. Functions are serialized, too, which results in invalid JSON data. 
One solution would be to remove those from json which would result in missing functions.
The better way would be to put the default config into the import function which is then merged with column settings and order.

**Comment by OlegKi** [comment] 2016-10-12 22:05
Could you describe more exactly what you mean? Which version of free jqGrid you use? Which methods of jqGrid you mean?

There are many ways to export settings or export the state of jqGrid. [The demo](http://www.ok-soft-gmbh.com/jqGrid/OK/ColumnChooserAndLocalStorage2_singleSelect.htm), created for [the answer](http://stackoverflow.com/a/31663268/315935), demonstrates how to save the grid state in `localStorage` and restore it on the next visiting of the same page.

Free jqGrid contains old methods `jqGridExport`, `jqGridImport` and `excelExport`, which are unchanged from the jqGrid 4.7. I personally don't use there. I suppose that you use the method `jqGridExport` in the way
```JavaScript
var opt1 = $("#grid").jqGrid("jqGridExport");
```
or like
```JavaScript
var opt2 = $("#grid").jqGrid("jqGridExport", {exptype: "jsonstring"});
```
You can take look in the code of the method `jqGridExport` (see [here](https://github.com/free-jqgrid/jqGrid/blob/v4.13.4/js/grid.import.js#L155-L204)) to find out that it get mostly the options of jqGrid with respect of `getGridParam` method and then calls `xmlJsonClass.json2xml` or `xmlJsonClass.toJson` to export the settings. Thus you can just use, for example,
```JavaScript
var opt3 = JSON.stringify($("#grid").jqGrid("getGridParam"));
```
to convert the current options to JSON string. Serializing to JSON will don't serialize any function. It could solve the problem. One can use `$.parseJSON` or `JSON.parse` to convert the JSON string back to the object.

**Comment by OlegKi** [comment] 2016-10-20 14:05
The issue is still opened. Please provide additional information, which I asked you or close the issue.

**Comment by ibschreiber** [comment] 2016-10-20 14:12
Hi Oleg. I mean the jqGridExport functionality. Yet, I found a much better solution by extracting the data qhich I want to save and send it to the server. When loading the grid, I merge the default options with the ones saved on the server. Much better than the jqGridExport functionality which is an abolute overkill and not save for table changes at all. In my opinon, this functionality should be removed from the code as it leads to unexpected behaviour in case of changes. 
A function jqGridExport which can be configured ( {filter:true, order:true, colOrder:true, colWidth:true, ...} would be the perfect solution.
Thank you for your time,
Michael

**Closed** 2016-10-20 14:13 UTC

**Comment by OlegKi** [comment] 2016-10-20 14:27
Hi Michael,

I have the same opinion about the usage of `jqGridExport`, but I will still hold the part of the code only to have better compatibility with the old versions of jqGrid (versions <=4.7).

Best wishes
Oleg
