### ISSUE TITLE
inline-editing local data, after page move, edited  data  disappear(while added record is OK)

### ISSUE THREAD

**Issue by alpastar** [free-jqgrid/jqGrid#354] opened 2017-07-12 10:12 UTC
$grid.jqGrid({
 // We need 3 attributes to use the local data
 // 1) datatype 2) datastr 3) jsonReader
 // datatype: 'jsonstring',
 // datastr: go_xport.a_jq_data,
 // Used to read the data from json object and assign to JqGrid
  jsonReader: {
    repeatitems: false,
    //root: "rows",
    //page: "page",
    //total: "total"
    //id: "0"
  },  
  datatype: "local" ,               // 
  data:  go_xport.a_jq_data,
  loadonce : true ,                  // 
  editurl  : 'clientArray' ,         // it wont connect to any server and leave your data alone 

// inlineNav 

 $grid.jqGrid('inlineNav','#jq_pager', { 
     iconsOverText: true ,
      edit   : true  ,          
      add    : true  ,  
      search : false,
      refresh: true ,

    addParams: {
      addRowParams: {       // the parameters of editRow used to edit new row
         keys: true,
         oneditfunc: function (rowid) {              // before-edit 
          // alert("new row with rowid=" + rowid + " are added.");
         }
      }
    },

    editParams: {                // the parameters of editRow
       key: true,
       url:'clientArray',                // not  'clientarray' 
       oneditfunc: function (rowid) {
           // alert("row with rowid=" + rowid + " is editing.");
       },

     aftersavefunc: function(){
        // console.log(JSON.stringify($('#jq_grid').jqGrid('getGridParam', 'data')));
        // in cell, new-data is displayed, but  in data, it is still old-data 
        // so now change the internal local data
         var a_data  = $('#jq_grid').jqGrid('getGridParam', 'data')  ;         // reference to internal array of object ?
         var a_index = $('#jq_grid').jqGrid('getGridParam', '_index');
         var row_id = $("#jq_grid").jqGrid('getGridParam', "selrow" );      // get row_id
         var o_new_row = $("#jq_grid").jqGrid('getRowData', row_id) ;    // get new-data
        //  console.log(JSON.stringify(o_new_row));                   
          a_data[a_index[row_id]] = o_new_row ;                                      // replace with edited-row 
         var a_total_data = $('#jq_grid').jqGrid('getGridParam', 'data') ;  //
        //  console.log(JSON.stringify(a_total_data));                                // ok, it is replaced with new-data  
       }
    }

// but after page navigation , old-data appear, (before-edit-data)  
// while newly added data remains  in new-data  with page-navigation 
// and when edited , this  remains  in new-data 
// summary :
//  insert is ok, but edit  has problem with  local-data-editing 
//  is this bug ?  or something wrong with me ?

**Comment by OlegKi** [comment] 2017-07-13 05:25
Please provide **the demo** (in jsfiddle for example), which can be used to reproduce the problem. I can help you only if I can reproduce the problem. Currently it's unclear which versions you use in your tests.

The code of `aftersavefunc`  seems me absolutely wrong. jqGrid **automatically** modify local data. `"clientArray"` is default value of `editurl`. No additional `aftersavefunc` is required to edit local data.

Try the demo https://jsfiddle.net/uo17vrex/, which is simple modification of the first demo from [the page](https://free-jqgrid.github.io/getting-started/index.html). You can easy verify that one can edit the data on one page, switch to another page, go back to the first page and the modified data still be saved.

**Comment by alpastar** [comment] 2017-07-13 06:57
OK, and thank you for your response,
struggling  on this issue for 3 days .... 

ver. = free-jqGrid 4.14.1 
 ->  "https://cdnjs.cloudflare.com/ajax/libs/free-jqgrid/4.14.1/jquery.jqgrid.min.js"

situation :
load (local)excel file -> convert into csv ->convert into json (array-of-object)
automatically by go_xport (object)
final  data is stored in go_xport.a_jq_data .

in GUI , everything is OK (add,delete,update)
for more accurate analysis, i dump  data  on every add,delete,edit(console.log)  
add  :  GUI: ok,   [data]:OK ,  record  increase, and changed data displayed, and remains in changed state
delete : GUI:ok, record decrease , [data]:  still present
edit : GUI:ok,    [data]: still old-data  

im afraid that my program is  somewhat long , two complicated with my own library,
and includes many korean letters
so, uploading to jsfiddle to reproduce the problem is not easy thing.

anyhow, i will try a few days more, 
and then i will provide  you  the result and code  regardless of my success.

**Comment by alpastar** [comment] 2017-07-13 10:55
found !!! ,  and   reproduced !!! 
   https://jsfiddle.net/alpastar/99hfgbzm/


if  i  assign  no key in colModel , the problem disappear 
if  i assign  key in colModel ,  and  no-assign loadonce,  then the  problem disappear 

conclusion:
 assigned  key in colModel, and loadonce:true , then the weird behaviour occurs 

Q) 
 if  i assign  no key in colModel , then  id column  is (auto)created (in data) 
and  managed  by  jqGrid ??

**Comment by OlegKi** [comment] 2017-07-13 20:08
Thank you for the bug report and providing the demo, which reproduce the problem!

Your code uses **wrong combination of jqGrid parameters**: you use `loadonce: true` in the grid, which input data come from the input `data` parameter. You use `datatype: "local"`, input data in `data` and `loadonce: true`. The option `loadonce: true` is introduced for the case of loading the data **from the server**. For example, you use `url: "someUrl", datatype: "json", loadonce: true`. It means that jqGrid should load the data from `url: "someUrl"` and *after that* it changes `datatype: "json"` to `datatype: "json"`. The `data` option will be filled during processing of the server response and then the `datatype` will be changed from initial `"json"` (`"xml"` or `"jsonp"`) to `"local"`. Some parts of code of jqGrid tests that `datatype` is `"local"` **and** `loadonce: true` to detect the case that the data are loaded from the server and not directly from `data` input parameter.

Nevertheless, if you used wrong jqGrid options, then other developers could do the same error. I'll try to analyse the source code and fix all placed, which I described above. I found currently only [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.14.1/js/grid.base.js#L3761)
```JavaScript
if (p.keyName === false || p.loadonce) {
```
inside of `refreshIndex`. The like could be changed to
```JavaScript
if (p.keyName === false || (p.loadonce && p.dataTypeOrg)) {
```
for example. I'm not sure that it's the only place, which should be changed. I need to analyse the code more deep. Probably I'll just change the code to test the input parameter and to overwrite `loadonce` to `false` if `datatype` is `"local"` at the time of creating the grid.

**Comment by OlegKi** [comment] 2017-07-16 17:01
@alpastar : Please, try the latest code of free jqGrid from GitHub. The problem seems to be fixed now. At least your demo, but with loading the latest sources, https://jsfiddle.net/OlegKi/99hfgbzm/4/ don't have the problem. Please close the issue after confirming that the problem is solved.

I still don't recommend you to use wrong option `loadonce: true` with the local data.

**Comment by OlegKi** [comment] 2017-07-23 11:08
@alpastar  I don't get any answer from you during the last week. Thus I'm closing the issue now. In my opinion the bug, which you reported, should be fixed now. You can reopen the issue later if you'll get a new information about the subject.

**Closed by OlegKi** 2017-07-23 11:08 UTC
Labels: bug
