### ISSUE TITLE
Subgrid column disappears 

### ISSUE THREAD

**Issue by bolzo5** [free-jqgrid/jqGrid#387] opened 2017-10-18 10:44 UTC
Hi Oleg,
I'm having problem creating a grid following your example.
http://www.ok-soft-gmbh.com/jqGrid/OK/hasSubrgid.htm

It works great until I try to filter a column after having opened a subgrid, using:
$gridName.jqGrid("filterToolbar", { stringResult: true, searchOnEnter: true, defaultSearch: "cn" });

The filter works,  but if I have opened a subgrid earlier( even if I already closed it) the subgrid value ( the plus sign) disappears and all my data gets shifted one column to the left.

If I filter before opening anything,  there are no problems and applying and removing filtering works just until I open the subgrid.

I'm trying to replicate this behaviour on a jsFiddle, I'll post it as soon as I can.
I think this behaviour is related to the colmodel not having the subgrid column definition, but I don't understand why and where the subgrid value gets discarded.

Thank you in advance

**Comment by OlegKi** [comment] 2017-10-18 11:06
Sorry, but I really need to have **the demo** with the test case (step by step description how to reproduce the problem inclusive expected results and what one see instead). If I just copy the code of the demo in the jsfiddle and add call of `filterToolbar` I'll get the demo https://jsfiddle.net/OlegKi/0yws4s7c/, where I can't reproduce any problem. Please modify the demo so that the problem could be reproduced.

**Comment by OlegKi** [comment] 2017-10-25 14:56
@bolzo5 Please, send me more details about the problem (see my previous comment) or close the issue.

**Closed** 2017-10-31 10:26 UTC
