### ISSUE TITLE
Issues in version 4.15.0 with method "selarrow"

### ISSUE THREAD

**Issue by reypm** [free-jqgrid/jqGrid#374] opened 2017-09-20 15:39 UTC
Yesterday I did an upgrade to the library from `4.14.1` to `4.15.0` and I start having bugs with my application.

What's is the bug? For some reason the method `.jqGrid('getGridParam', 'selarrrow')` stopped working and even with selected items it still returned `0` as the length of the Array. After read once and again mine Javascript code and found no changes at all then I decided to downgrade the library to it's previous version and "voila" everything started working again.

See the code below which works in 4.14.1 but does not work in 4.15.0:

```javascript
var $content_pane = $('#content_pane');

$content_pane.on('click', '#create_quote', function (ev) {
    var grid_customer = $('#grid_customer');
    var selIds = grid_customer.jqGrid('getGridParam', 'selarrrow');
    var create_quote_dialog = $('#create_quote_dialog');

    if (selIds.length > 0) {
        alert(selIds);
    } else {
        alert('You must select at least one item.');
    }
 });
```

Maybe is a bug maybe something has changed between versions but still not documented (I'm not seeing any README file for version 4.15.0).

Could you confirm this?

**Comment by OlegKi** [comment] 2017-09-21 05:33
Could you provide **the demo**, which reproduces the problem? I tried myself, but I don't see any problem. See https://jsfiddle.net/uapworoe/

**Comment by reypm** [comment] 2017-09-21 12:05
@OlegKi provide a demo is a little problematic for me since the code is depending on server side. Would provide you with the Javascript code works for you?

**Comment by OlegKi** [comment] 2017-09-21 12:41
@reypm Sorry, but I posed the demo in my previous comment. You can select some rows on the demo https://jsfiddle.net/uapworoe/ and click on "display multiselect ids" button. The `click` event handler is at the end on my code.

**Comment by reypm** [comment] 2017-09-25 14:03
@OlegKi ok, I was able to reproduce the issue [here](https://jsfiddle.net/reynierpm/Lr2tg6rL/1/) it's based on your previous demo but this one is failing

**Comment by OlegKi** [comment] 2017-09-25 23:28
@reypm Thank you for the demo. The problem was that I introduced new option `noCellSelection: true` in free jqGrid 4.15.0, which could be used in case of `cellEdit: true` and `multiselect: true`. The modified code worked incorrectly in your case, when `cellEdit: true` and `multiselect: true` were used, but without `noCellSelection: true`. I fixed the code now. See the demo https://jsfiddle.net/OlegKi/Lr2tg6rL/4/.

Please test the latest free jqGrid code. I hope it works now as expected.

**Comment by reypm** [comment] 2017-09-26 15:25
@OlegKi so far everything seems to be working fine and the issue is fixed now. When will you make a new release?

**Comment by OlegKi** [comment] 2017-09-26 17:32
I'm waiting for some other feedbacks and plan to publish 4.15.1 at the end of the week (or the month).

**Comment by OlegKi** [comment] 2017-09-27 13:41
I'm closing the issue it you can't reproduce any problems in free jqGrid after applying [the fix](https://github.com/free-jqgrid/jqGrid/commit/2d9956f5cd5dec4abbb4cb433b7daf833b4fe851).

**Closed by OlegKi** 2017-09-27 13:41 UTC
Labels: bug
