### ISSUE TITLE
Wrong position of resize line (vertical line)

### ISSUE THREAD

**Issue by gspansky** [free-jqgrid/jqGrid#249] opened 2016-07-06 07:36 UTC
Hi! 

I have a problem with resizing columns. When I press the button on column header to resize it's width, then resize vertical line appears at a certain distance from my cursor. Is there any way to repair this strange issue? I want to make resize line appear in the same position as mouse cursor.

This StackOverflow question illustrates problem, which occurs also in free-jqgrid: 
http://stackoverflow.com/questions/14638922/jqgrid-drag-line-issue

**Comment by OlegKi** [comment] 2016-07-06 07:51
The old question on the stackoverflow, which you references, is about *old version of jqGrid* 4.4.4. You should write always which version of free jqGrid you use and to provide the demo, which can be used to reproduce the problem. You should describe more clear which web browser and in which version you used to reproduce the reported problem. I tested on [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/formEditOnDoubleClick-jqueryui-fa3.htm), which uses free jqGrid 4.13.3, in Chrome 51, Chrome 52 beta (52.0.2743.60 beta-m (64-bit)), Chrome 54 canary beta (54.0.2789.0 canary (64-bit)) and I can't see any problems in any from the web browsers like of Firefox (v47 or v48.0b5), IE11 or Microsoft Edge.

Please provide more exact information about the reported problem.

**Comment by gspansky** [comment] 2016-07-07 18:24
Ok, my free-Grid version is: jqGrid 4.13.2. Browser: Firefox v.47.0, Chrome v.51.0.2704.103 m.

The problem was, that vertical line, which appears on drag change column width operaton was in another place, than my dragged mouse was. I' ve studied jqGrid code, and I found dragStart() function, which has line like: 
`                 startX = $th.offset().left + (p.direction === "rtl" ? 0 : self.headers[i].width + (jgrid.cell_width ? 0 : intNum(p.cellLayout, 0)) - 2);
` 

As I can see, this function get actual left column border position and add some calculated width to it (what is that calculated extra widht?). But the problem is, that we can only catch the right border of the column to perform change width operation. So why drag vertical line (with 'ui-jqgrid-resize-mark' class) is calculated from left side, instead of get right column border position, or mouse position? 

I've changed this line to this, and my problem has gone: 
`startX = x.clientX; `

Now vertical column resize drag line is exactly above my mouse cursor, which solves my problem. 
But Im still really curious why do you calculate drag line position from the left column border instead of right border? And what is that extra calculated width?

`    + (p.direction === "rtl" ? 0 : self.headers[i].width + (jgrid.cell_width ? 0 : intNum(p.cellLayout, 0)) - 2);
`

**Comment by OlegKi** [comment] 2016-07-07 19:58
Sorry, but **the demo**, which uses non-minimized version of free jqGrid, and which works incorrect is **really required**. I see no sense to discuss the lines of `dragStart` function. I have to analyse exactly the demo and debug it.

**Comment by OlegKi** [comment] 2016-07-14 16:47
Please provide the demo, which can be used to reproduce the problem or close the issue.

**Comment by OlegKi** [comment] 2016-07-21 11:02
I didn't get any demo from you since a week. I'm closing the issue now. You can reopen it later if you will post the demo or enough information, which allows me to reproduce the problem.

**Closed by OlegKi** 2016-07-21 11:02 UTC
