### ISSUE TITLE
Modal and validation error messages are not placed correctly

### ISSUE THREAD

**Issue by afattahi54** [free-jqgrid/jqGrid#278] opened 2016-12-05 13:19 UTC
We are using jqGrid 4.13.5, in IE and Chrome, the client side validation modal does not place correctly. In Firefox it works correct. ( I have tested with 4.13.6-pre and still see the error)

We are using the grid in RTL mode, and the body `dir` css is set to `rtl`. When I remove the body dir style the modal and errors are placed correctly !

Please see screen shots.
![chrome-add-stick-to-right](https://cloud.githubusercontent.com/assets/5003703/20886262/7f545240-bb0a-11e6-8d6d-8d6794fbf62a.png)
![chrome-add-under-problem](https://cloud.githubusercontent.com/assets/5003703/20886260/7f4dee82-bb0a-11e6-8c8f-6531417edb92.png)
![chrome-alert](https://cloud.githubusercontent.com/assets/5003703/20886261/7f4f5344-bb0a-11e6-8ccb-fb5070e4c386.png)

**Comment by OlegKi** [comment] 2016-12-07 13:03
Thank you for the bug report! The reason of the problem seems to me [the line](https://github.com/twbs/bootstrap/blob/v3.3.7/less/modals.less#L21) of Bootstrap.css, which contains `.modal { right: 0; }`.

I posted some changes to GitHup, which includes [the commit](https://github.com/free-jqgrid/jqGrid/commit/c189197fac535394c2c7b133dd026641472265b3). Please test the latest code of free jqGrid and inform me whether the problem is fixed now.

**Comment by afattahi54** [comment] 2016-12-09 09:14
Dear Oleg, thanks, it is now correct in Chrome and IE !

**Comment by OlegKi** [comment] 2016-12-09 14:38
Thanks for the feedback! It seems that the problem is solved now, thus I close the issue.

**Closed by OlegKi** 2016-12-09 14:38 UTC
Labels: bug
