### ISSUE TITLE
a bug in the jquery.jqgrid.src.js row 9078

### ISSUE THREAD

**Issue by jinchunhe** [free-jqgrid/jqGrid#159] opened 2015-10-23 02:04 UTC
```javascript
grid.fsDiv = $('<div style="position:absolute;" + (p.direction === "rtl" ? "right:0;" : "left:0;") + "top:' + (parseInt(top, 10) + parseInt(hth, 10) + parseInt(hbd, 10) + 1) + 'px;" class="frozen-sdiv ui-jqgrid-sdiv"></div>');
```
fix:
```javascript
grid.fsDiv = $('<div style="position:absolute;' + (p.direction === "rtl" ? "right:0;" : "left:0;") + 'top:' + (parseInt(top, 10) + parseInt(hth, 10) + parseInt(hbd, 10) + 1) + 'px;" class="frozen-sdiv ui-jqgrid-sdiv"></div>');
```

**Comment by OlegKi** [comment] 2015-10-23 05:09
Sorry, but could you **describe** the problem, which you report? The screenshot could be helpful too. Moreover the line from the "fix" part of your suggestion looks exactly like the original line. What kind of fix you suggest?

**Comment by jinchunhe** [comment] 2015-10-23 06:37
![qqcapture_20151023143608](https://cloud.githubusercontent.com/assets/12995757/10686111/7e5cb65c-7993-11e5-994b-338f725c8bab.jpg)

**Comment by OlegKi** [comment] 2015-10-23 06:49
Thank you! I see the problem now. I will fix it.

**Comment by OlegKi** [comment] 2015-10-23 07:59
I posted [the bug fix](https://github.com/free-jqgrid/jqGrid/commit/a96653707022187b39dd3c4c2aae183aa48640c0) together with [other changes](https://github.com/free-jqgrid/jqGrid/commit/d056a688a3d92b0e4ad36f67027b5c9958fbbe01), which improves the performance of frozen columns.

Please test the latest code and close the issue if you confirm that the problem is solved now.

Thanks you once more for reporting the bug.

**Closed** 2015-10-23 09:13 UTC
Labels: bug

**Comment by fletchsod-developer** [comment] 2015-10-23 10:48
They both looks the same to me.  Was there something that should look
different with those written post?

**Comment by OlegKi** [comment] 2015-10-23 12:00
@fletchsod-developer: please express yourself mare clear. What "looks the same"? The old code had wrong quotes. As the result the part of the code (like `(p.direction === "rtl"`) was interpreted as the string which inserted on HTML page. The new code fix the bug.

The details about the performance improvements are described in [the changes](https://github.com/free-jqgrid/jqGrid/commit/d056a688a3d92b0e4ad36f67027b5c9958fbbe01) which I referenced in my previous comment.  It was described [here](https://github.com/free-jqgrid/jqGrid/pull/157) width demos which reproduce an measure the performance in the old code. See [the demo](http://jsfiddle.net/OlegKi/e3ouywqs/6/) uses jqGrid 4.9.2 and the performance of **expending/collapsing** the groups is much slowly as in [the demo](http://jsfiddle.net/OlegKi/e3ouywqs/4/) which use the new code from GitHib. If you would increase the number of generated rows (in the line `gridData = getGridData(100);` replace 100 to 1000 for example) then the differences will be even more clear.

**Comment by fletchsod-developer** [comment] 2015-10-23 12:11
Disregard this..  I was only trying to help.   It was Gmail that only showed this & I replied back on it.

     grid.fsDiv = $('
     ');

     fix:
     grid.fsDiv = $('
     ');
