### ISSUE TITLE
request: press F2 key to inline editing?

### ISSUE THREAD

**Issue by aberel** [free-jqgrid/jqGrid#359] opened 2017-08-08 11:37 UTC
Is there any way or method in jqGrid to activate F2 key for inline-editing a row (just like Windows F2). 
I would like the user can select a row and then hitting F2 key should act same way as EDIT button. (this will not replace the standard dblClick or pager Edit button)

My version is Free jqGrid 4.13.7-pre

Thanks!
(same question in https://stackoverflow.com/questions/45527144/jqgrid-f2-key-to-activate-inline-editing )

**Comment by OlegKi** [comment] 2017-08-09 10:36
Sorry, but I'm really busy last time. I see that your question is already answer. It contains practically the same information, which I could suggest you. I hope that the problem is solved now. Please close the issue in the case.

**Closed** 2017-08-09 10:45 UTC
