### ISSUE TITLE
Bug with posting non-editable cols when formatter is 'date'

### ISSUE THREAD

**Issue by iRostik** [free-jqgrid/jqGrid#378] opened 2017-09-25 09:09 UTC
I set field in colModel:
`{name:'date_begin', formatter:date, editable: false}`
But when i look in profiler data, i see my field in postdata.
It happens, because function 'setNullsOrUnformat' sets field value:
```
if (cm.formatter === "date" && (cm.formatoptions == null || cm.formatoptions.sendFormatted !== true)) {
	// TODO: call all other predefined formatters!!! Not only formatter: "date" have the problem.
	// Floating point separator for example
	postdata[cmName] = $.unformat.date.call($t, value, cm);
}
```

I think, it required to loop throw postdata, not all colModel in upper block:
`$.each(colModel, function (i, cm) {`

**Comment by OlegKi** [comment] 2017-09-25 09:59
@iRostik: Спасибо, Ростислав! Thank you for the bug report. I posted the corresponding fix to GitHub. Please, verify that the problem is fixed now.

**Comment by OlegKi** [comment] 2017-09-30 13:45
@iRostik: I don't get any feedback from your during some days. I suppose that the problem is fixed now after committing [the fix](https://github.com/free-jqgrid/jqGrid/commit/b013350a3218f66efeb5fed4ca07749b276c6ff3) and I close the issue. You can reopen it at any time later if you find any problem.

**Closed by OlegKi** 2017-09-30 13:45 UTC
Labels: bug
