### ISSUE TITLE
TypeError: Failed to execute 'replaceChild' on 'Node': parameter 2 is not of type 'Node'.

### ISSUE THREAD

**Issue by Mike-Benoit** [free-jqgrid/jqGrid#458] opened 2018-10-29 20:48 UTC
We track all JS exceptions that are triggered and we are seeing the following exception quite a bit (10-20x per day) when clearing a grid and reloading its data. The offending code seems pretty deep in the JQGrid though:

TypeError: Failed to execute 'replaceChild' on 'Node': parameter 2 is not of type 'Node'.
    at a (.../jqgrid/jquery.jqgrid.min.js:10:114065)
    at HTMLTableElement.emptyRows (.../jqgrid/jquery.jqgrid.min.js:10:114271)
    at HTMLTableElement.<anonymous> (.../jqgrid/jquery.jqgrid.min.js:10:142011)
    at Function.each (.../jquery.min.js:2:2573)
    at w.fn.init.each (.../jquery.min.js:2:1240)
    at w.fn.init.clearGridData (.../jqgrid/jquery.jqgrid.min.js:10:141881)
    at w.fn.init.$.fn.jqGrid (.../jqgrid/jquery.jqgrid.min.js:10:46723)
    at MyGrid.clearGridData (...)

Unfortunately we aren't able to reproduce it reliably and therefore can't get a unminified stack trace. 

Any ideas what may be causing it or if we can avoid this exception somehow?

Using free jqGrid v4.15.5.

**Comment by cunnpole** [comment] 2018-10-30 14:16
I wonder if this is related to the issue I am seeing. I get exceptions on the next line (3737 on the latest commit) if the returned results are empty. When emptyRows is called the tableRows are empty and therefore firstrow is undefined. Do you know what your last stable release was? I'm in the process of porting from Tony's version so I don't have a benchmark for free-jqgrid.

**Comment by OlegKi** [comment] 2018-10-30 20:36
Please send information, which will be **enough to reproduce the problem**. For example, you can send the demo (in JSFiddle), which reproduces the problem. Currently I have now no idea what you do in your code and how you use jqGrid at all (simple grid, grouping, TreeGrid and so on).

Please use always `jquery.jqgrid.src.js` instead of `jquery.jqgrid.min.js` during reporting a problem.

By the way, explicit call of `clearGridData` is not requited if you reload the grid.

@cunnpole : The same for you. If you want to report a problem, please provide **the demo**, which reproduce the problem. If the problem will not take place after opening the demo, please describe step by step instruction, which one should do to reproduce the problem. Many problems exist because of wrong usage of jqGrid. I can't help you to solve a problem if I don't see your JavaScript code and I can't reproduce the problem.

**Comment by OlegKi** [comment] 2019-02-10 21:15
I'm closing the issue because you didn't posted any additional information. You can reopen the issue if you'll want to post information which allows me to reproduce your problem.

**Closed by OlegKi** 2019-02-10 21:15 UTC

**Comment by Mike-Benoit** [comment] 2019-02-15 20:21
We finally were able to replicate it in our app when the user double clicks a button which is supposed to popup a div with a grid in it, causing it to try and load twice. This grid then has to reach out to a server to load its data asynchronously, so it appears to be some kind of race condition with two grids being loaded/populated with data around the same time.

On line 3737 of query.jqgrid.min.js if we add: "if (!table.tBodies[0]) { return; } ", (See below example) it works around the exception, but causes another exception around line 4316 because "self.rows[0]" doesn't exist. 

We're still looking into it more, as I'm not sure its a jqgrid problem itself, but it would be nice if jqgrid could handle it more gracefully somehow. 


```
 emptyRows = function (scroll, locdata) {
                                       var self = this, bDiv = grid.bDiv,
                                               frozenTable = grid.fbDiv != null ?
                                                       grid.fbDiv.children(".ui-jqgrid-btable")[0] : null,
                                               removeRows = function (table) {
                                                       if (!table) { return; }

                                                       var tableRows = table.rows, firstrow = tableRows[0];
                                                       if (p.deepempty) {
                                                               if (tableRows) { $(tableRows).slice(1).remove(); }
                                                       } else if (p.quickEmpty) {
                                                               if (p.quickEmpty === "quickest") {
                                                                       if (!table.tBodies[0]) { return; } 
                                                                       table.replaceChild(document.createElement("tbody"), table.tBodies[0]);
                                                                       table.firstChild.appendChild(firstrow);
                                                               } else {
                                                                       while (tableRows.length > 1) { // skip deliting of the first row
                                                                               table.deleteRow(tableRows.length - 1);
                                                                       }
                                                               }
                                                       } else {
                                                               $(table.firstChild).empty().append(firstrow);
                                                       }
                                               };
```

**Comment by OlegKi** [comment] 2019-02-15 20:56
Sorry, but your last post still contains too few information. Which version of free jqGrid you use? How you use jqGrid? (simple grid, TreeGrid, Data Grouping etc). You should post **the demo** with test data, which can be used to reproduce the problem, which you report. At least I could have some imagine how you use jqGrid. Which web browser and in which version you use? I know problems with `table.tBodies` only in case of usage some very old versions of Internet Explorer.

I use jqGrid myself since very long time and I can't remind that I used `clearGridData`. In any way, if you use `clearGridData` and you have some problem with `table.tBodies[0]` then you can add the option `quickEmpty: true` or `quickEmpty: false` instead of using default option `quickEmpty: "quickest"`. I suppose that it should solve your problem.

**Comment by Mike-Benoit** [comment] 2019-02-20 20:01
We're seeing the issue on all modern browsers, but mostly Chrome v71. We don't support IE versions less than 11, so it definitely isn't an old browser issue.

Because it does appear to be a race condition of some sort, we have yet to be able to replicate it in a jsfiddle, but are still trying.

Can you think of any situations where table.tBodies[0] would not exist when emptyRows() is called?

**Comment by Mike-Benoit** [comment] 2019-02-21 00:20
Several places recommend that when reloading data in an existing grid (ie: pull fresh data from a server), to do this:

jQuery('#grid').jqGrid('clearGridData');
jQuery('#grid').jqGrid('setGridParam', {data: dataToLoad});
jQuery('#grid').trigger('reloadGrid');

That is what we do in most cases, but in your previous comment you say clearGridData() should not be called at all? 

If we don't call clearGridData first, then the grid data gets merged with old data and the results are incorrect. For example if you are showing 10 records, then run a search to only show 1 record, it still shows 10 records, with the first record being the search result.
