### ISSUE TITLE
Some attributes in editparameters don't do what they're supposed to

### ISSUE THREAD

**Issue by arsalankhalid** [free-jqgrid/jqGrid#180] opened 2015-12-01 20:11 UTC
For example :

 var editparameters = {
        "keys": true,
        "oneditfunc": null,
        "successfunc": null,
        "url": '.' + $scope.gridName + '/update',
        "extraparam": {
          businessDate: DataService.getSelectedDate,
          snId: rowData.snId,
          code: rowData.Code
        },
        "aftersavefunc": alert("test"),
        "errorfunc": generateNonNumericErrorMsg("Current Rate", cellcontent),
        "afterrestorefunc": alert("test"),
        "beforeEditRow": alert("test"),
        "restoreAfterError": alert("test"),
        "mtype": "POST"
      };

      $grid.jqGrid('editRow',rowid, editparameters);
    }

Aftersavefunc, errorfunc, afterrestorefunc, beforeEditRow, and restoreAfterError are ALL only invoked after only simply CLICKING on a cell, rather than do what they're supposed to do. I.e restoring after an error, aftersaving etc. I confirmed this by identifying when the alerts are invoked. You can probably re-create this locally. Also just as a note, this editRow call is done within an onCellSelect in ColModel.

Thanks!

**Comment by OlegKi** [comment] 2015-12-01 21:02
Sorry, but you wrote wrong code. For example
```JavaScript
var editparameters = {
        "url": '.' + $scope.gridName + '/update',
        "aftersavefunc": alert("test"),
        ...
    };
```
means creating the object and initialize there. The values of both `url` and `aftersavefunc` will be initialized to the expressions. The expression `'.' + $scope.gridName + '/update'` will be calculates and the result value will be assigned as the value of of `url` property. In the same way the expression `alert("test")` will be calculated *during initializing of the object* and the result of working `alert("test")` (probably `undefined`) will be assigned to the property `aftersavefunc`. You don't assign any callback function in such way.

What you should to do is something like
```JavaScript
var editparameters = {
        url: '.' + $scope.gridName + '/update',
        aftersavefunc: function () { alert("test") },
        ...
    };
```

**Comment by arsalankhalid** [comment] 2015-12-01 21:06
It's funny that you mention this because I tried exactly what you just mentioned after I posted this issue. I didn't entirely understand why it was working but you've given a clear explanation now, thank you! Apologies for posting an incorrect request. 

Since I have your attention however, I was curious as to why the editparameters object expected different attributes than the edit property? For example:

editparameters expects: 
editparameters = {
	"keys" : false,
	"oneditfunc" : null,
	"successfunc" : null,
	"url" : null,
        "extraparam" : {},
	"aftersavefunc" : null,
	"errorfunc": null,
	"afterrestorefunc" : null,
	"restoreAfterError" : true,
	"mtype" : "POST"
}

and the edit object expects: 

http://www.trirand.com/jqgridwiki/doku.php?id=wiki:form_editing

Things like beforeSubmit/afterEdit or beforeSave would be incredibly useful! I was looking for an attribute that would specifically allow me to validate what I have edited before a POST was sent out. But that doesn't seem possible with the inline edit!

Thanks for the quick response Oleg.

**Comment by OlegKi** [comment] 2015-12-01 21:28
jqGrid support three [editing modes](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:jqgriddocs#editing): inline editing, form editing and cell editing. `editparameters` which you posted specify the options of **inline editing**. To be exactly it's the options of [editRow](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:inline_editing#editrow) method which you call directly with `editparameters` parameter or which will be called indirectly, by `formatter: "actions"`,  `inlineNav` ... See [the wiki](https://github.com/free-jqgrid/jqGrid/wiki/New-style-of-usage-options-of-internal-methods), which provides example of usage and the new possibility, which can be used in free jqGrid.

**Comment by arsalankhalid** [comment] 2015-12-01 21:29
But how come the three editing modes have different options, wouldn't them being the same be ideal?

**Comment by OlegKi** [comment] 2015-12-01 21:46
Free jqGrid try to hold **compatibility with the previous versions of jqGrid**. One implemented *before me* absolutely independent modules with 3 different editing modes. I understand that the fact is not comfortable for  the newcomer, but the compatibility with the previous versions is very important.

**Comment by OlegKi** [comment] 2015-12-18 09:01
I hope that the question asked in the issue is cleared and I close the issue. You can reopen it on any time later or to post new issue.

**Closed by OlegKi** 2015-12-18 09:01 UTC
