### ISSUE TITLE
Check All doesn't maintain its status after scrolling in infinite grid.. 

### ISSUE THREAD

**Issue by rajeshks117** [free-jqgrid/jqGrid#121] opened 2015-07-21 02:41 UTC
Check All doesn't maintain its status after scrolling in infinite grid.. If you will unselect one row,  it will unselect the check All check-box and later there is no option to click unselect all.

I think check all check-box should have three state.

**Comment by OlegKi** [comment] 2015-07-21 08:22
Sorry, but I don't understand the problem. You use for example terminology like "infinite grid" which is unclear. Could you describe the issue more detailed and to include JavaScript code which shows what you do. The best would be if you post URL to the demo and include the test case which contains step by step instructions to reproduce the problem including expecting results and the results which one have instead.

**Comment by rajeshks117** [comment] 2015-07-21 13:41
Thank Oleg for responding. Look at this example some has posted.
http://www.guriddo.net/demo/guriddojs/loading_data/scrollmulti/

1st issue:- If you will click select all checkbox and scroll forward and backward then it doesn't maintain the checkbox status.
2nd Issue:- If you unselect any checkbox then check all button is unchecked. It should go to some partial select option. Look at your gmail inbox and try to select all and then uncheck one of your email. The select all will go to partial select state.

**Comment by OlegKi** [comment] 2015-07-21 16:32
OK, you mean virtual scrolling under "infinite grid".

I personally don't like the current implementation of the feature in jqGrid. It has many restrictions, many limitations and a lot of misunderstandnesses. I personally never use it and recommend everybody don't use it if the feature really don't required in the project.

About "select all" checkboxes. jqGrid don't support any "selection state" **over the pages**. So if you select some rows on one page, go to the next page and then returns back to the previously page you will don't have selected rows which you have selected before. Virtual scrolling do mostly the same as paging, so it have close restrictions. There are some important difference in case of usage `scroll: true` and `scroll: 1`. You didn't wrote which option you use.

Gmail for example have some implementation of selection which good in using with email, but which could be not good with other objects. For example if you have many emails in the postbox and choose "select all" then only **all mails from the current page** will be selected. Gmail supports selection over the pages (one can make selection on one page, go to the next page, then returns to the previous one and to see the same rows selected), but "select all" will be interpreted not as select all mails over all pages.

You can implement *any behavior* which you need for selection. I posted many examples on the stackoverflow about this. See [the old demo](http://www.ok-soft-gmbh.com/jqGrid/ColumnChooserAndLocalStorage2_.htm) created for [the answer](http://stackoverflow.com/a/8547852/315935) for example. I think that you can use almost the same code for virtual scrolling too.

The problem is just the usage of some behavior in jqGrid out of the box. Especially the case of virtual scrolling needed be rewritten in many places. I didn't found fill now the time for it. Sorry.

**Comment by OlegKi** [comment] 2016-07-24 11:28
I think, that the issue could be closed. The specific of virtual scrolling implementation (`scroll: 1` or `scroll: true`) don't provide an easy way to improve the behavior. There are different possibilities, but there should be considered in exact implementation context.

**Closed by OlegKi** 2016-07-24 11:28 UTC
