### ISSUE TITLE
Group name in summary row

### ISSUE THREAD

**Issue by Luca7993** [free-jqgrid/jqGrid#232] opened 2016-05-17 11:18 UTC
Hi,
I would like to insert the Group value in a column in the summary row.
something like this
![image](https://cloud.githubusercontent.com/assets/1061695/15320444/dc8061c6-1c30-11e6-826e-d7ac2a636d78.png)
for example, in one column I want to insert in summarytpl something like "Total {groupvalue}" and after in buildsummarytd function the value "{groupvalue}" would be automatically substitute the value (using also formatting).

another solution is to edit the function buildsummarytd from 
`if (cm.summaryFormat) {
								tmpdata = cm.summaryFormat.call($t, g, tmpdata, vv, cm);
							}`

in 
`if (cm.summaryFormat) {
								tmpdata = cm.summaryFormat.call($t, g, tmpdata, vv, cm, summary);
							}`

so when I use summaryFormat in colModel, I can use summary.groupValue

thank you!
Luca

**Comment by OlegKi** [comment] 2016-05-17 19:09
Thank you Luca for the suggestion! I find adding of `summary` as an additional parameter of `summaryFormat` as a good idea and made [the corresponding changes](https://github.com/free-jqgrid/jqGrid/commit/4af116c296611a59744a6e48e43802d4e4813fe4).

I recommend you to look at [the issue](https://github.com/free-jqgrid/jqGrid/issues/227), which describes one more way to set custom value in the summary. [The code](http://www.ok-soft-gmbh.com/jqGrid/OK/my-app-src1.js) used in [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/grouping2-requirejs-src1.htm) demonstrates the possibility.

I close the issue. Please confirm that the problem is solved now. You can reopen the issue any time if you will.

**Closed by OlegKi** 2016-05-17 19:09 UTC
