### ISSUE TITLE
NavGrid doesn't respect columns searchoptions, searchOnEnter, clearSearch

### ISSUE THREAD

**Issue by acidofil** [free-jqgrid/jqGrid#323] opened 2017-04-21 21:35 UTC
Hello,

first let me thank you for a great fork. I have few problems/notices regarding navGrid / searching.

1. notice - when I make a search request to the server **filterToolbar** sends this data:

"&searchString=&inputtextname=MySearchString"

BUT **navGrid** sends 

'searchString=MySearchString&searchField=inputtextname'

I understand that anyone can solve this via backend, but its quite confusing.

2. problem - **navGrid** doesn't respect **clearSearch** option i.e. when I have this (example) in colModel

                    {name:'foo', label: 'bar', search: true, stype:'text', searchoptions: {
                        sopt: ['bw'],
                        clearSearch: false
                    }, title: false},

The **navGrid** dialog clears the input text after clicking **Search** button. So when I open the search dialog again the search string is gone. **searchOnEnter** option is another option which isn't working, I have to press Search button instead (or make onkeyup/onchange events etc - mess).

Original jqgrids "clearSearch: false" or "searchOnEnter: true" directly used in Free-jqgrids options root also isn't working.

thank you very much and have a nice weekend ;)

**Comment by OlegKi** [comment] 2017-04-23 18:03
Hi!

It would be helpful if you would post always small code fragments, which shows how you use jqGrid or better to post small demo, which demonstrates the problem. Please write additionally, which version of jqGrid you use currently. The latest released version (4.14.0) is recommended/supported and the latest source from GitHub.

jqGrid implements two parts of server side searing: with respect of `filterToolbar` and with respect of `searchGrid` (used by `navGrid`). Both of the methods contains **two ways of formatting the parameters**, which will be send to the server. The *legacy* mode of `filterToolbar` means sending searching parameters in the form `columnIndexOrName=value`. Such format don't allow to specify any searching operation and one means "equal" operation. Multiple parameters (filters in multiple columns) can be sent. The legacy mode of `searchGrid` means sending **one** searching parameter in the form of 3 parameters: `searchField=columnIndexOrName`, `searchString=value` and `searchOper=op`, where `op` is one from the strings defined in `sopt` array of the column. Later, both `filterToolbar` and `searchGrid` begun support of *new format*, which is recommended to use. One can use `stringResult: true` option of `filterToolbar` to activate the mode and `multipleSearch: true` option of the `searchGrid`. The most general (extended) format of searching will be activated in `searchGrid` by usage two options: `multipleSearch: true` and `multipleGroup: true`. The resulting format is described [here](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:advanced_searching#options). By the way, `filterToolbar` supports the option `searchOperators: true`, which allow to choose searching operation in every column of the filter toolbar. After activating the new mode jqGrid sends the full information about searching/filtering as *one* `filters` parameter. Its value is JSON encoded filter.

One can use `searching` *parameter of jqGrid* to specify default options used by both `filterToolbar` and `searchGrid`. The recommended settings are:
```JavaScript
searching: {
    stringResult: true,
    searchOperators: true,
    defaultSearch: "cn",
    multipleSearch: true,
    multipleGroup: true,
    searchOnEnter: true,
    closeOnEscape: true,
    closeAfterSearch: true,
    closeAfterReset: true
}
```
The oldest versions of jqGrid (till 3.7) had no support of local data and no client side sorting/searching. Later versions support local searching, but local searching uses **only the new searching format**: the `filters` parameter. Because of that one don't need to specify `stringResult: true` in case of usage `datatype: "local"`.

About "problem 2". I suppose that you use `searchOnEnter: true` on the wrong place. Recommended way to specify searching parameter is the usage of `searching` option. Try the demo https://jsfiddle.net/OlegKi/yvbt6w54/1/ included in the README of free jqGrid 4.14.0. You will see that <kbd>Enter</kbd> key works correctly in free jqGrid.

Finally, the only goal of `clearSearch: false` is creating "x" button in the `filterToolbar`. It has no meaning for the searching dialog.

**Comment by acidofil** [comment] 2017-04-23 19:04
Hello, 

thanks a *lot* for an comprehensive and very helpful explanation! 

First point is clear now. Second point is basically explained in last part of your reply to point one. Everything works fine when I switch multipleSearch and multipleGroup to true = search text persists and even searchOnEnter works as expected. When set to false, neither of functions works.

**Comment by OlegKi** [comment] 2017-04-28 20:14
It seem that the problem is solved. I'm closing the issue. You can reopen it at any time or post new issue if you'll find new problems.

**Closed by OlegKi** 2017-04-28 20:14 UTC
