### ISSUE TITLE
UI calendar not close if add new record

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#298] opened 2017-03-12 13:16 UTC
From your example https://jsfiddle.net/OlegKi/yvbt6w54/ , if i add new record ,  after save calendar remains open. 

I do not think it is ok.

**Comment by OlegKi** [comment] 2017-03-12 20:01
Could you describe the test case exactly? The demo https://jsfiddle.net/OlegKi/yvbt6w54/ contains datepicker in the filter toolbar, which could be opened, there are two possibilities to ass new record: via inline editing and form editing. What shell I do in which order to reproduce the problem, which you try to report?

In any way it sounds like **an problem in the demo**, which code could be improved, and not like a bug in free jqGrid.

**Comment by davgino** [comment] 2017-03-13 07:16
When using the form editing.
After save record,  form is open and ui calendar from field Date it is opening.

**Comment by OlegKi** [comment] 2017-03-13 20:50
@davgino : I made some changes in the code (see [the commit](https://github.com/free-jqgrid/jqGrid/commit/de813d402cac7a292a63ac7066899cb99bedfbbb)). It seems that the problem is fixed now (see the same demo https://jsfiddle.net/OlegKi/yvbt6w54/, which uses the latest source of jqGrid from GitHub).

**Closed** 2017-03-14 08:18 UTC
