### ISSUE TITLE
Better Bootstrap support

### ISSUE THREAD

**Issue by Wooya** [free-jqgrid/jqGrid#176] opened 2015-11-17 09:33 UTC
Hi Oleg!

It would be nice if free-jqGrid has native Bootstrap support. Currently I'm using https://github.com/Soliman/jqGrid.bootstrap/blob/master/jqGrid.bootstrap.css and https://github.com/jquery-ui-bootstrap for Bootstrap look & feel, but when I'm including for ex. any Bootswatch theme, result looks weird.

**Comment by OlegKi** [comment] 2015-11-17 11:22
Sorry, Wooya, but you should understand that I develop free jqGrid in my free time and just share it with other for free. Even if you would send some feature request to Microsoft, Apple or some other large companies they have to find time of some employee who knows good your suggestion and who have time to implement the feature.

You wrote about "native Bootstrap support". I prepared it already, but I don't know Bootstrap CSS good enough to suggest the nice and flexible enough design of the tables using Bootstrap CSS, which I would suggest as *the standard Bootstrap implementation*. I could invest some days of my time to do this, but probably you can help here and send me more exact suggestions.

Free jqGrid have `guiStyles` option and the `"jQueryUI"` set of settings settings defined [here](https://github.com/free-jqgrid/jqGrid/blob/v4.10.0/js/grid.base.js#L489-L544). One can write
```JavaScript
$extend(true, $.jgrid.guiStyles, {
    myBootstrapSettings: {
        gBox: "...", // CSS classes which will be set on outer div of jqGrid
        overlay: "...", // CSS used for overlay visible during Ajax requests
        ...
    }
});
```
After extending `$.jgrid.guiStyles` with new set of CSS settings one can use `guiStyle` option of jqGrid with new value: `guiStyle: "myBootstrapSettings"`. Thus one need just replace the standard jQuery UI CSS classes used in all internal jqGrid components to the corresponding Bootstrap CSS classes. In other words one should do almost the same like described [here](https://github.com/free-jqgrid/jqGrid/wiki/Using-Font-Awesome-in-free-jqGrid-4.8#creating-of-custom-iconset), but customize `guiStyle` instead of `iconSet`.

Creating of such set of CSS settings would be interesting for many other developers, which uses free jqGrid. I suggest you not just use what I implement and send me new feature requests (which is helpful too of cause), but *to contribute to the development* of free jqGrid.

**Comment by Wooya** [comment] 2015-11-18 07:16
Thanks a lot for response. I've missed guiStyles option somehow. I'll take a closer look to this option.

**Comment by OlegKi** [comment] 2015-12-18 09:06
@Wooya : Do you have some progress in creating `guiStyles` options for Bootstrap?

**Comment by jdetaeye** [comment] 2016-01-14 10:24
We're also interested in aligning free-jqgrid better with the popular bootstrap framework.
I started looking into the settings for the "guistyles" variable for bootstrap.

I'm not sure the gui-styles approach is going to properly address the issue:
* Things are more complex than a simple 1-to-1 mapping between the styles.  See https://github.com/twbs/bootstrap/blob/master/less/tables.less for the native table styles of bootstrap, and it'll be clear it involves more than renaming some styles.
* The native bootstrap styling doesn't support all of the functionality free-jqgrid offers.  Eg sorting by clicking on a column.
* The getGuiStyles function to look up the right styles to apply has a performance penalty - probably small, but completely avoidable

A good solution will require a bootstrap specific stylesheet (ideally in less-format to make it themeable in bootstrap).   
The upcoming-free-jqgrid competitor "datatables" plugin uses a similar approach: see https://github.com/DataTables/DataTables/tree/master/media/css. They have wisely made the styles in their plugin independent of any UI-framework, and then provide a stylesheet per framework.

**Comment by OlegKi** [comment] 2016-01-14 11:13
Hi @jdetaeye !

One should distinguish two problems:
 1. small visual effect like increasing the font-size, some paddings and magings
 2. the usage of common bootstrap styles like classes `table table-bordered`, `bg-danger`, `btn`, `btn-default`, `success`, `active` and so on.

jqGrid 4.6/4.7 had wrong calculations of widths (because of usage another boxing model for example), problems with replacing of icons and some other problems. I fixed the problems already in the first version of free jqGrid (4.8). One can increase font-size together with adjusting paddings and magings, but *adding small set of additional CSS rules*. I think to provides the corresponding examples on [the documentation site](http://free-jqgrid.github.io/). I thought about including sass file in building process, which will simplify to generate `ui.jqgrid.css` with adjusted properties.

*Thus there are no general compatibility problem of jqGrid with Bootstrap*. [The page](http://free-jqgrid.github.io/getting-started/index.html) contains for example many live jqGrids and it uses Bootstrap.

The second problem is just choosing the best configuration of jqGrid with the usage of the native Bootsrtap classes like `table table-bordered`, `bg-danger`, `btn`, `btn-default`, `success`, `active` and so on. I made 99% of the required changes in free jqGrid code. One need just extend `$.jgrid.guiStyles` with the set of settings, which *uses* the Bootsrtap classes. Short time after I started the changes in free jqGrid, Tony made the same changes in Guriddo jqGrid JS.

Thus one need to extend [the structure](https://github.com/free-jqgrid/jqGrid/blob/v4.12.0/js/grid.base.js#L501-L502) of free jqGrid with the corresponding settings from Bootstrap. One can look at [the settings](https://github.com/tonytomov/jqGrid/blob/master/js/grid.base.js#L1019-L1077) for example and to use close classes in free jqGrid. I have just time problem to do this. I develop free jqGrid for free and I get almost no donations. It's almost the only problem. Nevertheless I can try to create some prototype of setting `$.jgrid.guiStyles` in the next days and to share there with you. I'm sure that we can create the set for Bootstrap very quickly, but one will need to made some iterations of the process. You will need to review the styles and to provide your suggestions what can be additionally made.

**Comment by jdetaeye** [comment] 2016-01-14 11:35
>>Thus there are no general compatibility problem of jqGrid with Bootstrap. 
>>The page contains for example many live jqGrids and it uses Bootstrap.

The goal should be more than "no compatibility issues", and simple to be able to use free-jqgrid without jquery-ui at all.
The page you refer to is using jquery UI + bootstrap.

>>Thus one need to extend the structure of free jqGrid with the corresponding settings 
>>from Bootstrap. One can look at the settings for example and to use close classes in 
>>free jqGrid. I have just time problem to do this. I develop free jqGrid for free and I 
>>get almost no donations. It's almost the only problem. Nevertheless I can try to 
>>create some prototype of setting $.jgrid.guiStyles in the next days and to share 
>>there with you. I'm sure that we can create the set for Bootstrap very quickly, but 
>>one will need to made some iterations of the process. You will need to review 
>>the styles and to provide your suggestions what can be additionally made.

If you can kickstart us some prototype to start with, we'll definitely work with you through these iterations. 
Once I come over my current "puzzled" state, I'll be able to contribute productively...

(In case you're wondering about the context in which we use free-jqgrid, you can look at https://demo.frepple.com)

**Comment by OlegKi** [comment] 2016-01-14 12:57
OK, I will post you the preliminary results in the next days.

It's important to have an example of usage free jqGrid. One think is important to stress. I strictly recommend you to use more active loading of CSS and JavaScript files from CDN. See [the article](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs). I can explain the main difference on an example. Your demo site use **local** paths for `font-awesome.min.css` (and all the fonts), `jquery-2.1.4.min.js`, jquery UI, free jqGrid and so on. If you would examine the header of the response of loading `font-awesome.min.css` for example you would see during loading of https://demo.frepple.com/static/css/font-awesome.min.css something like the following HTTP headers
```
Cache-Control:max-age=10800
Date:Thu, 14 Jan 2016 12:24:12 GMT
Expires:Thu, 14 Jan 2016 15:24:12 GMT
```
If you would compare the HTTP headers with the headers from https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css you will find:
```
Cache-Control:max-age=31104000
Date:Thu, 14 Jan 2016 12:36:26 GMT
Expires:Sun, 08 Jan 2017 12:36:26 GMT
```
You can see that the `bootstrapcdn` cached the files much more aggressive. The files of Font Awesome 4.5.0 will be **never** changed and the new version will have another URLs. Thus such caching have no problems.

Thus if you would use some common CDNs you will use **in the most case** the local files from the web browser cache. Even the first loading is very quickly because of good infrastructure of CDNs. By the way if one loads the CDNs files from internal network of the company that one loads the files mostly only from the local proxy server.

If you take in consideration the advantages of CDN then you will see that the usage of additional jQuery UI CSS would be not really important. At least the subject have practical no influence on the performance of the web site in more as 99% of cases. I'd recommend you to think about it and to make some tests.

Nevertheless the problem with customizing of free jqGrid for Bootsrap stay and I will contact you later about it.

**Comment by OlegKi** [comment] 2016-01-15 09:24
To be more exact what I mean with the usage of CDN and local files as fallback only I'd recommend you to read [the article](http://www.hanselman.com/blog/CDNsFailButYourScriptsDontHaveToFallbackFromCDNToLocalJQuery.aspx). The main idea is testing whether `window.jQuery` is `undefined` after the `<script>`, which loads jQuery from CDN and starting dynamic loading from another place. The simplest implementation looks like
```html
<script src="//code.jquery.com/jquery-2.2.0.min.js"></script>
<script>window.jQuery || document.write('<script src="js/jquery-2.2.0.min.js">&lt;/script>')</script>
```
One can use [Microsoft.AspNet.Web.Optimization](https://www.nuget.org/packages/Microsoft.AspNet.Web.Optimization/), [RequireJS](http://requirejs.org/) and many other, which do internally the same trick in different small variations.

If you use ASP.NET 5 then one can use `asp-fallback-*` attributes: `asp-fallback-src` and `asp-fallback-test` attributes of `<script>` (see [here](https://docs.asp.net/en/latest/client-side/angular.html?highlight=fallback#installation)) and `asp-fallback-href`, `asp-fallback-test-class`, `asp-fallback-test-property` and `asp-fallback-test-value` attributes of `<link>` (see [here](https://docs.asp.net/en/latest/client-side/bootstrap.html?highlight=fallback#nuget)).

**Comment by Wooya** [comment] 2016-01-20 13:22
Hi Oleg! I've taked a look at `guiStyles` and I think it's impossible to do with standard Bootstrap 3.5 styles. Some of the BS classes are quite usable (like panel, panel-primary, panel-body, panel-heading and states classes), but most of them not.

**Comment by OlegKi** [comment] 2016-01-24 21:04
You can see [here](http://www.ok-soft-gmbh.com/jqGrid/OK/formEditOnDoubleClick-bootstrap.htm) **very preliminary** version of the implementation `guiStyles` with Bootstrap classes.

**Comment by OlegKi** [comment] 2016-01-31 21:48
[The demo](http://www.ok-soft-gmbh.com/jqGrid/OK/formEditOnDoubleClick-bootstrap1.htm) demonstrates the last changes which I committed today to GitHub.  The changes are not finished, but I can name the version as beta version of Bootstrap support. Some new CSS rules can be customized by overwriting defaults from `ui.jqgrid.css`. I mean the setting like
```
.ui-jqgrid.ui-jqgrid-bootstrap {
	border: 1px solid #ddd;
	border-radius: 6px;
}
.ui-jqgrid-view > .ui-userdata {
	background-color: #f0f0f0;
}
.ui-jqgrid.ui-jqgrid-bootstrap .custom-hdiv {
	background-color: #e5e5e5;
}
.ui-jqgrid-view > .ui-jqgrid-sdiv td {
	background-color: #f9f9f9
}
.ui-jqdialog {
	font-size: 14px;
}
.ui-jqgrid.ui-jqgrid-bootstrap .ui-jqgrid-titlebar,
.ui-jqgrid.ui-jqgrid-bootstrap .ui-jqgrid-errorbar,
.ui-jqdialog.ui-jqgrid-bootstrap .ui-jqdialog-titlebar {
	font-size: 16px;
}
.ui-jqgrid.ui-jqgrid-bootstrap .custom-title-div,
.ui-jqdialog .custom-dlg-header {
	background-color: #cacaca;
	border-top-left-radius: 6px;
	border-top-right-radius: 6px;
}
.ui-jqgrid-bootstrap.ui-jqgrid-resize-mark {
	border: 1px solid #aaaaaa;
	background-color: #cccccc;
	color: #222222;
	font-weight: bold;
}
.ui-jqgrid.ui-jqgrid-bootstrap .sgbutton-div .sgbutton.btn:focus,
.ui-jqgrid.ui-jqgrid-bootstrap .sgbutton-div .sgbutton.btn:hover {
	border: 1px solid #333;
}
```
and so on. All `color`, `background-color` and `font-size` can be easy overwritten. I thought how one can simplify the setting.

I think to set `btn-primary` on some buttons of Add/Edit/Search/Delete dialog and I think about simplifying settings of some additional classes like `btn-danger` on the buttons.

The CSS settings and the code contains many changes and have to be tested. Your feedbacks are welcome!

**Comment by Wooya** [comment] 2016-02-25 20:42
Thanks a lot for this feature! It works like a charm :-) At the moment I didn't find any flagrant irregularities, but still testing ;-)

**Comment by OlegKi** [comment] 2016-02-25 20:47
I'm very glad that it looks OK. I'm wonder that nobody posted any bug report till now. In any way, please inform me about any problems which you'll find or any suggestions to improve it.

**Comment by Wooya** [comment] 2016-02-25 21:29
At the moment one thing is annoying. When body background is different than default grid odd rows looks veird :)

Default background:
![zrzut ekranu z 2016-02-25 22-25-16](https://cloud.githubusercontent.com/assets/541588/13334989/14d7b0f4-dc0f-11e5-9748-38c2c3cd0805.png)

Non default background color:
![zrzut ekranu z 2016-02-25 22-27-06](https://cloud.githubusercontent.com/assets/541588/13335004/24e88784-dc0f-11e5-8d3f-1775b93353bf.png)

**Comment by OlegKi** [comment] 2016-02-26 06:25
It seems be the standard behavior of Boostrap CSS Theme of the table. You can change the look of the grid if you would add `background-color:white;` to the outer div of the grid or if you would add
```css
.ui-jqgrid-bootstrap.ui-jqgrid {
    background-color: white;
}
```
to the on top div of the jqGrid

**Comment by Wooya** [comment] 2016-02-26 07:59
Problem with background color is less important. But I'm also using bootswatch themes, and when I switch theme to dark one, jqgrid top and bottom panels not looking good. Maybe those panels should inherit their background color from table.td class somehow?

![image](https://cloud.githubusercontent.com/assets/541588/13346511/206ca34a-dc67-11e5-805a-75e304b22b8d.png)

**Comment by OlegKi** [comment] 2016-02-26 08:36
@Wooya : I'm not know perfectly, but it seems to me that Bootstrap don't have any standard beckground set in the theme, which can be used in jqGrid. The grid can have the follwoing components

- grid header (caption)
- top pager
- top toolbar
- column headers
- filter toolbar
- grid body
- grid footer
- bottom toolbar
- pager

To display the components contrast enough one need to have to least 3 backgrounds *in the same or close colors* (for example blue color with different level of darkness), but Boostrap  is oriented mostly on the set from two colors or large set *very different colors*: `bg-primary`, `bg-success`, `bg-info`, `bg-warning`, `bg-danger`. See [the lines of Bootsrtap CSS](https://github.com/twbs/bootstrap/blob/v3.3.6/dist/css/bootstrap.css#L1375-L1410). On the other side the background colors of Bootstrap can be changed very easy. One uses  `background-image`, just using `linear-gradient` effects and one divides the standard CSS in two clear parts `bootstrap.css` and `bootstrap-theme.css`, where `bootstrap.css` is image free.

Thus I had the choice between white grid like Guriddo jqGri JS do and some *example* set of beckground colors which could be easy overwritten. I've chosen the second way, but included [**the demo**](http://www.ok-soft-gmbh.com/jqGrid/OK/grouping-bootstrap.htm) in the readme of free jqGrid 4.13.0, which shows how to customize the background colors in the grid.

By the way you can find close examples about customizing the background colors in the same issue thread (see above [the comment](https://github.com/free-jqgrid/jqGrid/issues/176#issuecomment-177624225)). If you know some other way of choosing *standard* background colors of the them which would be looks good for different themes, it would be very interesting to know for me. I'm not CSS expert or less more Bootstrap CSS expert.

**Comment by dterra** [comment] 2016-03-03 19:39
The new `styleUI: 'Bootstrap'` works great for me also, but I think subgrids need some styling yet. Bootstrap classes are not added to the subgrid container table, and the cells may need some fixing also.
@OlegKi , to play with Bootstrap's options (including background colors), there is a great tool I often use called [Bootstrap Live Customizer](http://bootstrap-live-customizer.com/). You can customize almost every Bootstrap option by changing `variables.less` on-the-fly, and the results are visible live while you are playing with them. You can then download the custom css theme and the less variables without even knowing what less compilation is.

**Comment by OlegKi** [comment] 2016-03-03 21:11
Thank you for the bug report! I made some changes in `ui.jqgrid.css` (see [the commit](https://github.com/free-jqgrid/jqGrid/commit/9391b8290edfde3c5626e09953d4a606785caa45)). I hope that the problem is solved now. If you do find some more problems, please modify the demo https://jsfiddle.net/OlegKi/kc2537ty/3/ to demonstrate it.

**Comment by dterra** [comment] 2016-03-04 17:26
Thank you @OlegKi. 
I think that subgrid should have bootstrap style not only when grid is used as subgrid, but also the standard subgrid.
I'm sorry, but I tried to create a simple jsfiddle with a simple subgrid to explain what I'm trying to say, but couldn't get it working with remote example json data.
I'll try to explain myself with a few captures:
This is how the subgrid looks like:
![simplesubgrid](https://cloud.githubusercontent.com/assets/17619145/13533846/171be314-e211-11e5-9a1b-335293c76104.png)

The expanded subgrid table `'td.subgrid-data table'` does not have any class at all.
If you add `class="table table-hover table-condensed table-bordered"` to it, and then, in css, remove
from `.ui-jqgrid .ui-subgrid tr.ui-subtblcell td` these:
```
    border-bottom-color: inherit;
    border-bottom-style: solid;
    border-bottom-width: 1px;
```
...and add `padding: 2px;`, and also:
```
.ui-th-subgrid {
    background-color: #e5e5e5;
}
```
...it looks like this:
![simplesubgrid](https://cloud.githubusercontent.com/assets/17619145/13534510/4c44eb8c-e214-11e5-9a7a-af8248db8b9c.png)
...which I think is how it should look like.
I'm sorry I couldn't get the fiddle working, hope it helps.

**Comment by OlegKi** [comment] 2016-03-04 22:28
@dterra : You are right! I absolutely forgot about the **legacy** subgrid.

To tell the trust I thought to drop it at all, because I could not find any examples or questions, which I answers, which uses `subGridModel`, `subgridtype` and `subGridUrl` in the last 5 years. I don't recommend you to use it, because it's not flexible enough.

Nevertheless the feature exists and I would fix the code in the next days. I'll post you small comment after I'll make the changes. Thank you for pointing me to problem!

**Comment by OlegKi** [comment] 2016-03-05 13:14
@dterra : I posted [the fixes](https://github.com/free-jqgrid/jqGrid/commit/8f1216142f13633cb82f8f255c4f40a4fb0c02fa) of legacy subgrid to GitHub. Please verify whether all the problem with styling of subgrid are fixed now.

**Comment by Wooya** [comment] 2016-03-08 06:52
@OlegKi please don't drop simple subgrid feature :( I'm using this feature very often for simple master - detail tables. I know, we can use grid as subgrid, but sometimes it's very overloaded for simple subgrid which just displaying some data.

**Comment by OlegKi** [comment] 2016-03-08 07:37
@Wooya OK! No problem.

**Comment by dterra** [comment] 2016-03-08 13:46
@OlegKi : [The fixes](https://github.com/free-jqgrid/jqGrid/commit/8f1216142f13633cb82f8f255c4f40a4fb0c02fa) of legacy subgrid look good to me, thank you very much!
:+1:  for keeping simple/legacy subgrid. I really like the fact that I can make a subgrid with just a few lines of code. I prefer to keep it simple when I just need to show some related data that doesn't need searching/sorting.

**Comment by OlegKi** [comment] 2016-03-08 16:51
Thanks to all. I will keep the simple/legacy subgrid.

It seems that the Bootstrap support is implemented now and I close the issue. One should report new issue to report any new bug.

**Closed by OlegKi** 2016-03-08 16:51 UTC
Labels: enhancement
