### ISSUE TITLE
4.15.0 can't autoresize with rows content

### ISSUE THREAD

**Issue by truelife2** [free-jqgrid/jqGrid#377] opened 2017-09-25 01:47 UTC
after upgrade to 4.15.0,the column auto resize only shrink with header,

i take some debug, when call getAutoResizableWidth colWidth will be NaN.

colWidth = cm.rotated ?
$incosDiv.outerHeight(true) :
$incosDiv.outerWidth(true) + $thDiv.children(".ui-jqgrid-sort-order").outerWidth(true);

$thDiv.children(".ui-jqgrid-sort-order").length was 0 and .outerWidth(true) was undefined
and test 4.14.1 was okay.

and has a another problem,about  shrinkToFit=false
wheni shrinkToFit: false,autoresizeOnLoad: true,,
after data loaded,column will always shrink to fit,

after debug the code,when call setGridWith, will always use shrinkToFit=true?
resort = function () {
	var iRes;
	if (p.autoresizeOnLoad) {
		$j.autoResizeAllColumns.call($self);
		clearArray(p.columnsToReResizing);
		if (p.autowidth) {
			$j.setGridWidth.call($self,
				$self.closest(".ui-jqgrid").parent().width(),
				true);
		}
	} else {
		for (iRes = 0; iRes < p.columnsToReResizing.length; iRes++) {
			$j.autoResizeColumn.call($self, p.columnsToReResizing[iRes]);
		}
		clearArray(p.columnsToReResizing);
	}
},

**Comment by OlegKi** [comment] 2017-09-25 09:09
Thanks for the bug report! I poste the corresponding fix to GitHub. Please verify whether the bug is fixed now.

You reported **two** problems, but I can't reproduce the second one. I can't reproduce any problem with the usage of `autoresizeOnLoad: true` in combination with `shrinkToFit: false`. The code fragment of `resort` function isn't changed in free jqGrid 4.15.0 (comparing with free jqGrid 4.14.1). Probably you had only one problem (the first one, which you reported)? Could you provide the demo, which can be used to reproduce the problem?

**Comment by truelife2** [comment] 2017-09-25 12:12
sorry, my previous version was 4.13.3,the first problem,i has use 4.14.1 and 4.15.0 to test;

the second problem, on 4.14.1 and 4.15.0 has the same situation,i'm not test other version.
this time i downloaded other version to test ,on 4.13.4    4.13.5   4.13.6 was okay;
but 4.14.0 version begin has the problem.

seem when call resort, it will auto resize,but shrinkToFit parameter always send "true"?
if (p.autowidth) {
	$j.setGridWidth.call($self,
		$self.closest(".ui-jqgrid").parent().width(),
		true);
}
maybe send p.shrinkToFit will better, or that has other reason?
	$j.setGridWidth.call($self,
		$self.closest(".ui-jqgrid").parent().width(),
		p.shrinkToFit);

this was my one grid's options:

{"mtype":"POST","colModel":......,"jsonReader":{"root":"datas"},
"localReader":{"id":"$g$id"},"autowidth":true,
"autoresizeOnLoad":true,
"shrinkToFit":false,
"singleSelectClickMode":"",
"rowNum":15,
"rowList":[10,15,20,25,30,50],
"ajaxGridOptions":{"contentType":"application/json; charset=utf-8","dataType":"json"},"url":"/LSI101W/Main/Gets","datatype":"json","pager":"#gridpager"}

thank you.

**Comment by truelife2** [comment] 2017-09-25 12:20
i has test 4.15.1.pre, the first one problem was fixed, thank you very much.

**Comment by OlegKi** [comment] 2017-09-25 12:50
Sorry, but I repeat, that **I can't reproduce any problem if I use `autoresizeOnLoad: true` in combination with `shrinkToFit: false`**. Try https://jsfiddle.net/OlegKi/dk2qwbcs/ for example. You see that the columns will be **not** shrinked. You can change `width: 350` to  `width: 450` and see that the columns with be **not** expanded too.

I can only guess, which problem you really have. You could interpret the results in the wrong way, or you could call `setGridWidth` method explicitly somewhere in your code, with wrong parameters (shrinking), or some bug could really exist in free jqGrid, but **I need to have the demo**, which reproduces the problem, which I can debug to fine the origin of the problem.

**Comment by truelife2** [comment] 2017-09-25 13:48
i update you demo here,
https://jsfiddle.net/dk2qwbcs/1/

                 width:800,
                autowidth: true,
                autoresizeOnLoad: true,
                shrinkToFit: false,

i update these parameters,
shrinkToFit set to false,but it will force shrink to fit

**Comment by OlegKi** [comment] 2017-09-26 00:11
Sorry, but I'm not sure, which behavior you try to implement because you use `autowidth: true`. The option `autowidth: true` **force** expanding/shrinking of the columns, which hasn't `fixed: true` option (like rownumber column).

**What behavior you expect in the case from `autoresizeOnLoad: true` in combination with `autowidth: true`?** The only case, which I know, would be the usage of `resetWidthOrg: true` property of `autoResizing` option. See https://jsfiddle.net/OlegKi/dk2qwbcs/3/ and the issue https://github.com/free-jqgrid/jqGrid/issues/289 for more details.

**Comment by truelife2** [comment] 2017-09-26 00:55
thx your help,i use the gird for our maintain system,like this,grid need to fill a space.,sometime need horizontal scrollbar to view full context.
![demo1](https://user-images.githubusercontent.com/12017748/30837234-0a02827c-a296-11e7-8812-cdfef4ca90f6.png)
![demo2](https://user-images.githubusercontent.com/12017748/30837235-0a0c83e4-a296-11e7-9641-0b464a619163.png)

autowidth's feature,not just fill the grid to content?

**Comment by OlegKi** [comment] 2017-09-26 05:31
The usage of
```JavaScript
autoResizing: { compact: true, resetWidthOrg: true }
```
seems to me the best choice for you. See https://jsfiddle.net/OlegKi/dk2qwbcs/3/. (You should compare more exactly the width of resulting columns in the demo). See the issue https://github.com/free-jqgrid/jqGrid/issues/289 for more details.

Additionally you can reduce the width of columns by rotating "checkbox" columns (Y/N columns) with respecto of `rotateColumnHeaders`. See https://jsfiddle.net/OlegKi/dk2qwbcs/4/ demo, where I added:
```JavaScript
fixed: true,
width: 28
```
to prevent rotated columns from shrinking and fixing there width.

**Comment by OlegKi** [comment] 2017-09-26 08:15
Free jqGrid allows easy to implement **any other custom resizing scenario**. One need just **remove** `autowidth: true` and `autoresizeOnLoad: true` options and to add `jqGridAfterLoadComplete` event handler, which calls methods `autoResizeAllColumns` and `setGridWidth` explicitly.

The demo https://jsfiddle.net/OlegKi/dk2qwbcs/5/ uses
```JavaScript
$("#grid1").on("jqGridAfterLoadComplete", function () {
    var $self = $(this),
        p = $self.jqGrid("getGridParam"),
        outerWidth = $self.closest(".ui-jqgrid").parent().width();

    $self.jqGrid("autoResizeAllColumns");
    if (outerWidth > 0 && p.width > outerWidth) { // the grid isn't hidden
        // we can choose as the new width min from the width of data (p.tblwidth)
        // and the width of outer div. As the result one will don't create any
        // unneeded space on the right side of the grid for small grids, but still
        // create horizontal scroll bar for the grid with large content
        $self.jqGrid("setGridWidth", Math.min(outerWidth, p.tblwidth), false);
    }
});
```
to reduce the width of the grid and to create the horizontal scrollbar only in case of small outer div:
![grid2___](https://user-images.githubusercontent.com/249117/30849632-429259de-a2a3-11e7-8333-f7c01a98da4a.png)
but still hold the grid *without unneeded space of the right side and without expanding the columns* if the width of outer div is large enough:
![grid1___](https://user-images.githubusercontent.com/249117/30849685-72989e54-a2a3-11e7-8242-fb114217ed8c.png)
In the same way, you can modify the code of `jqGridAfterLoadComplete` and implement *any other scenario*, which you need.

**Comment by truelife2** [comment] 2017-09-26 08:33
OK,very thx your help,i will do it by this way.

and very like your project,that save my much time, and it was free, haha 

thank you ,again.

**Comment by OlegKi** [comment] 2017-09-26 08:41
You are welcome! Don't forget to close the issue after your question will be cleared.

**Closed** 2017-09-26 11:42 UTC
Labels: bug
