### ISSUE TITLE
Box-sizing inherit problem

### ISSUE THREAD

**Issue by rcpacheco** [free-jqgrid/jqGrid#155] opened 2015-10-17 18:59 UTC
After upgrading from 4.8.0, I noticed that with version 4.9.2 an empty space apears at the end of the columns. See Picture.
With box_size inherit:
![with_box_size_inherit](https://cloud.githubusercontent.com/assets/845725/10560648/122c3482-74d7-11e5-98c9-cb9804899b8d.PNG)

Without box_size inherit:
![without_box_size_inherit](https://cloud.githubusercontent.com/assets/845725/10560649/14a2d734-74d7-11e5-8217-53048f5011f8.PNG)

The problem was caused by the following commits:
Fix boxing model for gbox - 0a7354b85792d523fdacbd842fd1817873e5ff55
small code optimizations - b9bd804b97fdb70be0c52fba1290dca814d51f42

They add to the styles the following part,

jqGrid/css/ui.jqgrid.css:
32 .ui-jqgrid > .ui-jqgrid-view *,
33 .ui-jqgrid > .ui-jqgrid-view *:before,
34 .ui-jqgrid > .ui-jqgrid-view *:after {
35	-webkit-box-sizing: inherit;
36	-moz-box-sizing: inherit;
37 	box-sizing: inherit;
38 } 

After removing those lines, the problem was solved.

**Comment by OlegKi** [comment] 2015-10-17 22:48
Hi Ricardo!

Thank you for reporting the issue. I confirm that the box-sizing is changes in 4.9. It was the only way which I found to hold all divs and especially widths of grouping rows of data grouping be inline with the width of the grid during zooming. I understood that such changes will change the total width of existing grids, but the look of the grids should still looks OK. If I take a look on both pictures which you posted I see the content of the columns looks good in my opinion. The only small problem seems to me that you use `shrinkToFit: false` option and set **explicitly** the width of the grid (`width` option). Is it so? You don't posted the URL to the demo or the options of jqGrid which you use. I just guess. If it's so then I would recommend you just remove `width` option from jqGrid options or to adjust the width of every column (you can try to add 5 to every width value).

You can of cause to include CSS rules
```css
.ui-jqgrid > .ui-jqgrid-view {
	-moz-box-sizing: content-box;
	-webkit-box-sizing: content-box;
	box-sizing: content-box;
}
```
after `ui.jqgrid.css` to overwrite the setting, but it would be not the way which I would recommend you.

The problem is: there are many devices (even monitors) with high DPI resolution and many people (inclusive me) use more as 100% zoom in web browser to see web pages. If I use 150% zoom then the 1px border will be different calculated in different web browsers. One have close problems in other situations, but grouping looks the mostly bad after zooming. So I can't find any optimal CSS settings with border 1px which use old `box-sizing: content-box;` model and where all possibilities of jqGrid (inclusive grouping) looks good. Only using `box-sizing: border-box;` I get the best results. It's the setting used by very popular Bootsrap css.

Ricardo, could you confirm that you use `shrinkToFit: false` and some explicit value for `width` in the grid which pictures you posted? Can the problem be fixed by removing of `width` option of the grid or by changing (increasing) the the value of `width` property for every column? Setting of `box-sizing: content-box;` (or to `inherit`) for `.ui-jqgrid > .ui-jqgrid-view` should set the old style of cause and fix the problem too, but I see that `box-sizing: border-box;` get better results in the most complex scenarios, so I made it the default style of free jqGrid.

**Comment by rcpacheco** [comment] 2015-10-18 17:46
Thanks a lot! you are completely right. I'm using shrinkToFit: false.
I'm opening the grid in pop up windows, shrink wrapped to the exact size of the grid and in that way they look really nice.
I checked all the options that you suggested and I end up calculating the with width properly. I'm also displaying always the scroll-bar, so that I can always anticipate its effect in the total with.
Sorry for the false report. As always, very grateful of the great job you have done taking maintaining jqgrid as committed in this new phase as you have in the past.

To create the real grid I'm using a library that I created to create the grids in a declarative way generating the proper options for free-jqgrid, so that creating a new grid is extremely simple, but this is the final result from that library: http://rcpacheco.github.io/test_box_sizing.html
Thanks again!

**Comment by OlegKi** [comment] 2015-10-18 19:54
You are welcome! It seems that the issue is solved and I am closing it.

It's good if you continue to post all suspected parts of free jqGrid. It would be important to fix all existing bugs and to simplify the usage. The best way to archive this I see in communication with other persons who use it.

Best regards
Oleg

**Closed by OlegKi** 2015-10-18 19:54 UTC
