### ISSUE TITLE
Global search with highlighting and inline editing

### ISSUE THREAD

**Issue by johncze** [free-jqgrid/jqGrid#81] opened 2015-06-06 17:41 UTC
Hi Oleg,

I use this example http://www.ok-soft-gmbh.com/jqGrid/OneFieldSearching2_.htm (this example is from stackoverflow http://stackoverflow.com/questions/22716630/jqgrid-multi-word-search-with-global-search) and I have a problem with inline editing. If I will write the text into the search field, then jqgrid filters rows. Now If I will double click on the filtered row, the field containing highlight has value => <span ...> highlight value</span>. The span is from jQuery Highlight, but I don't know how to hide this span during inline editing and after saving edited row shows this span.

![jqgrid](https://cloud.githubusercontent.com/assets/4117874/8020715/f0a3f0ae-0c83-11e5-8fff-bf10f0e5cb8c.png)

Thank you for your advice.

**Comment by OlegKi** [comment] 2015-06-06 20:19
The code which you use contains the row
```JavaScript
$self.find(">tbody>tr.jqgrow>td:nth-child(" + (iCol + 1) + ")").highlight(rule.data);
```
I think that one can modify the line and include [attribute-not-equal-selector](https://api.jquery.com/attribute-not-equal-selector/) `[editable!='1']`:
```JavaScript
$self.find(">tbody>tr.jqgrow[editable!='1']>td:nth-child(" + (iCol+1) + ")").highlight(rule.data);
```
I hope that it will work. There are many other ways to skip selection of inline editing, but one need make more changes in the code in the case.

**Comment by johncze** [comment] 2015-06-07 08:05
Unfortunatelly, this  attribute-not-equal-selector atribute doesn't work. Are the other solutions more complicated?

**Comment by OlegKi** [comment] 2015-06-07 08:34
Could you post the demo which reproduces the problem. The original demo have no inline editing and it use highlighting *together* with searching which *reloads* the grid. After reloading there are *no editable rows*. So I don't understand what you do exactly. Having the demo I could help you to solve the problem. Please use `jquery.jqgrid.src.js` with direct URLs to GitHub (see [the wiki](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs#access-githib-code-from-rawgit)) in the demo.

**Comment by OlegKi** [comment] 2015-12-18 09:10
I didn't get any demo from you, which can be used to reproduce the problem. I can't fix the problem if I can't reproduce it.

I close the issue. You can post me additional information and reopen the issue any time later.

**Closed by OlegKi** 2015-12-18 09:10 UTC
Labels: question
