### ISSUE TITLE
Ui tab and pager

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#205] opened 2016-02-04 06:52 UTC
If have 2 UI tabs, at second tab, when i use $grid.setGridWidth(500, true) the pager first td column is calcultate wrong. The width It is much smaller than it should be.
setGridWidth(500, true) calculates the correct grid, but the problem is the pager.
See http://s7.postimg.org/k0u7xcv7f/pager.png

**Comment by OlegKi** [comment] 2016-02-04 15:05
I suppose that you create the grid with small width value and then increase it using `setGridWidth`. The problem is old ant it exist in old versions of jqGrid too. One can use `width` parameter of grid with some large enough value and then set use `setGridWidth`, like you do already, to set the width to the value (500), which you really need.

If you would use the latest code grom GitHub, then you can use three additional optional parameters of jqGrid: `pagerLeftWidth`, `pagerCenterWidth`, `pagerRightWidth` (for example `pagerLeftWidth: 150`). One should *not* set the width of all three values at the same time (just one `pagerLeftWidth`/`pagerRightWidth` or two: `pagerLeftWidth` and `pagerRightWidth` or `pagerLeftWidth`, `pagerCenterWidth` or ...). It allows to place the parts of the the pager on the optimal position.

One more option which you have is *changing the width of every from three parts of the pager explicitly*. One need just know that the parts of the pager have ids which are build from the pager id and the texts `"_left"`, `"_center"` and `"_right"`. If you use `pager: true` or `toppager: true` option and you don't specify the id of the pager explicitly, then you can get the id using `getGridParam`. For example
```JavaScript
var pagerIdSelector = $("#grid").jqGrid("getGridParam", "pager");
$(pagerIdSelector + "_left").width(150); // 150px for the navigator bar
```

**Comment by davgino** [comment] 2016-02-04 19:23
Thanks for the tips

**Comment by OlegKi** [comment] 2016-02-05 22:08
Is the problem is solved? Please close the issues about solved problems or post additional information about the problem.

**Comment by OlegKi** [comment] 2016-02-09 15:58
I'm closing the issue because I didn't get any answer from you. You can reopen it at any time later if it would be required.

**Closed by OlegKi** 2016-02-09 15:58 UTC
Labels: question
