### ISSUE TITLE
Column Chooser and grouping : true 

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#277] opened 2016-11-15 17:31 UTC
When choosing a column on the right to be displayed I get the following error:
TypeError: inGroup is undefined - line 15619 col 1. 

Probably this error occurs in conjunction with grouping : true

**Comment by OlegKi** [comment] 2016-11-15 20:27
Thank you for the bug report! I posted [the fix](https://github.com/free-jqgrid/jqGrid/commit/b8cd89bfaca8e57f72db4f894fdddccdf1908a4d) and some other small changes. Please test the new code. I hope that the problem is fixed now.

**Closed** 2016-11-15 20:43 UTC
Labels: bug
