### ISSUE TITLE
free-jqGrid subgrid triggers events of higher level grid

### ISSUE THREAD

**Issue by Wooya** [free-jqgrid/jqGrid#64] opened 2015-05-21 05:31 UTC
When I moved to free-jqGrid I noticed strange thing. I've 3-level subgrids. When selecting row on subgrid onSelectRow event is triggered on higher grid level :-\

1) Selecting 1st level grid's row (console log shows IDDH01 row ID -> onSelectRow event)
![image](https://cloud.githubusercontent.com/assets/541588/7742113/d92f66b6-ff8a-11e4-931f-83b1f67b9dd9.png)

2) Selecting 2nd level grid's row (console log shows IDDH11 row ID -> onSelectRow event FROM 1st GRID IS TRIGGERED), 1st level grid row UNSELECTS
![image](https://cloud.githubusercontent.com/assets/541588/7742132/2056cd18-ff8b-11e4-854d-ba0db290f443.png)

3) Selecting 3rd level grid's row (console log shows IDDH21 row ID -> event as above), 2nd level grid row UNSELECTS
![image](https://cloud.githubusercontent.com/assets/541588/7742165/d0499944-ff8b-11e4-8cb6-65aff11a314f.png)

4) I've only one console.log() at 1st level grid:
```javascript
		onSelectRow: function (rowId, status, event) {
			mainGridId_DH_ID = rowId;
			console.log(mainGridId_DH_ID);
		}
```

**Comment by OlegKi** [comment] 2015-05-21 09:20
I verified the bug report, but I can't reproduce the problem. [Here](http://ok-soft-gmbh.com/jqGrid/OK/LocalSubgridMultileve3_-freejqGrid.htm) in the demo which I used.

You should verify that you have no id duplicates in the grids. The usage of `idPrefix` options in subgrids is really required. I hope you use there. **You should provide the demo which reproduces the described problem.**

**Comment by OlegKi** [comment] 2015-05-24 07:43
Is the problem still exist? Could you provide the demo which reproduce the problem?

**Comment by Wooya** [comment] 2015-05-25 14:11
Hi. Sorry for late response, but I've been quite busy :) I'll post my code today (hour or two)

**Comment by Wooya** [comment] 2015-05-25 14:57
Ok, here's JSFiddle https://jsfiddle.net/x4bgnvpu/2/ but my problem not occurs on this example altrough code is almost 100% copy of mine :( If you want to, I can give you via private message an access directly to my page, then you'll see in action what I described in first post.

**Comment by OlegKi** [comment] 2015-05-25 15:23
Looked at the code, but I see now problem. I find many thing in the code a little strange, but I see not the problem which you reported. I can localize the problem only if you provide the code which demonstrates the problem. You can post me some additional information via email. You see it on my profile https://github.com/OlegKi : oleg.kiriljuk@ok-soft-gmbh.com

**Comment by Wooya** [comment] 2015-05-25 15:55
I've send you an email with site address and account data.

**Comment by OlegKi** [comment] 2015-05-25 17:04
Could you update the code which you use to the current from GitHub. You get is after I made relatively large set to changes and before I have fixed some small problems in the next day.
I debugged the code and I can see that one can `return false` in some places to prevent event bubbling of `click` already successfully processed by subgrid. It would only improve a little the performance of processing the events, but the existing code already detect correctly the event from his grid.

**Comment by Wooya** [comment] 2015-05-25 17:18
Hi Oleg. I've just updates jqGrid sources with latest one.

**Comment by Wooya** [comment] 2015-05-25 17:46
I've tested now my code and it seems to not bubbling events :)

**Comment by OlegKi** [comment] 2015-05-25 18:47
OK. You should only don't forget to close the issue after making enough tests.

**Comment by Wooya** [comment] 2015-05-25 19:31
I'll not forget, but as I can see last free-jqGrid update fixed issue. Thanks a lot for your help, again :)

**Closed** 2015-05-25 19:39 UTC
