### ISSUE TITLE
JQGrid Searching: SearchType at serverside 

### ISSUE THREAD

**Issue by eppsaksh** [free-jqgrid/jqGrid#138] opened 2015-09-02 11:10 UTC
Hi Oleg,

I am using tool bar & advance searching onJQGrid, Searching is done at server side.
On server side, "filters" parameter are passed with all details to search. Search is working fine.

Here issue is I want searchType on server side to do some validation while searching.
We write searchtype:"integer",searchoptions:{sopt:['eq','ne','le','lt','gt','ge']} in colModel.
Is there any way to send this searchtype: integer to server(Like we do for filters, sidx, sord)?

Thanks,
eppsAksh

**Comment by OlegKi** [comment] 2015-09-02 11:41
Hi eppsAksh,

jqGrid provides many ways to extend the data which will be send to the server. For example one can use just `postData` to send additional information about the types of the columns to the server.

If the user click on Search button in Advanced Searching dialog or if the user trigger searching using the filter bar then `reloadGrid` event will be executed. Before `reloadGrid` jqGrid extend `postData` with additional property `filters`. During processing of reloading jqGrid test `search` parameter of the grid and set `_search` property of `postData`. So `postData` is always the origin of information which will be send to the server.

What you can do is for example the following
```JavaScript
postData: {
    modelTypeInfo: function () {
        var p = $("#yourGrid").jqGrid("getGridParam"),
              colModel = p.colModel, l = colModel.lenth, res = "", cm;
        if (p.search) {
            for (i = 0; i < l; i++) {
                cm = colModel[i];
                if (cm.searchtype !== undefined) {
                    res += cm.name + ":" + cm.searchtype + ";"
                }
            }
        }
        return res;
    }
}
```
The above code will send the information about types of all columns which have `searchtype` property and the server can use the information during processing of searching request. The above code is just an example of possible encoding of required information you can use any other format too.

Instead of using `postData` with the property defined as function you can use `beforeRequest` for example. You can use `$(this).jqGrid("getGridParam")` to access to parameters of jqGrid and you can append `postData` with the information which you need.

**Comment by eppsaksh** [comment] 2015-09-02 13:27
Hi Oleg,

Thanks For quick response. It is working as expected.
I have done below addition in code,
jqgrid as below:
    beforeRequest : function(){
    	  $('#gridID').jqGrid('setGridParam', { 'postData': {
    	    searchTypeInfo: function () {
    	        var p = $("#gridID").jqGrid("getGridParam"),
    	              colModellist = p.colModel, l = colModellist.length, res = "", cm, j;
    	        if (p.search) {
    	            for ( j = 0; j < l; j++) {
    	            	alert('inside');
    	                cm = colModellist[j];
    	                if (cm.searchtype !== undefined) {
    	                    res += cm.name + ":" + cm.searchtype + ";";
    	                }
    	            }
    	        }
    	        return res;
    	    }
    	} });
      }
And server side introduced parameter "searchTypeInfo"  to get values of searchtype from colModel.

Thanks,
eppsAksh

**Comment by OlegKi** [comment] 2015-09-02 13:38
You are welcome!

Please close issues after the problem is solved. Of cause I can close any issue too, but I prefer that the person who opens the issue do it. Additionally I would recommend you to use syntax highlighting in the code which you post. It's described [here](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown). I reformatted your last comment myself. Best wishes!

**Comment by eppsaksh** [comment] 2015-09-02 13:59
Hi Oleg,

Can we do this in filters (JSON Object), as like below
We have json object of filters as {"groupOp":"AND","rules":[{"field":"creditAmountLimit","op":"eq","data":"1"}]}

In above object, can we add details about searchType of that searched field.

Thanks,
eppsAksh

**Comment by OlegKi** [comment] 2015-09-02 14:16
jqGrid just set the `postData.filters` and trigger `reloadGrid`. Of cause you can convert the `filters` from JSON string to object inside of `beforeRequest` and to extent the object with another properties, but the code will be more complex and you will have to change your server code to parse modified `filters` structure.

I stressed that the code, which I posted you, is just an example how you can post the required information to the server. You should decide better yourself, which way is the best for your environment.

**Comment by eppsaksh** [comment] 2015-09-02 14:49
Hey Oleg,

Thanks a lot.

I have done as per below,
calling beforeRequestInJqGrid function in beforeRequest and e1 is gridID.

function beforeRequestInJqGrid(el){ 	
var gridData = el.jqGrid('getGridParam', 'postData'); 
var jsonFilters = $.parseJSON(gridData.filters); 	
var p = el.jqGrid("getGridParam"),colModellist = p.colModel; 	 
if(jsonFilters && jsonFilters.rules) { 		
$.each(jsonFilters.rules, function(i, rule){ 		
$.each(colModellist, function(j, column){ 			
if( rule.field == column.index ) { 				
rule.searchType = column.searchtype; 					
jsonFilters.rules[i] = rule; 					
return false; 		
} 			}); 		
}); 		 		
gridData.filters = JSON.stringify(jsonFilters); 	
el.jqGrid('setGridParam', { 'postData': gridData }); 
	} 
}

Thanks,
eppsAksh

**Comment by OlegKi** [comment] 2015-09-09 05:33
Is the problem is solved now? Please close the issue or describe the current opened problems.

**Closed** 2015-09-09 06:15 UTC
Labels: question
