### ISSUE TITLE
Multiselect widget filter plugin with Jqgrid

### ISSUE THREAD

**Issue by AshK14** [free-jqgrid/jqGrid#290] opened 2017-02-07 06:37 UTC
Hi Oleg,

I am having trouble filtering names which have a "," in them through multiselect filter in jqgrid.
For example, name:"John, Doe"

Please use this fiddle which demonstrates this issue,
https://jsfiddle.net/AshK14/3oeatxur/4/

I am using the latest version of free-jqgrid.

Thanks.

**Comment by OlegKi** [comment] 2017-02-07 22:16
Thank you for reporting the problem. I made some changes in the code of free jqGrid to prevent some more complex workarounds.

Now you can solve the problem just by adding new option **`inFilterSeparator: ";"`** to your code. The option inform jqGrid to use semicolon (`;`) instead of default comma (`,`) separator. See the results on https://jsfiddle.net/OlegKi/3oeatxur/5/

I posted before some other features to jqGrid. One can specify now **`generateValue: true`** property in `searchoptions` in case of usage `stype: "select"`. **No `value` need be specified in the case `searchoptions` in case of usage `generateValue: true`**. As the result jqGrid will generate case insensitive (because `ignoreCase: true` is default option) unique values, it will sort the unique values and will set `value` property in `searchoptions`. **As the result your code could be essentially simplified**.
See the final results here: **https://jsfiddle.net/OlegKi/3oeatxur/6/**

**Comment by OlegKi** [comment] 2017-02-13 12:32
Do you tested the new code from GitHub, which use new `inFilterSeparator` option? Do you tried the demo https://jsfiddle.net/OlegKi/3oeatxur/6/, which demonstrates another new property `searchoptions .generateValue`, which allows essentially simplify your code?

Please test the features and close the issue if the problem is solved now.

**Comment by OlegKi** [comment] 2017-02-15 21:42
@AshK14  I didn't get any response from you in the last days. The demo https://jsfiddle.net/OlegKi/3oeatxur/6/ shows clear that the reported problem is solved. Thus I'm closing the issue now.

**Closed by OlegKi** 2017-02-15 21:42 UTC

**Comment by AshK14** [comment] 2017-02-22 06:58
Hi Oleg,

Very sorry, could not test your changes till now.
I can confirm that it is working as expected.

Thanks a lot for your help.
