### ISSUE TITLE
Pivot grid: Horizontal scroll bar is below total footer row.

### ISSUE THREAD

**Issue by eppsaksh** [free-jqgrid/jqGrid#149] opened 2015-10-07 15:27 UTC
Hi Oleg,

I created pivot gris with below code, issue is horizontal scroll bar is below footer total row.
Is there any seeting to make it just below footer row.

var grid=jQuery("#grid1");
		var gridWidth = calculateWidth(null,null,grid); 

		 grid.jqGrid("jqPivot",
					data,
			        {   	
			            xDimension: [
						                { dataName: 'voucherType', label: "Voucher Type", width:calculateWidth(5,gridWidth,null)},
						                { dataName: 'voucherTypeDesc', label: "Description", width:calculateWidth(10,gridWidth,null)},
						                { dataName: "amount", label: "Amount", width:calculateWidth(8,gridWidth,null),summaryType:"sum",
						                formatter:function (cellvalue, options, rowObject){ return formatTypeTextBox(cellvalue, options, rowObject,'x0')}}
					                ],
			            yDimension: [	                         	
			                         	{dataName: 'chargeCategory'}//,

			                        ],
			            aggregates: [
			                         	{member: "chg_val",  aggregator: 'sum',label: 'Total',  width:calculateWidth(8,gridWidth,null),
			                         		formatter:function (cellvalue, options, rowObject){ return formatTypeTextBox(cellvalue, options, rowObject,'x0')}}   
			                        ],
    		     colTotals: true, 
    		     colTotalsText: "Total" ,
    		     frozenStaticCols: true,
    		     skipSortByY: true
		 },
		// grid options
		 {
		 	    grouping: false, 
		 	   	gridview: true,
		 	    width:"100%",
		 	    height:"100%",
		 	    caption: "Matrix ",
		 	    emptyrecords: 'No Data.',
		 	    loadComplete : function() {
		 	    	calculateFooterTotal("grid1","x1");
				}
		},{  type: "POST",reader : "gridRecords" }).jqGrid("gridResize");

**Comment by OlegKi** [comment] 2015-10-07 16:13
Sorry, but I need full demo to be able to reproduce the problem. The `data` is undefined like `calculateFooterTotal`, `formatTypeTextBox`, `calculateWidth` and probably some other.

**Comment by OlegKi** [comment] 2015-10-09 09:39
Please retry your code using free jqGrid directly from RawGit or CDN (see [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs)). Is the described problem exist if you use the latest sources of free jqGrid?

**Comment by OlegKi** [comment] 2015-11-18 10:58
The issue is still opened. Please provide the demo which can be used to reproduce the problem or close the issue.

**Comment by OlegKi** [comment] 2015-12-18 09:05
I close the issue, because I didn't get any responses from you. You can post additional information and reopen the issue any time later.

**Closed by OlegKi** 2015-12-18 09:05 UTC
