### ISSUE TITLE
Bug - Drag and Drop issue with grouping View with target row empty

### ISSUE THREAD

**Issue by boulepick** [free-jqgrid/jqGrid#268] opened 2016-09-09 14:45 UTC
Hi Oleg,

just want to report an issue with drag and drop from one grid to another that has subgid and grouping view enabled. basically if the row of the subgrid is empty and grouping view enable, it will not allow the drop event from the source grid. when i disable the grouping view on the target subgrid, it works fine i'm able to drop to an empty row of the subgrid. check this fiddle https://jsfiddle.net/boulepick/rb6puhsm/ . enable and disable the grouping view and you will the issue.

cheers

**Comment by boulepick** [comment] 2016-12-07 01:05
ok solved my issue by adding these simple lines in the "Load Complete" of my subgrid
//check if we have data to enable grouping view
                                   
```
 var hasData = $this.jqGrid('getDataIDs');
 if(typeof hasData === 'undefined' || hasData.length === 0){
    $this.jqGrid('groupingRemove');
  }
```

**Comment by OlegKi** [comment] 2016-12-07 13:05
Thank you for reporting of other people about the workaround. Please close the issue if the problem is solved now.

**Closed** 2016-12-07 13:10 UTC
