### ISSUE TITLE
How to sort the yDimension group

### ISSUE THREAD

**Issue by mrjumpy** [free-jqgrid/jqGrid#83] opened 2015-06-08 02:37 UTC
Take a look:
http://codepen.io/mrjumpy/pen/RPRXjM?editors=001
If we want to sort yDimension `month`, 
let month's order in every group become ASC or customization its order.(it's DESC now)
How could we do?
If could, maybe every dimension should have the feature, too.

**Comment by OlegKi** [comment] 2015-06-08 10:17
If I correctly understand your problem then you should just add `sorttype: "integer"` property to `yDimension` items which corresponds have `dataName: 'sellyear'` and `dataName: 'sell month'`. See the modified demo http://codepen.io/anon/pen/RPVQNG 

In general I can imagine to add `sortorder` (`sortDirection`) additionally to `sorttype` for `yDimension` items. I'm not sure whether the corresponding changes in the code of pivot module are simple enough or not. If it's not really required then I would set the enhancement in the list of new features of the next release. It's the mostly important now for me to fix the bugs in the existing code to publish mostly clean code of free jqGrid 4.9.

**Comment by mrjumpy** [comment] 2015-06-08 10:46
I have a real example for you. Also my clients ask me.
http://codepen.io/mrjumpy/pen/eNWVZX?editors=001

For example, if our clients are German, in the yDimension, they want to in front of `America`.
Similarly, if the clients are Taiwanese, they also want to be the first.
If we don't have `sortorder`,  the sort of context can't be resolved.

But I agree with your thought that to publish jkqGrid4.9 and bug fix, I can understand that.
So, maybe this is a enhancement. 

Thank for your every bug-fix. I really appreciate that. :+1:

**Comment by OlegKi** [comment] 2015-06-08 11:59
You current problem can be solved very easy because your input data are already sorted like you as need. You can use `skipSortByY: true` option (see [the part](https://github.com/free-jqgrid/jqGrid/wiki/jqPivot-in-version-4.9#some-additional-options) of the documentation).

In more common case you can specify `compare` callback function inside of `yDimension` instead of `sorttype`. I didn't yet described the feature in [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/jqPivot-in-version-4.9), but the feature is already implemented. See [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.9.0-rc1/js/grid.pivot.js#L160) of code. 

So one can define the following callback function inside of `yDimension`
```JavaScript
compare: function (a, b) {
    // make German the first (less as all other)
    if (a === "Germany" || (b !== "Germany" && a < b)) { return -1; }
    if (b === "Germany" || a > b) { return 1; }
    return 0;
}
```
You will set `"Germany"` at the first place during sorting. See

http://codepen.io/anon/pen/QbvQBz

**Comment by mrjumpy** [comment] 2015-06-09 02:03
Cool :+1: 
I can implement my feature through this one.
Thank you!! Oleg.

**Comment by OlegKi** [comment] 2015-06-09 06:34
Small remark. The above `compare` implementation should of cause be fixed to return 0 in case that both `a` and `b` are "Germany". The code which I posted before returns -1 in the case which is wrong. So the code could be for example
```JavaScript
compare: function (a, b) {
    // make German the first (less as all other)
    if (a === "Germany") {
        return b === "Germany" ? 0 : -1;
    }
    if (b === "Germany" || a > b) { return 1; }
    if (a < b) { return -1; }
    return 0;
}
```
If the input data could contains `null` or `undefined` values (or contains other non-string data) then one can modify the `compare` method more to place. For example I uses the following callback function by default in `jqPivot` for comparing the strings:
```JavaScript
stringCompare = function (a, b) {
	var a1 = a, b1 = b; 
	if (a1 == null) { a1 = ""; } // we will place undefined and null values as the lowest TOGETHER with ""
	if (b1 == null) { b1 = ""; }
	// be sure that we have no other input data (Number, Date and so on)
	a1 = String(a1);
	b1 = String(b1);
	if (!this.caseSensitive) {
		a1 = a1.toUpperCase();
		b1 = b1.toUpperCase();
	}
	if (a1 === b1) {
		if (a === b) {//typeof a === typeof b) {
			return 0;
		}
		// either a or b is undefined or null
		if (a === undefined) { return -1; } // make undefined less as all other
		if (b === undefined) { return 1; }
		if (a === null) { return -1; } // make null less as all other with the exception undefined
		if (b === null) { return 1; }
	}
	if (a1 < b1) {
		return -1;
	}
	return 1;
}
```
The line where `this.caseSensitive` will be used should be interesting too. It shows that `this` will be set to `instanceof ArrayOfFieldsets`. So one can implement compare method which use case insensitive compare depend of the `caseSensitive` used in jqPivot options.

**Comment by mrjumpy** [comment] 2015-06-10 05:20
I have some problems, 
can I get group level in the `compare` function?

**Comment by OlegKi** [comment] 2015-06-10 05:24
No, but you can specify **different** `compare` function for every `yDimension` item.

**Comment by mrjumpy** [comment] 2015-06-10 05:36
OK,
http://codepen.io/mrjumpy/pen/eNWVZX?editors=001
If I want to `2015 Germany` in front of `2015 America`,
But, `2011 Germany` still in the end on `2011`
Is it possible?

**Comment by OlegKi** [comment] 2015-06-10 05:41
I commented one like with `return 1;` at the beginninvg of the code and all works now: http://codepen.io/anon/pen/MwoYOO

**Comment by mrjumpy** [comment] 2015-06-10 05:45
But my needed is enable `2011's Germany` on the end.
And `2015's Germany` on the first.

**Comment by OlegKi** [comment] 2015-06-10 06:57
Sorry, but I don't full understand how you want to formulate your searching criteria? Is (2015, "Germany") the only vector of input data which you want to have the first and all other should be sorted in the standard way?

It seems to me that your problem could be solved by allow to specify custom sorting method for **the vector** of data. The signature of the method could be the same as by [compareVectorsEx](https://github.com/free-jqgrid/jqGrid/blob/v4.9.0-rc1/js/grid.pivot.js#L165) method of `ArrayOfFieldsets`:
```JavaScript
function (vector1, vector2) {
// it should return object with two properties: index and result
// the result property corresponds to the standard compare: -1, 0, 1
// the index property should be -1 if the vectors are the same (equal)
// the index should be the index in the vector where vector1 and vector2
// are different
}
```
I could add the callback in the jqPrivot options. In the way you would provide your full custom vector compere. Would it solves your problem?

**Comment by mrjumpy** [comment] 2015-06-10 07:28
I'm not sure I really understand what the `compareVectorsEx` is.
Maybe I tell you what is exactly feature that I implement now.

I enable the header drag and drop so that the user can drag & drop whatever order they want.
When I'm using `compare` function. 
It's fine in the first `<tr>` of the pivot header. They can drag & drop what they want it.
Because it's same group, same sorting logic.

But when it comes to second `<tr>` of the pivot header, it will be a problem.
Just like the previous example I show you. 
The problem is the sorting formula is fixed. And I can't distinguish where the group is.
So the order just the same in every group.
But I need the the different order in the different group(year).

For example:
In `2011`, I want to Germany first.
In `2015`, I want to America first.
Maybe another grouped year has another sorting. It's up to the user's drag & drop result.

**Comment by OlegKi** [comment] 2015-06-10 08:59
It sounds like **absolutely another problem**.

Drag & drop inside of grouping headers is not possible at all in jqGrid or free jqGrid less as 4.9. I implemented the possibility in free jqGrid 4.9, with restriction of dropping **inside of the same group**. What you want to implement have not so much sense in common case (if I understand you correctly)  because you want to allows the user to extract the column of sub-header from the header structure and move it in*separate* header, which can break the current structure of headers and create additional (unneeded for the common case) header group.

Moreover **you want even not only drag & drop of columns of the grid, but the drag & drop column headers**. If you examine exactly the demo http://codepen.io/anon/pen/MwoYOO you will see that the most columns have "Price" or "Quntity" (you mean probably Quantity) as label. The texts "Germany" and "2011" are part of column headers which can't be drag & dropped by the standard jqGrid implementation.

If you do need to implement drag & drop of column headers it will be not so simple code and you will probably need to generate new array of column headers and recreate all column headers based on new information.

**Comment by mrjumpy** [comment] 2015-06-10 09:33
OK! Thank you very much.
Now, we don't drag and drop.
we're sort it directly using `vector function`.
How should we do?
change `compareVectorsEx`  directly?
Or, we just have another callback function can do that?

**Comment by OlegKi** [comment] 2015-06-10 09:42
First of all you can just sort the input data so like you need and to use `skipSortByY: true` option.

Seconds I will change the code of jqPivot and introduce new option - the callback `compareVectors`. I will write new comment after making the corresponding changes and committing the changes to the main code of free jqGrid on GitHub.

**Comment by OlegKi** [comment] 2015-06-10 10:22
I made the changes in the code of jqPivot. One can specify now custom vector-sorting function for x or y dimension. For example you can use the following `compareVectorsByY` callback to make ("2011", "Germany") the first inside the `"2011"` group only:
```JavaScript
compareVectorsByY: function (vector1, vector2) {
    var fieldLength = this.fieldLength, iField, compareResult;

    if (fieldLength === 2) {
        if (vector1[0] === "2011" && vector1[1] === "Germany") {
            if (vector2[0] === "2011" && vector2[1] === "Germany") {
                return {
                    index: -1,
                    result: 0
                };
            }
            return {
                index: vector2[0] === "2011" ? 1 : 0,
                result: -1
            };
        }
        // any vector1 is larger as vector2 ("2011", "Germany")
        if (vector2[0] === "2011" && vector2[1] === "Germany") {
            return {
                index: vector2[0] === "2011" ? 1 : 0,
                result: 1
            };
        }
    }

    for (iField = 0; iField < fieldLength; iField++) {
        compareResult = this.fieldCompare[iField](vector1[iField], vector2[iField]);
        if (compareResult !== 0) {
            return {
                index: iField,
                result: compareResult
            };
        }
    }
    return {
        index: -1,
        result: 0
    };
}
```
See the demo http://codepen.io/anon/pen/waeKXL

**Comment by OlegKi** [comment] 2015-07-28 15:23
I think, that the problem is solved now. So I'm closing the issue.

**Closed by OlegKi** 2015-07-28 15:23 UTC
Labels: pivot, question
