### ISSUE TITLE
rtl version and pager icon direction

### ISSUE THREAD

**Issue by afattahi54** [free-jqgrid/jqGrid#275] opened 2016-10-29 08:04 UTC
When we set the page direction to RTL, the direction of pager icons does not change.

Please see https://jsfiddle.net/tn48Letf/ 

The old jqGrid, used to switch the icon directions, please see: http://jsfiddle.net/58g6e61f/

Thanks!

**Comment by OlegKi** [comment] 2016-10-29 10:17
Do you mean that the correct look of the icons in RTL mode would be

- "ui-icon-seek-first" of "fa-step-backward" should be used for go to the **last** page
- "ui-icon-seek-prev" or "fa-backward" should be used as the **next** page
- "ui-icon-seek-next" or "fa-forward" should be used as the **previous** page
- "ui-icon-seek-end" of "fa-step-forward" should be used for go to the **first** page

Is it correct in general for RTL mode? If you confirm that then I would fix the problem in free jqGrid.

**Comment by OlegKi** [comment] 2016-10-29 17:04
I though more about the problem and posted [the fix](https://github.com/free-jqgrid/jqGrid/commit/7c8032443254cebe23a5ed57546ea7af0cae08d2). Please verify, whether the current code produces the correct pager items. I'm not sure, which language is your first one (the native language). Look at the modified demo https://jsfiddle.net/OlegKi/tn48Letf/1/.

By the way, the locale file `grid.locale-fa.js`, `grid.locale-ar.js` and other contain some non-localized texts (see [here](https://github.com/free-jqgrid/jqGrid/blob/v4.13.4/js/i18n/grid.locale-fa.js#L36), [here](https://github.com/free-jqgrid/jqGrid/blob/v4.13.4/js/i18n/grid.locale-fa.js#L65-L69) and [here](https://github.com/free-jqgrid/jqGrid/blob/v4.13.4/js/i18n/grid.locale-fa.js#L122-L125)). It would be helpful for other if you would translate the missing texts and sent there to me. You can post pull request or just send the translations in the next comment.

**Comment by afattahi54** [comment] 2016-10-30 04:32
Thanks, the icon in produced grid is fine . 
Here are translations:

``````
showhide: "تغییر وضعیت نمایش جدول",
.....
addGroupTitle: "اضافه کردن عنوان گروه",
deleteGroupTitle: "حذف عنوان گروه",
addRuleTitle: "اضافه کردن  عنوانقانون",
deleteRuleTitle: "حذف عنوان قانون",
operandTitle: "برای انتخاب گزینه های جستجو کلیک کنید",

`````

**Comment by OlegKi** [comment] 2016-10-30 12:35
Thanks for the information. I posted [the commit](https://github.com/free-jqgrid/jqGrid/commit/6a5bfc7f5196fe393050e28e22c6bf590994067a), which contains all your changes and some other changes of the week days and months which I get from [the official Unicode CLDR Charts](http://www.unicode.org/cldr/charts/30/verify/dates/fa.html).

Some other texts are still in English: "savetitle" and "canceltitle" (see [here](https://github.com/free-jqgrid/jqGrid/blob/master/js/i18n/grid.locale-fa.js#L122-L125)). Try https://jsfiddle.net/OlegKi/tn48Letf/3/, click on any row. You will see Save and Cancel buttons in the navigator bar added by `inlineNav`. Hover the buttons and you will see the texts "Save row" and "Cancel row editing" displayed as Tooltips. Could you translate the texts too to make full translation of the `grid.locale-fa.js`?

**Comment by OlegKi** [comment] 2016-11-01 11:21
The bug reported in the issue is fixed. I'm waiting still your feedback about translation of [the words](https://github.com/free-jqgrid/jqGrid/blob/master/js/i18n/grid.locale-fa.js#L122-L125) to Persian language, but it's a separate subject. Thus I close the issue.

**Closed by OlegKi** 2016-11-01 11:21 UTC
Labels: bug

**Comment by afattahi54** [comment] 2016-11-01 18:17
Thanks.. Here are the remaining translations:

````
savetitle: "ذخیره سطر",

canceltitle: "انصراف از تغییر سطر"
`````

**Comment by OlegKi** [comment] 2016-11-01 18:26
Thank you. I included the changes in the main code of free jqGrid (see [the commit](https://github.com/free-jqgrid/jqGrid/commit/b8cc845803a0c2e78f7aff39c3295b47d6fc5ed4)).
