### ISSUE TITLE
Cell editing

### ISSUE THREAD

**Issue by beckmi** [free-jqgrid/jqGrid#175] opened 2015-11-16 18:28 UTC
I am trying to use cellEdit mode with cellsubmit set to 'clientArray'
using navButtonAdd I added a button to save all changed cells
pressing the button while a cell is in edit mode I always get wrong results from function getChanged Cells:
calling the function with parameter 'dirty' never delivers the active cell - no matter if it's changed or not
calling the function with parameter 'all' the active cell is shown with an empty value if another cell in that row was edited, no matter what value it has

**Comment by OlegKi** [comment] 2015-11-16 22:22
Please provide the demo with the test data, which I could use to reproduce the problem. Please use **non-minimized** version of free jqGrid (`jquery.jqgrid.src.js`), for example direcly from GitHub (see [here](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs#access-githib-code-from-rawgit)). You can create the demo on JSFiddle for example.

**Comment by OlegKi** [comment] 2015-12-18 09:04
Hi @beckmi ,

I didn't get any response from you. Because of that I close the issue. You can post me the demo, which can be used to reproduce the problem any time later and reopen the issue.

**Closed by OlegKi** 2015-12-18 09:04 UTC
